objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AsiaMaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewOdrSalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.SalesAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.SalesAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Maintenance Contract Management (SalesAccount)</relationshipLabel>
        <relationshipName>ASalesOdr_Pipeline_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ShipmentAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ShipmentAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Maintenance Contract Management (ShipmentAccount)</relationshipLabel>
        <relationshipName>ASalesOdr_Pipeline_Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Maintenance Contract Management</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Maintenance Contract Management No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_MaintenanceListNewCsv_ctrlTest.cls
@isTest
private class JEOLAsia_MaintenanceListNewCsv_ctrlTest {

	private static User testUser = JEOLAsia_TestDataFactory.createTestUser();

	private static testMethod void test01()
	{
		System.runAs (testUser)
		{
			Test.startTest();

			Account acc = new account();
			acc.Name = 'testAcc1';
			acc.Code__c = '01';
			insert acc;

			Account acc2 = new account();
			acc2.Name = 'testAcc2';
			acc2.Code__c = '02';
			insert acc2;

			AsiaMaintenanceContractManagement__c contMan = new AsiaMaintenanceContractManagement__c();
			contMan.NewOdrSeries__c = 'testAP';
			contMan.NewOdrSalesStaff__c = testUser.Id;
			contMan.NewOdrSalesAccount__c = acc.Id;
			contMan.NewOdrShipmentAccount__c = acc2.Id; 
			insert contMan;

			PageReference pageRef = Page.JEOLAsia_MaintenanceListNewCsv;
			Map<String, String> params = new Map<String, String>();
	        params.put('id', String.valueOf(contMan.id));
	        params.put('CUSTOMERCODE', 't01');
	        params.put('CUSTOMERNAME', 'testName1');
	        params.put('CUSTCODETYPE', '1');
	        params.put('CUSTNAMETYPE', '1');
	        params.put('SALESRESPONSIBLE', '0001');
	        params.put('SHIPMENTADDRESS', 'testAddress');
	        params.put('QUOTATIONCREATED', '1');
	        params.put('SACREATED', '1');
	        params.put('EXISTLASTACTIVITYDATE', '1');
	        params.put('LASTACTIVITYDATEFROM', String.valueOf(Date.parse('2017/05/01')));
	        params.put('LASTACTIVITYDATETO', String.valueOf(Date.parse('2017/05/31')));
	        params.put('QUOTATIONSENTDATEFROM', String.valueOf(Date.parse('2017/05/01')));
	        params.put('QUOTATIONSENTDATETO', String.valueOf(Date.parse('2017/05/31')));
	        params.put('PERIODFROM', String.valueOf(Date.parse('2017/05/01')));
	        params.put('PERIODTO', String.valueOf(Date.parse('2017/05/31')));
	        pageRef.getParameters().putAll(params);

	        Test.setCurrentPage(pageRef);

	        JEOLAsia_MaintenanceListNewCsv_ctrl ctrl = new JEOLAsia_MaintenanceListNewCsv_ctrl();

	        ctrl.getFileName();

			Test.stopTest();
		}
	}

	private static testMethod void test02()
	{
		System.runAs (testUser)
		{
			Test.startTest();

			Account acc = new account();
			acc.Name = 'testAcc1';
			acc.Code__c = '01';
			insert acc;

			Account acc2 = new account();
			acc2.Name = 'testAcc2';
			acc2.Code__c = '02';
			insert acc2;

			AsiaMaintenanceContractManagement__c contMan = new AsiaMaintenanceContractManagement__c();
			contMan.NewOdrSeries__c = 'testAP';
			contMan.NewOdrSalesStaff__c = testUser.Id;
			contMan.NewOdrSalesAccount__c = acc.Id;
			contMan.NewOdrShipmentAccount__c = acc2.Id; 
			insert contMan;

			PageReference pageRef = Page.JEOLAsia_MaintenanceListNewCsv;
			Map<String, String> params = new Map<String, String>();
	        params.put('id', String.valueOf(contMan.id));
	        params.put('CUSTOMERCODE', 't02');
	        params.put('CUSTOMERNAME', 'testName2');
	        params.put('CUSTCODETYPE', '2');
	        params.put('CUSTNAMETYPE', '2');
	        params.put('SALESRESPONSIBLE', '0002');
	        params.put('SHIPMENTADDRESS', 'testAddress');
	        params.put('QUOTATIONCREATED', '2');
	        params.put('SACREATED', '2');
	        params.put('EXISTLASTACTIVITYDATE', '2');
	        pageRef.getParameters().putAll(params);

	        Test.setCurrentPage(pageRef);

	        JEOLAsia_MaintenanceListNewCsv_ctrl ctrl = new JEOLAsia_MaintenanceListNewCsv_ctrl();
	        
			Test.stopTest();
		}
	}
}