objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>住所</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>見積書</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Undergraduate__c</fullName>
        <inlineHelpText>Undergraduate</inlineHelpText>
        <label>学部・事業所</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>Bill__c</fullName>
        <label>請求書</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingSystem__c</fullName>
        <label>請求方式</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CarryDeliveryTimeFormula__c</fullName>
        <formula>Datevalue(CarryDeliveryTime__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>搬入納期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CustomerOrder__c</fullName>
        <label>顧客オーダ</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>納品書</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Kosohin__c</fullName>
        <label>後送品</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelPI__c</fullName>
        <formula>UnitBodyLink__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>機種</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderAmount__c</fullName>
        <label>オーダ額</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OrderDateFormula__c</fullName>
        <formula>Datevalue(OrderDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>オーダ日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrdersMemp__c</fullName>
        <label>受注メモ</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaperDivision__c</fullName>
        <label>指定用紙区分</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <label>製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>見積書</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (販売先取引先)</relationshipLabel>
        <relationshipName>SalesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesContactPosition__c</fullName>
        <label>販売先担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesContactTel__c</fullName>
        <label>販売先担当者TEL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesStaff__c</fullName>
        <label>営業担当名</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesTantoshya__c</fullName>
        <label>販売先担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SchedulingDivision__c</fullName>
        <label>分納区分</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (出荷先取引先)</relationshipLabel>
        <relationshipName>ShipmentAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentContactPosition__c</fullName>
        <label>出荷先担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentContact_Tel__c</fullName>
        <label>出荷先担当者TEL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentTantosha__c</fullName>
        <label>出荷先担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxAmount__c</fullName>
        <label>税額</label>
        <summarizedField>SalesOrderLine__c.Zegaku__c</summarizedField>
        <summaryForeignKey>SalesOrderLine__c.SalesOrderLink__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesOrderLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>金額</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NyukaYoteDateFormula__c</fullName>
        <formula>Datevalue(NyukaYoteDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>入荷予定日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderDateFormula__c</fullName>
        <formula>Datevalue(OrderDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>オーダ日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderQuantity__c</fullName>
        <label>オーダ数量</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderUnit__c</fullName>
        <label>オーダ単位</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PositionText__c</fullName>
        <formula>TEXT( Position__c )</formula>
        <label>位置</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>価格</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>販売オーダライン</relationshipLabel>
        <relationshipName>SalesOrderLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>商品名</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <label>製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShukaSuryo__c</fullName>
        <label>出荷数量 (棚卸単位)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShukkaDateFormula__c</fullName>
        <formula>Datevalue(ShukkaDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>出荷日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShukkaStatus__c</fullName>
        <label>出荷状況</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Soko__c</fullName>
        <label>倉庫</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>販売オーダライン</label>
    <nameField>
        <label>販売オーダ</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceOrder__c.object
<CustomObject>
    <fields>
        <fullName>CustomerOrder__c</fullName>
        <label>顧客オーダ</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Kosohin__c</fullName>
        <label>後送品</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderDateFormula__c</fullName>
        <formula>Datevalue(OrderDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>オーダ日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductItem__c</fullName>
        <formula>Customer__r.UnitBodyLink__r.ItemLink__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>品目</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>サービスオ販売先取引先ーダ ()</relationshipLabel>
        <relationshipName>ServiceOrders_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesContactTel__c</fullName>
        <label>販売先担当者TEL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesStaff__c</fullName>
        <label>営業担当名</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>サービスオーダ</relationshipLabel>
        <relationshipName>ServiceOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>サービスオーダ</label>
    <nameField>
        <label>サービスオーダ</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ServiceOrderControl__c.object
<CustomObject>
    <fields>
        <fullName>NyukaYoteDateFormula__c</fullName>
        <formula>Datevalue(NyukaYoteDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>入荷予定日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>サービスオーダ材料費</relationshipLabel>
        <relationshipName>ServiceOrderControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceOrder__c</fullName>
        <label>サービスオーダ</label>
        <referenceTo>ServiceOrder__c</referenceTo>
        <relationshipLabel>サービスオーダ材料費</relationshipLabel>
        <relationshipName>ServiceOrderControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShukaSuryo__c</fullName>
        <label>出荷数量</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShukkaDateFormula__c</fullName>
        <formula>Datevalue(ShukkaDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>出荷日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Suryo__c</fullName>
        <label>数量</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>サービスオーダ材料費</label>
    <nameField>
        <label>サービスオーダ材料費名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>本体号機 (販売先取引先)</relationshipLabel>
        <relationshipName>Sales_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_JuchuOrderView.cls
public with sharing class JEOL_JuchuOrderView {
    
    public Boolean hasError{get; set;}
    public ViewWrapper target{get; set;}
    private static final String SOBJECT_KEYPREFIX_SALES = SalesOrder__c.SobjectType.getDescribe().getKeyPrefix();
    private static final String SOBJECT_KEYPREFIX_SERVICE = ServiceOrder__c.SobjectType.getDescribe().getKeyPrefix();

    public JEOL_JuchuOrderView() {
        try {
            String targetId = ApexPages.currentPage().getParameters().get('Id');
            if (targetId == null) {
                throw new JEOLException('');
            }
            
            Sobject targetRec = getRecord(targetId);
            
            if (targetRec == null) {
                throw new JEOLException('');
            }
            
            this.target = new ViewWrapper(targetRec);
            this.hasError = false;
        } catch(Exception e) {
            this.hasError = true;
            Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.FATAL, e.getMessage()));
        }
    }
    
    private Sobject getRecord(String targetId) {
        String soql;
        if (targetId.startsWith(SOBJECT_KEYPREFIX_SALES)) {
            soql = getSalesOrderQueryStr(targetId);
        }
        if (targetId.startsWith(SOBJECT_KEYPREFIX_SERVICE)) {
            soql = getServiceOrderQueryStr(targetId);
        }
        SObject targetRec = null;
        if (String.isNotBlank(soql)) {
            List<SObject> targetRecs = Database.query(soql);
            for (SObject rec: targetRecs) {
                targetRec = rec;
                break;
            }
        }
        return targetRec;
    }
    
    
    private String getSalesOrderQueryStr(String targetId) {

        String str = ' SELECT ' + 
                        ' Id ' +
                        ' ,Name' +
                        ' ,SalesAccount__r.Code__c' +
                        ' ,SalesAccount__r.Name' +
                        ' ,SalesAccount__r.Undergraduate__c' +
                        ' ,ShipmentAccount__r.Code__c' +
                        ' ,ShipmentAccount__r.Name' +
                        ' ,ShipmentAccount__r.Undergraduate__c' +
                        ' ,OrderDateFormula__c' +
                        ' ,CarryDeliveryTimeFormula__c' +
                        ' ,SalesStaff__c' +
                        ' ,ProductNumber__c' +
                        ' ,OrdersMemp__c' +
                        ' ,OrderAmount__c' +
                        ' ,TaxAmount__c' +
                        ' ,CurrencyIsoCode' +
                        ' ,SalesContactPosition__c' +
                        ' ,SalesAccount__r.Address__c' +
                        ' ,SalesTantoshya__c' +
                        ' ,SalesContactTel__c' +
                        ' ,ShipmentContactPosition__c' +
                        ' ,ShipmentAccount__r.Address__c' +
                        ' ,ShipmentTantosha__c' +
                        ' ,ShipmentContact_Tel__c' +
                        ' ,CustomerOrder__c' +
                        ' ,SchedulingDivision__c' +
                        ' ,Kosohin__c' +
                        ' ,BillingSystem__c' +
                        ' ,PaperDivision__c' +
                        ' ,Quotation__c' +
                        ' ,Invoice__c' +
                        ' ,Bill__c' +
                        ' ,ModelPI__c' +
                        ' ,UnitBody__c' +
                        ',( ' +
                            ' SELECT ' + 
                                ' Id ' +
                                ' ,CurrencyIsoCode' +
                                ' ,Name' +
                                ' ,ProductNumber__c' +
                                ' ,PositionText__c' +
                                ' ,ProductItem__r.Name' +
                                ' ,ProductName__c' +
                                ' ,OrderQuantity__c' +
                                ' ,OrderUnit__c' +
                                ' ,Price__c' +
                                ' ,Amount__c' +
                                ' ,Soko__c' +
                                ' ,NyukaYoteDateFormula__c' +
                                ' ,ShukaSuryo__c' +
                                ' ,ShukkaDateFormula__c' +
                                ' ,ShukkaStatus__c' +
                                ' ,ZaikoKanriKubun__c' +
                            ' FROM ' +
                                 ' SalesOrderLines__r ' +
                            ' ORDER BY ' +
                                ' Name ' +
                         ') ' +
                    ' FROM ' +
                        ' SalesOrder__c' +
                    ' WHERE ' +
                        ' Id =: targetId';

        return str;
    }

    private String getServiceOrderQueryStr(String targetId) {

        String str = 'SELECT ' +
                        ' Id ' +
                        ' ,CurrencyIsoCode' +
                        ' ,Name' +
                        ' ,SalesAccount__r.Code__c' +
                        ' ,SalesAccount__r.Name' +
                        ' ,SalesAccount__r.Undergraduate__c' +
                        ' ,ShipmentAccount__r.Code__c' +
                        ' ,ShipmentAccount__r.Name' +
                        ' ,ShipmentAccount__r.Undergraduate__c' +
                        ' ,OrderDateFormula__c' +
                        ' ,DesiredDeliveryDateFormula__c' +
                        ' ,SalesStaff__c' +
                        ' ,ProductNo__c' +
                        ' ,SalesContactAffiliation__c' +
                        ' ,SalesAccount__r.Address__c' +
                        ' ,SalesContactName__c' +
                        ' ,SalesContactTel__c' +
                        ' ,ShipToAffiliation__c' +
                        ' ,ShipmentAccount__r.Address__c' +
                        ' ,ShipToContactPerson__c' +
                        ' ,ShipToContactTEL__c' +
                        ' ,CustomerOrder__c' +
                        ' ,CallCenterReceptionNo__c' +
                        ' ,BunnoKubun__c' +
                        ' ,Kosohin__c' +
                        ' ,SekyuHoshiki__c' +
                        ' ,ShiteYoshiKubun__c' +
                        ' ,Mitsumori__c' +
                        ' ,Nohin__c' +
                        ' ,Sekyu__c' +
                        ' ,Model__c' +
                        ' ,UnitBody__c' +
                        ' ,Remarks__c' +
                        ',( ' + 
                            ' SELECT ' +
                                ' Id' +
                                ' ,CurrencyIsoCode' +
                                ' ,Name' +
                                ' ,ProductItem__r.Name' +
                                ' ,ProductItem__r.JapaneseName__c' +
                                ' ,Suryo__c' +
                                ' ,Tani__c' +
                                ' ,ProductItem__r.Soko__c' +
                                ' ,NyukaYoteDateFormula__c' +
                                ' ,ShukaSuryo__c' +
                                ' ,ShukkaDateFormula__c' +
                                ' ,ShukkaStatus__c' +
                                ' ,ProductItem__r.ZaikoKanriKubun__c' +
                            ' FROM ' +
                                ' ServiceOrderControls__r ' +
                            ' ORDER BY ' +
                                ' Name ' +
                        ' ) ' +
                    ' FROM ' +
                        ' ServiceOrder__c ' +
                    ' WHERE ' +
                        ' Id =: targetId ';

        return str;
    }
    
    public class ViewWrapper {
        
        private SObject rec;
        private Boolean isSales = false;
        private Boolean isService = false;
        
        public viewWrapper(SObject targetRec) {
            String targetId = (String)targetRec.get('id');
            if (targetId.startsWith(SalesOrder__c.SobjectType.getDescribe().getKeyPrefix())) {
                this.isSales = true;
            }
            if (targetId.startsWith(ServiceOrder__c.SobjectType.getDescribe().getKeyPrefix())) {
                this.isService = true;
            }
            if (isSales || isService) {
                this.rec = targetRec;
            } else {
                throw new JEOLException('予期しない操作が行われました。');
            }
        }

        public Boolean getIsSales() {
            return isSales;
        }
        public Boolean getIsService() {
            return isService;
        }

/** ここからgetメイン項目 **/
        public String getOrderNo() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('Name');
            }
            if (isService) {
                ret = (String)rec.get('Name');
            }
            return ret;
        }
        public Date getOrderDate() {
            Date ret;
            if (isSales) {
                ret = (Date)rec.get('OrderDateFormula__c');
            }
            if (isService) {
                ret = (Date)rec.get('OrderDateFormula__c');
            }
            return ret;
        }
        public Date getCarryDeliveryTime() {
            Date ret;
            if (isSales) {
                ret = (Date)rec.get('CarryDeliveryTimeFormula__c');
            }
            if (isService) {
                ret = (Date)rec.get('DesiredDeliveryDateFormula__c');
            }
            return ret;
        }
        public String getSalesStaff() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('SalesStaff__c');
            }
            if (isService) {
                ret = (String)rec.get('SalesStaff__c');
            }
            return ret;
        }
        public String getProductNumber() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('ProductNumber__c');
            }
            if (isService) {
                ret = (String)rec.get('ProductNo__c');
            }
            return ret;
        }
        public String getOrdersMemp() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('OrdersMemp__c');
            }
            if (isService) {
                ret = (String)rec.get('Remarks__c');
            }
            return ret;
        }
        public Decimal getOrderAmount() {
            Decimal ret;
            if (isSales) {
                ret = (Decimal)rec.get('OrderAmount__c');
            }
            if (isService) {
//                ret = (Decimal)rec.get('');
            }
            return ret;
        }
        public Decimal getTaxAmount() {
            Decimal ret;
            if (isSales) {
                ret = (Decimal)rec.get('TaxAmount__c');
            }
            if (isService) {
//                ret = (Decimal)rec.get('');
            }
            return ret;
        }
        public String getCurrencyIsoCode() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('CurrencyIsoCode');
            }
            if (isService) {
//                ret = (String)rec.get('');
            }
            return ret;
        }
        public Decimal getSumAmount() {
            Decimal ret;
            Decimal ordAmt = 0;
            Decimal taxAmt = 0;
            if (isSales) {
                if (rec.get('OrderAmount__c')!=null) {
                    ordAmt = (Decimal)rec.get('OrderAmount__c');
                }
                if (rec.get('TaxAmount__c')!=null){
                    taxAmt = (Decimal)rec.get('TaxAmount__c');
                }
                ret = ordAmt + taxAmt;
            }
            if (isService) {
//                ret = (String)rec.get('');
            }
            return ret;
        }
        public String getSalesContactPosition() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('SalesContactPosition__c');
            }
            if (isService) {
                ret = (String)rec.get('SalesContactAffiliation__c');
            }
            return ret;
        }
        public String getSalesTantoshya() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('SalesTantoshya__c');
            }
            if (isService) {
                ret = (String)rec.get('SalesContactName__c');
            }
            return ret;
        }
        public String getSalesContactTel() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('SalesContactTel__c');
            }
            if (isService) {
                ret = (String)rec.get('SalesContactTel__c');
            }
            return ret;
        }
        public String getShipmentContactPosition() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('ShipmentContactPosition__c');
            }
            if (isService) {
                ret = (String)rec.get('ShipToAffiliation__c');
            }
            return ret;
        }
        public String getShipmentTantosha() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('ShipmentTantosha__c');
            }
            if (isService) {
                ret = (String)rec.get('ShipToContactPerson__c');
            }
            return ret;
        }
        public String getShipmentContactTel() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('ShipmentContact_Tel__c');
            }
            if (isService) {
                ret = (String)rec.get('ShipToContactTEL__c');
            }
            return ret;
        }
        public String getCustomerOrderNo() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('CustomerOrder__c');
            }
            if (isService) {
                ret = (String)rec.get('CustomerOrder__c');
            }
            return ret;
        }
        public String getCallCenterReceptionNo() {
            String ret;
            if (isSales) {
//                ret = (String)rec.get('');
            }
            if (isService) {
                ret = (String)rec.get('CallCenterReceptionNo__c');
            }
            return ret;
        }
        public String getSchedulingDivision() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('SchedulingDivision__c');
            }
            if (isService) {
                ret = (String)rec.get('BunnoKubun__c');
            }
            return ret;
        }
        public String getKosohin() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('Kosohin__c');
            }
            if (isService) {
                ret = (String)rec.get('Kosohin__c');
            }
            return ret;
        }
        public String getBillingSystem() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('BillingSystem__c');
            }
            if (isService) {
                ret = (String)rec.get('SekyuHoshiki__c');
            }
            return ret;
        }
        public String getPaperDivision() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('PaperDivision__c');
            }
            if (isService) {
                ret = (String)rec.get('ShiteYoshiKubun__c');
            }
            return ret;
        }
        public String getQuotation() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('Quotation__c');
            }
            if (isService) {
                ret = (String)rec.get('Mitsumori__c');
            }
            return ret;
        }
        public String getInvoice() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('Invoice__c');
            }
            if (isService) {
                ret = (String)rec.get('Nohin__c');
            }
            return ret;
        }
        public String getBill() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('Bill__c');
            }
            if (isService) {
                ret = (String)rec.get('Sekyu__c');
            }
            return ret;
        }
        public String getModelPI() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('ModelPI__c');
            }
            if (isService) {
                ret = (String)rec.get('Model__c');
            }
            return ret;
        }
        public String getUnitBody() {
            String ret;
            if (isSales) {
                ret = (String)rec.get('UnitBody__c');
            }
            if (isService) {
                ret = (String)rec.get('UnitBody__c');
            }
            return ret;
        }
/** ここまでgetメイン項目 **/

/** ここからgetオブジェクト **/
        public Account getSalesAccount() {
            Account ret;
            if (isSales) {
                ret = (Account)rec.getSobject('SalesAccount__r');
            }
            if (isService) {
                ret = (Account)rec.getSobject('SalesAccount__r');
            }
            return ret;
        }
        public Account getShipmentAccount() {
            Account ret;
            if (isSales) {
                ret = (Account)rec.getSobject('ShipmentAccount__r');
            }
            if (isService) {
                ret = (Account)rec.getSobject('ShipmentAccount__r');
            }
            return ret;
        }
/** ここまでgetオブジェクト **/

/** ここからgetライン情報 **/
        public List<Sobject> getLines() {
            List<Sobject> ret;
            if (isSales) {
                ret = rec.getSobjects('SalesOrderLines__r');
            }
            if (isService) {
                ret = rec.getSobjects('ServiceOrderControls__r');
            }
            return ret;
        }
/** ここまでgetライン情報 **/

    }

}