objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ProductItem__c.object
<CustomObject>
    <fields>
        <fullName>JapaneseName__c</fullName>
        <label>品目名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (販売先取引先)</relationshipLabel>
        <relationshipName>SalesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrderTypeCode__c</fullName>
        <label>販売オーダタイプコード</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNoItemLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>シリアル番号付品目</label>
        <referenceTo>SerialNoProductItem__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SerialNoItemLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列（装置）</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (出荷先取引先)</relationshipLabel>
        <relationshipName>ShipmentAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBodyLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesOrderLine__c.object
<CustomObject>
    <fields>
        <fullName>ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>販売オーダライン</relationshipLabel>
        <relationshipName>SalesOrderLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrderLink__c</fullName>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>販売オーダライン</relationshipLabel>
        <relationshipName>SalesOrderLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>販売オーダライン</label>
    <nameField>
        <label>販売オーダ</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SerialNoProductItem__c.object
<CustomObject>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目リンク</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>シリアル番号付品目</relationshipLabel>
        <relationshipName>ItemRelation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SalesTargetCustomer__c</fullName>
        <label>販売先取引先コード</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <externalId>true</externalId>
        <label>シリアル番号_連携用</label>
        <length>78</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>シリアル番号付品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceOrder__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>顧客対応票</label>
        <referenceTo>Support__c</referenceTo>
        <relationshipLabel>サービスオーダ</relationshipLabel>
        <relationshipName>ServiceOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductItem__c</fullName>
        <formula>Customer__r.UnitBodyLink__r.ItemLink__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>品目</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>サービスオ販売先取引先ーダ ()</relationshipLabel>
        <relationshipName>ServiceOrders_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>サービスオーダ</relationshipLabel>
        <relationshipName>ServiceOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBodyLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>サービスオーダ</relationshipLabel>
        <relationshipName>ServiceOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>サービスオーダ</label>
    <nameField>
        <label>サービスオーダ</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ServiceOrderControl__c.object
<CustomObject>
    <fields>
        <fullName>ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>サービスオーダ材料費</relationshipLabel>
        <relationshipName>ServiceOrderControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceOrder__c</fullName>
        <label>サービスオーダ</label>
        <referenceTo>ServiceOrder__c</referenceTo>
        <relationshipLabel>サービスオーダ材料費</relationshipLabel>
        <relationshipName>ServiceOrderControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>サービスオーダ材料費</label>
    <nameField>
        <label>サービスオーダ材料費名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support__c.object
<CustomObject>
    <fields>
        <fullName>SerialNoItemsLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>シリアル番号付品目</label>
        <referenceTo>SerialNoProductItem__c</referenceTo>
        <relationshipLabel>顧客対応票</relationshipLabel>
        <relationshipName>SerialNoItems2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBodyLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>顧客対応票</relationshipLabel>
        <relationshipName>Support</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>顧客対応票</label>
    <nameField>
        <label>コールセンター受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>ItemLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>本体号機 (販売先取引先)</relationshipLabel>
        <relationshipName>Sales_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <label>シリアル番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <formula>ItemLink__r.Series__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>系列</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_JutyuOrderList_ctrlTest.cls
/*
@IsTest
private class JEOL_JutyuOrderList_ctrlTest {

    // Cookei用定数 販売タブ
    private static final String COOKIE_LABEL_SALES_CO_NO = 'customerOrderNo_sales';
    private static final String COOKIE_LABEL_SALES_SEBAN = 'Seban_sales';
    private static final String COOKIE_LABEL_SALES_AREA = 'Area_sales';
    private static final String COOKIE_LABEL_SALES_USER_CODE = 'UserCode_sales';
    private static final String COOKIE_LABEL_SALES_ACCOUNT_TYPE = 'AccountType_sales';
    private static final String COOKIE_LABEL_SALES_ACCOUNT_CODE = 'AccountCode_sales';
    private static final String COOKIE_LABEL_SALES_ACCOUNT_NAME = 'AccountName_sales';
    private static final String COOKIE_LABEL_SALES_ACCOUNT_PHONE = 'AccountPhone_sales';
    private static final String COOKIE_LABEL_SALES_PARTS_NO = 'PartsNo_sales';

    // Cookei用定数 サービスタブ
    private static final String COOKIE_LABEL_SERVICE_CO_NO = 'customerOrderNo_service';
    private static final String COOKIE_LABEL_SERVICE_CC_NO = 'callCenterReceptionNo_service';
    private static final String COOKIE_LABEL_SERVICE_UNIT_BODY = 'unitBody_service';
    private static final String COOKIE_LABEL_SERVICE_KSRY = 'KishuRyakushou_service';
    private static final String COOKIE_LABEL_SERVICE_SEBAN = 'Seban_service';
    private static final String COOKIE_LABEL_SERVICE_AREA = 'Area_service';
    private static final String COOKIE_LABEL_SERVICE_USER_CODE = 'UserCode_service';
    private static final String COOKIE_LABEL_SERVICE_ACCOUNT_TYPE = 'AccountType_service';
    private static final String COOKIE_LABEL_SERVICE_ACCOUNT_CODE = 'AccountCode_service';
    private static final String COOKIE_LABEL_SERVICE_ACCOUNT_NAME = 'AccountName_service';
    private static final String COOKIE_LABEL_SERVICE_ACCOUNT_PHONE = 'AccountPhone_service';
    private static final String COOKIE_LABEL_SERVICE_PARTS_NO = 'PartsNo_service';
    private static final String COOKIE_LABEL_SERVICE_PARTS_CLASS = 'PartsClass_service';

    // Cookei用定数 共通
    private static final String COOKIE_LABEL_SEARCH_TYPE = 'searchType';
    private static final String COOKIE_LABEL_PAGE_NUMBER = 'PageNumber';  // ページ番号
    private static final String COOKIE_LABEL_PAGE_SIZE = 'PageSize';  // ページサイズ
    private static final String COOKIE_PATH = '/apex/JEOL_JutyuOrderListPage';
    private static final String COOKIE_LABEL_INIT_SEARCH_FLG = 'initSearchFlg';  // 画面起動時検索フラグ

    // 取引先タイプ定数
    private static final String ACCOUNT_TYPE_SALES = 'sales';
    private static final String ACCOUNT_TYPE_DELIVERY = 'delivery';

    // 検索タイプ定数
    private static final String SEARCH_TYPE_SALES = 'sales';
    private static final String SEARCH_TYPE_SERVICE = 'service';

    // 受注検索（販売）
    private static testMethod void test01() {

        // テストデータ生成（販売）
        testDataSales();

        PageReference testPage = Page.JEOL_JutyuOrderListPage;
        Test.setCurrentPage(testPage);

        // クッキー設定（販売）
        createCookiesSales();

        JEOL_JutyuOrderList_ctrl ctrl = new JEOL_JutyuOrderList_ctrl();

		ctrl.searchType = JEOL_JutyuOrderList_ctrl.SEARCH_TYPE_SALES;
        // 検索結果取得とページ制御系メソッド呼び出し
        ctrl.getRecords();
        ctrl.nextAndSaveCurrentPageNumber();
        ctrl.previousAndSaveCurrentPageNumber();
        ctrl.firstAndSaveCurrentPageNumber();
        ctrl.lastAndSaveCurrentPageNumber();
        ctrl.setJumpSaveCurrentPageSize();
        ctrl.setSizeSaveCurrentPageSize();

        // 各値取得用メソッド呼び出し
        ctrl.getACCOUNT_TYPE_SALES();
        ctrl.getACCOUNT_TYPE_DELIVERY();
        ctrl.getPARTS_CLASS_PARTS_ONLY();
        ctrl.getPARTS_CLASS_SWAP_ONLY();
        ctrl.getRegionOptions();

	    // 全パラメータ指定（販売、AccountType_sales = 'sales'）
		ctrl.orderDesc = true;
        ctrl.customerOrderNo_sales = 'testNo';
        ctrl.Seban_sales = 'testSeban';
        ctrl.Area_sales = 'testArea';
        ctrl.UserCode_sales = 'testUcd';
        ctrl.AccountType_sales = ACCOUNT_TYPE_SALES;
        ctrl.AccountCode_sales = 'testACCcd';
        ctrl.AccountName_sales = 'testACCnm';
        ctrl.AccountPhone_sales = '03-1111-1111';
        ctrl.PartsNo_sales = 'testPN';

        // 検索（販売）
        ctrl.Search1();
        ctrl.clearResult();

		ctrl.orderDesc = true;
        ctrl.customerOrderNo_sales = '';
        ctrl.Seban_sales = '';
        ctrl.Area_sales = '';
        ctrl.UserCode_sales = '';
        ctrl.AccountType_sales = ACCOUNT_TYPE_DELIVERY;
        ctrl.AccountCode_sales = 'testAcctCode';
        ctrl.AccountName_sales = 'testAcctName';
        ctrl.AccountPhone_sales = '03-1111-1111';
        ctrl.PartsNo_sales = '';
        ctrl.Search1();
        ctrl.getRecords();

        // クリアメソッド呼び出し
        ctrl.doFormClear();
    }

    // 受注検索（サービス）
    private static testMethod void test02() {

        // テストデータ生成（サービス）
        testDataService();
        PageReference testPage = Page.JEOL_JutyuOrderListPage;
        Test.setCurrentPage(testPage);

        // クッキー設定（サービス）
        createCookiesService();

        JEOL_JutyuOrderList_ctrl ctrl = new JEOL_JutyuOrderList_ctrl();
		ctrl.searchType = JEOL_JutyuOrderList_ctrl.SEARCH_TYPE_SERVICE;
        // StandardSetController呼び出し
		ctrl.orderDesc = true;

        ctrl.setStandardSetController();
        ctrl.getRecords();
        ctrl.customerOrderNo_sales = 'testNo';
        ctrl.Seban_service = 'testSeban';
        ctrl.Area_service = 'testArea';
        ctrl.UserCode_service = 'testUcd';
        ctrl.customerOrderNo_service = 'testOrderNo';
        ctrl.callCenterReceptionNo_service = 'testNo';
        ctrl.unitBody_service = 'testBody';
        ctrl.KishuRyakushou_service = 'testRyaku';
        ctrl.AccountType_service = ACCOUNT_TYPE_DELIVERY;
        ctrl.AccountCode_service = 'testACCcd';
        ctrl.AccountName_service = 'testACCnm';
        ctrl.AccountPhone_service = '03-1111-1111';
        ctrl.PartsNo_service = 'testPN';
        ctrl.PartsClass_service = 'parts_only';
        ctrl.Search2();

        ctrl.AccountType_service = ACCOUNT_TYPE_SALES;
        ctrl.AccountCode_service = 'testACCcd';
        ctrl.AccountName_service = 'testACCnm';
        ctrl.AccountPhone_service = '03-1111-1111';
        ctrl.PartsClass_service = 'swap_only';
        ctrl.Search2();
    }

    // クッキー生成処理（販売）（画面起動時検索フラグON、一部条件指定）
    private static void createCookiesSales(){
        List<Cookie> cookies = new List<Cookie>();

        // 販売タブ
        cookies.add(new Cookie(COOKIE_LABEL_SALES_CO_NO, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_SEBAN, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_AREA, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_USER_CODE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_ACCOUNT_TYPE, ACCOUNT_TYPE_SALES, COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_ACCOUNT_CODE, 'testACCSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_ACCOUNT_NAME, 'testACNSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_ACCOUNT_PHONE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_PARTS_NO, 'testITEMname', COOKIE_PATH, -1, true));

        // 共通
        cookies.add(new Cookie(COOKIE_LABEL_SEARCH_TYPE, SEARCH_TYPE_SALES, COOKIE_PATH, -1, true));  // 検索タイプは販売タブを指定
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_NUMBER, '1', COOKIE_PATH, -1, true));  // ページ番号
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_SIZE, '10', COOKIE_PATH, -1, true));  // ページサイズ
        cookies.add(new Cookie(COOKIE_LABEL_INIT_SEARCH_FLG, 'true', COOKIE_PATH, -1, true));  // 画面起動時検索フラグ
        
        Apexpages.currentPage().setCookies(cookies);
    }

    // クッキー生成処理（サービス）（画面起動時検索フラグON、一部条件指定）
    private static void createCookiesService(){
        List<Cookie> cookies = new List<Cookie>();

        // サービスタブ
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_CO_NO, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_CC_NO, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_UNIT_BODY, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_KSRY, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_SEBAN, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_AREA, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_USER_CODE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_ACCOUNT_TYPE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_ACCOUNT_CODE, 'testACCSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_ACCOUNT_NAME, 'testACNSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_ACCOUNT_PHONE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_PARTS_NO, 'testITEMname', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_PARTS_CLASS, 'testPartsClass', COOKIE_PATH, -1, true));

        // 共通
        cookies.add(new Cookie(COOKIE_LABEL_SEARCH_TYPE, SEARCH_TYPE_SERVICE, COOKIE_PATH, -1, true));  // 検索タイプはサービスタブを指定
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_NUMBER, '1', COOKIE_PATH, -1, true));  // ページ番号
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_SIZE, '10', COOKIE_PATH, -1, true));  // ページサイズ
        cookies.add(new Cookie(COOKIE_LABEL_INIT_SEARCH_FLG, 'true', COOKIE_PATH, -1, true));  // 画面起動時検索フラグ
        
        Apexpages.currentPage().setCookies(cookies);
    }

    // テストデータ作成（販売）
    private static void testDataSales(){
        // 品目
        ProductItem__c pi = new ProductItem__c();
        pi.Name = 'testITEMname';
        pi.Series__c = 'testPI';
        pi.JapaneseName__c = 'testModelNamePI';
        insert pi;

        // シリアル番号付品目
        UnitBody__c ub = new UnitBody__c();
        ub.Name = 'testSNPIname';
        ub.ItemLink__c = pi.Id;
        ub.SerialNo__c = 'testSNo';
        ub.UnitBody__c = 'testUnitBody';
        ub.StatusOfUse__c = '1';
        insert ub;

        // 販売先取引先
        Account accSL = new Account();
        accSL.Name = 'testACNSL';
        accSL.Code__c = 'testACCSL';
        insert accSL;

        // 出荷先取引先
        Account accSP = new Account();
        accSP.Name = 'testACNSP';
        accSP.Code__c = 'testACCSP';
        insert accSP;

        // 販売オーダ
        SalesOrder__c so = new SalesOrder__c();
        so.Name = 'testSOname';
        so.SalesAccount__c = accSL.Id;
        so.ShipmentAccount__c = accSP.Id;
//        so.UnitBodyLink__c = ub.Id;               //20150905 commentout because prod not have this field
        //パーツサプライを指定
        so.SalesOrderTypeCode__c = '5A7';
        insert so;

        // 販売オーダライン
        SalesOrderLine__c sol = new SalesOrderLine__c();
        sol.Name = 'testSOLname';
        sol.SalesOrderLink__c = so.Id;
        sol.ProductItem__c = pi.Id;
        insert sol;
    }

    // テストデータ作成（サービス）
    private static void testDataService(){
        // 品目
        ProductItem__c pi = new ProductItem__c();
        pi.Name = 'testITEMname';
        pi.Series__c = 'testPI';
        pi.JapaneseName__c = 'testModelNamePI';
        insert pi;

        // シリアル番号付品目
        UnitBody__c ub = new UnitBody__c();
        ub.Name = 'testSNPIname';
        ub.ItemLink__c = pi.Id;
        ub.SerialNo__c = 'testSNo';
        ub.UnitBody__c = 'testUnitBody';
        ub.StatusOfUse__c = '1';
        insert ub;

        // 顧客対応票
        Support__c spt = new Support__c();
        spt.Name = 'testSPTname';
//        spt.UnitBodyLink__c = ub.Id;      //20150905 commentout because prod not have this field
        insert spt;

        // 販売先取引先
        Account accSL = new Account();
        accSL.Name = 'testACNSL';
        accSL.Code__c = 'testACCSL';
        insert accSL;

        // 出荷先取引先
        Account accSP = new Account();
        accSP.Name = 'testACNSP';
        accSP.Code__c = 'testACCSP';
        insert accSP;

        // サービスオーダ
        ServiceOrder__c so = new ServiceOrder__c();
        so.Name = 'testSOname';
        so.SalesAccount__c = accSL.Id;
        so.ShipmentAccount__c = accSP.Id;
        so.Customer__c = spt.Id;
        insert so;

        // サービスオーダ材料費
        ServiceOrderControl__c soc = new ServiceOrderControl__c();
        soc.Name = 'testSOLname';
        soc.ServiceOrder__c = so.Id;
        soc.ProductItem__c = pi.Id;
        insert soc;
    }

}
*/


/****************************/
@IsTest
private class JEOL_JutyuOrderList_ctrlTest {

    // Cookei用定数 販売タブ
    private static final String COOKIE_LABEL_SALES_CO_NO = 'customerOrderNo_sales';
    private static final String COOKIE_LABEL_SALES_SEBAN = 'Seban_sales';
    private static final String COOKIE_LABEL_SALES_AREA = 'Area_sales';
    private static final String COOKIE_LABEL_SALES_USER_CODE = 'UserCode_sales';
    private static final String COOKIE_LABEL_SALES_ACCOUNT_TYPE = 'AccountType_sales';
    private static final String COOKIE_LABEL_SALES_ACCOUNT_CODE = 'AccountCode_sales';
    private static final String COOKIE_LABEL_SALES_ACCOUNT_NAME = 'AccountName_sales';
    private static final String COOKIE_LABEL_SALES_ACCOUNT_PHONE = 'AccountPhone_sales';
    private static final String COOKIE_LABEL_SALES_PARTS_NO = 'PartsNo_sales';

    // Cookei用定数 サービスタブ
    private static final String COOKIE_LABEL_SERVICE_CO_NO = 'customerOrderNo_service';
    private static final String COOKIE_LABEL_SERVICE_CC_NO = 'callCenterReceptionNo_service';
    private static final String COOKIE_LABEL_SERVICE_UNIT_BODY = 'unitBody_service';
    private static final String COOKIE_LABEL_SERVICE_KSRY = 'KishuRyakushou_service';
    private static final String COOKIE_LABEL_SERVICE_SEBAN = 'Seban_service';
    private static final String COOKIE_LABEL_SERVICE_AREA = 'Area_service';
    private static final String COOKIE_LABEL_SERVICE_USER_CODE = 'UserCode_service';
    private static final String COOKIE_LABEL_SERVICE_ACCOUNT_TYPE = 'AccountType_service';
    private static final String COOKIE_LABEL_SERVICE_ACCOUNT_CODE = 'AccountCode_service';
    private static final String COOKIE_LABEL_SERVICE_ACCOUNT_NAME = 'AccountName_service';
    private static final String COOKIE_LABEL_SERVICE_ACCOUNT_PHONE = 'AccountPhone_service';
    private static final String COOKIE_LABEL_SERVICE_PARTS_NO = 'PartsNo_service';
    private static final String COOKIE_LABEL_SERVICE_PARTS_CLASS = 'PartsClass_service';

    // Cookei用定数 共通
    private static final String COOKIE_LABEL_SEARCH_TYPE = 'searchType';
    private static final String COOKIE_LABEL_PAGE_NUMBER = 'PageNumber';  // ページ番号
    private static final String COOKIE_LABEL_PAGE_SIZE = 'PageSize';  // ページサイズ
    private static final String COOKIE_PATH = '/apex/JEOL_JutyuOrderListPage';
    private static final String COOKIE_LABEL_INIT_SEARCH_FLG = 'initSearchFlg';  // 画面起動時検索フラグ

    // 取引先タイプ定数
    private static final String ACCOUNT_TYPE_SALES = 'sales';
    private static final String ACCOUNT_TYPE_DELIVERY = 'delivery';

    // 検索タイプ定数
    private static final String SEARCH_TYPE_SALES = 'sales';
    private static final String SEARCH_TYPE_SERVICE = 'service';

    // 受注検索（販売）
    private static testMethod void test01() {

        // テストデータ生成（販売）
        testDataSales();

        PageReference testPage = Page.JEOL_JutyuOrderListPage;
        Test.setCurrentPage(testPage);

        // クッキー設定（販売）
        createCookiesSales();

        JEOL_JutyuOrderList_ctrl ctrl = new JEOL_JutyuOrderList_ctrl();

        // 検索結果取得とページ制御系メソッド呼び出し
        ctrl.getRecords();
        ctrl.nextAndSaveCurrentPageNumber();
        ctrl.previousAndSaveCurrentPageNumber();
        ctrl.firstAndSaveCurrentPageNumber();
        ctrl.lastAndSaveCurrentPageNumber();
        ctrl.setJumpSaveCurrentPageSize();
        ctrl.setSizeSaveCurrentPageSize();

        // 各値取得用メソッド呼び出し
        ctrl.getACCOUNT_TYPE_SALES();
        ctrl.getACCOUNT_TYPE_DELIVERY();
        ctrl.getPARTS_CLASS_PARTS_ONLY();
        ctrl.getPARTS_CLASS_SWAP_ONLY();
        ctrl.getRegionOptions();

        // 全パラメータ指定（販売、AccountType_sales = 'sales'）
        ctrl.orderDesc = true;
        ctrl.customerOrderNo_sales = 'testNo';
        ctrl.Seban_sales = 'testSeban';
        ctrl.Area_sales = 'testArea';
        ctrl.UserCode_sales = 'testUcd';
        ctrl.AccountType_sales = ACCOUNT_TYPE_SALES;
        ctrl.AccountCode_sales = 'testACCcd';
        ctrl.AccountName_sales = 'testACCnm';
        ctrl.AccountPhone_sales = '03-1111-1111';
        ctrl.PartsNo_sales = 'testPN';

        // 検索（販売）
        ctrl.Search1();
        ctrl.clearResult();

        ctrl.orderDesc = true;
        ctrl.customerOrderNo_sales = '';
        ctrl.Seban_sales = '';
        ctrl.Area_sales = '';
        ctrl.UserCode_sales = '';
        ctrl.AccountType_sales = ACCOUNT_TYPE_DELIVERY;
        ctrl.AccountCode_sales = 'testAcctCode';
        ctrl.AccountName_sales = 'testAcctName';
        ctrl.AccountPhone_sales = '03-1111-1111';
        ctrl.PartsNo_sales = '';
        ctrl.Search1();
        ctrl.getRecords();

        // クリアメソッド呼び出し
        ctrl.doFormClear();
    }

    // 受注検索（サービス）
    private static testMethod void test02() {

        // テストデータ生成（サービス）
        testDataService();
        PageReference testPage = Page.JEOL_JutyuOrderListPage;
        Test.setCurrentPage(testPage);

        // クッキー設定（サービス）
        createCookiesService();

        JEOL_JutyuOrderList_ctrl ctrl = new JEOL_JutyuOrderList_ctrl();

        // StandardSetController呼び出し
        ctrl.setStandardSetController();

        ctrl.orderDesc = true;
        ctrl.customerOrderNo_sales = 'testNo';
        ctrl.Seban_service = 'testSeban';
        ctrl.Area_service = 'testArea';
        ctrl.UserCode_service = 'testUcd';
        ctrl.customerOrderNo_service = 'testOrderNo';
        ctrl.callCenterReceptionNo_service = 'testNo';
        ctrl.unitBody_service = 'testBody';
        ctrl.KishuRyakushou_service = 'testRyaku';
        ctrl.AccountType_service = ACCOUNT_TYPE_DELIVERY;
        ctrl.AccountCode_service = 'testACCcd';
        ctrl.AccountName_service = 'testACCnm';
        ctrl.AccountPhone_service = '03-1111-1111';
        ctrl.PartsNo_service = 'testPN';
        ctrl.PartsClass_service = 'parts_only';
        ctrl.Search2();

        ctrl.AccountType_service = ACCOUNT_TYPE_SALES;
        ctrl.AccountCode_service = 'testACCcd';
        ctrl.AccountName_service = 'testACCnm';
        ctrl.AccountPhone_service = '03-1111-1111';
        ctrl.PartsClass_service = 'swap_only';
        ctrl.Search2();
    }

    // クッキー生成処理（販売）（画面起動時検索フラグON、一部条件指定）
    private static void createCookiesSales(){
        List<Cookie> cookies = new List<Cookie>();

        // 販売タブ
        cookies.add(new Cookie(COOKIE_LABEL_SALES_CO_NO, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_SEBAN, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_AREA, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_USER_CODE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_ACCOUNT_TYPE, ACCOUNT_TYPE_SALES, COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_ACCOUNT_CODE, 'testACCSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_ACCOUNT_NAME, 'testACNSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_ACCOUNT_PHONE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_PARTS_NO, 'testITEMname', COOKIE_PATH, -1, true));

        // 共通
        cookies.add(new Cookie(COOKIE_LABEL_SEARCH_TYPE, SEARCH_TYPE_SALES, COOKIE_PATH, -1, true));  // 検索タイプは販売タブを指定
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_NUMBER, '1', COOKIE_PATH, -1, true));  // ページ番号
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_SIZE, '10', COOKIE_PATH, -1, true));  // ページサイズ
        cookies.add(new Cookie(COOKIE_LABEL_INIT_SEARCH_FLG, 'true', COOKIE_PATH, -1, true));  // 画面起動時検索フラグ
        
        Apexpages.currentPage().setCookies(cookies);
    }

    // クッキー生成処理（サービス）（画面起動時検索フラグON、一部条件指定）
    private static void createCookiesService(){
        List<Cookie> cookies = new List<Cookie>();

        // サービスタブ
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_CO_NO, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_CC_NO, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_UNIT_BODY, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_KSRY, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_SEBAN, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_AREA, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_USER_CODE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_ACCOUNT_TYPE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_ACCOUNT_CODE, 'testACCSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_ACCOUNT_NAME, 'testACNSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_ACCOUNT_PHONE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_PARTS_NO, 'testITEMname', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SERVICE_PARTS_CLASS, 'testPartsClass', COOKIE_PATH, -1, true));

        // 共通
        cookies.add(new Cookie(COOKIE_LABEL_SEARCH_TYPE, SEARCH_TYPE_SERVICE, COOKIE_PATH, -1, true));  // 検索タイプはサービスタブを指定
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_NUMBER, '1', COOKIE_PATH, -1, true));  // ページ番号
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_SIZE, '10', COOKIE_PATH, -1, true));  // ページサイズ
        cookies.add(new Cookie(COOKIE_LABEL_INIT_SEARCH_FLG, 'true', COOKIE_PATH, -1, true));  // 画面起動時検索フラグ
        
        Apexpages.currentPage().setCookies(cookies);
    }

    // テストデータ作成（販売）
    private static void testDataSales(){
        // 品目
        ProductItem__c pi = new ProductItem__c();
        pi.Name = 'testITEMname';
        pi.Series__c = 'testPI';
        pi.JapaneseName__c = 'testModelNamePI';
        insert pi;

        // シリアル番号付品目
        SerialNoProductItem__c snpi = new SerialNoProductItem__c();
        snpi.Name = 'testSNPIname';
        snpi.ItemLink__c = pi.Id;
        snpi.SerialNo__c = 'testSNo';
        snpi.UnitBody__c = 'testUnitBody';
        snpi.StatusOfUse__c = '1';
        snpi.SalesTargetCustomer__c = 'testCode';
        insert snpi;

        // 販売先取引先
        Account accSL = new Account();
        accSL.Name = 'testACNSL';
        accSL.Code__c = 'testACCSL';
        insert accSL;

        // 出荷先取引先
        Account accSP = new Account();
        accSP.Name = 'testACNSP';
        accSP.Code__c = 'testACCSP';
        insert accSP;

        // 販売オーダ
        SalesOrder__c so = new SalesOrder__c();
        so.Name = 'testSOname';
        so.SalesAccount__c = accSL.Id;
        so.ShipmentAccount__c = accSP.Id;
        so.SerialNoItemLink__c = snpi.Id;
        //パーツサプライを指定
        so.SalesOrderTypeCode__c = '5A7';
        insert so;

        // 販売オーダライン
        SalesOrderLine__c sol = new SalesOrderLine__c();
        sol.Name = 'testSOLname';
        sol.SalesOrderLink__c = so.Id;
        sol.ProductItem__c = pi.Id;
        insert sol;
    }

    // テストデータ作成（サービス）
    private static void testDataService(){
        // 品目
        ProductItem__c pi = new ProductItem__c();
        pi.Name = 'testITEMname';
        pi.Series__c = 'testPI';
        pi.JapaneseName__c = 'testModelNamePI';
        insert pi;

        // シリアル番号付品目
        SerialNoProductItem__c snpi = new SerialNoProductItem__c();
        snpi.Name = 'testSNPIname';
        snpi.ItemLink__c = pi.Id;
        snpi.SerialNo__c = 'testSNo';
        snpi.UnitBody__c = 'testUnitBody';
        snpi.StatusOfUse__c = '1';
        snpi.SalesTargetCustomer__c = 'testCode';
        insert snpi;

        // 顧客対応票
        Support__c spt = new Support__c();
        spt.Name = 'testSPTname';
        spt.SerialNoItemsLink__c = snpi.Id;
        insert spt;

        // 販売先取引先
        Account accSL = new Account();
        accSL.Name = 'testACNSL';
        accSL.Code__c = 'testACCSL';
        insert accSL;

        // 出荷先取引先
        Account accSP = new Account();
        accSP.Name = 'testACNSP';
        accSP.Code__c = 'testACCSP';
        insert accSP;

        // サービスオーダ
        ServiceOrder__c so = new ServiceOrder__c();
        so.Name = 'testSOname';
        so.SalesAccount__c = accSL.Id;
        so.ShipmentAccount__c = accSP.Id;
        so.Customer__c = spt.Id;
        insert so;

        // サービスオーダ材料費
        ServiceOrderControl__c soc = new ServiceOrderControl__c();
        soc.Name = 'testSOLname';
        soc.ServiceOrder__c = so.Id;
        soc.ProductItem__c = pi.Id;
        insert soc;
    }

}