objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CustomerCode__c</fullName>
        <label>お客様取引先コード</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <label>お客様取引先名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Model__c.object
<CustomObject>
    <description>デモレポート用機種マスタ</description>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>機種</label>
    <nameField>
        <label>形式</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductItem__c.object
<CustomObject>
    <fields>
        <fullName>EnglishName__c</fullName>
        <label>品目名（英名）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JapaneseName__c</fullName>
        <label>品目名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>機種</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SerialNoProductItem__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDate__c</fullName>
        <label>検収日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EfProductNoEndDate__c</fullName>
        <label>EF終了日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EfProductNo__c</fullName>
        <label>EF製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目リンク</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>シリアル番号付品目</relationshipLabel>
        <relationshipName>ItemRelation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ModelsAbbreviation__c</fullName>
        <label>機種略称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentItem__c</fullName>
        <label>親品目</label>
        <length>47</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentNumber__c</fullName>
        <label>親シリアル番号</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesTargetCustomer__c</fullName>
        <label>販売先取引先コード</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <externalId>true</externalId>
        <label>シリアル番号_連携用</label>
        <length>78</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ShipDate__c</fullName>
        <label>出荷日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SpecialNote__c</fullName>
        <label>特別契約メモ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SvcForm__c</fullName>
        <label>SVC形態</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>シリアル番号付品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDate__c</fullName>
        <formula>UnitBodyLink__r.AcceptanceDateFormula__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体検収日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContactMatter__c</fullName>
        <label>サポート員への連絡事項</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CustomerAffiliation__c</fullName>
        <label>御所属</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerCode__c</fullName>
        <label>顧客コード</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerFacultyOffice__c</fullName>
        <label>学部事業所</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <label>顧客名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EfProductNoEndDate__c</fullName>
        <formula>UnitBodyLink__r.EFEndDateFormula__c</formula>
        <label>EF終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FailureCause1__c</fullName>
        <label>原因１</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FailureCause2__c</fullName>
        <label>原因２</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FailureCause3__c</fullName>
        <label>原因３</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstSupportPerson__c</fullName>
        <label>一次対応者</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductNo__c</fullName>
        <label>製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelevanceCcReceiptNo__c</fullName>
        <label>関連コールセンタ受付番号</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestContent1__c</fullName>
        <label>依頼内容１</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestContent2__c</fullName>
        <label>依頼内容２</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestContent3__c</fullName>
        <label>依頼内容３</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_EndDate__c</fullName>
        <label>検索終点日付</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Search_StartDate__c</fullName>
        <label>検索始点日付</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SerialNoItemsLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>シリアル番号付品目</label>
        <referenceTo>SerialNoProductItem__c</referenceTo>
        <relationshipLabel>顧客対応票</relationshipLabel>
        <relationshipName>SerialNoItems2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceEndDate__c</fullName>
        <label>顧客対応終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ServiceStartDate__c</fullName>
        <label>顧客対応開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ServiceTypeCode__c</fullName>
        <label>サービス種別コード</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipDate__c</fullName>
        <formula>UnitBodyLink__r.ShippingDateFormula__c</formula>
        <label>本体納入日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SpecialNote__c</fullName>
        <formula>UnitBodyLink__r.SpecialContractNote__c</formula>
        <label>特別契約メモ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>コール応答中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>コール保留</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>対応依頼</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応終了</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応にて完了</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>二次対応中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>二次対応完了</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TypeOfService__c</fullName>
        <label>サービス種別</label>
        <picklist>
            <picklistValues>
                <fullName>1：パーコール</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2：保守点検</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3：オーバホール</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4：改造（WS）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5：移転</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6：納入</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7：その他</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8：出荷済工事</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A:パーコール-D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B:保守D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C:Ｏ・Ｈ-Ｄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D:移転Ｄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E:ＷＳ-Ｄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F:納入D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G:ＥＦ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H:設置室</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I:設置室D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J:周辺機器</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K:周辺機器Ｄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L:対策工事</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M:講習</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N:受託分析</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O:営業支援</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P:対策ME①</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q:対策ME②</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R:対策ME③</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>顧客対応票</label>
    <nameField>
        <label>コールセンター受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDate__c</fullName>
        <label>検収日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EFProductNo__c</fullName>
        <label>EF製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>ItemLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>ItemLink__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>機種</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <label>シリアル番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <formula>ItemLink__r.Series__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>系列</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SvcForm__c</fullName>
        <label>SVC形態</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_ServiceShori_ctrlTest.cls
@isTest
private class JEOL_ServiceShori_ctrlTest {

    // 正常終了、各メソッド呼び出し
    static testMethod void Test01() {
        //テストデータ作成
        testData();

        // ページを設定
        PageReference testPage = Page.JEOL_ServiceShoriPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        ApexPages.currentPage().getParameters().put('mainPartNo', 'g01');

        JEOL_ServiceShori_ctrl ctrl = new JEOL_ServiceShori_ctrl();

        // 各メソッド呼び出し
        ctrl.prev();
        ctrl.getCustomerSupportServiceSyoriList();
        ctrl.nextAndSaveCurrentPageNumber();
        ctrl.previousAndSaveCurrentPageNumber();
        ctrl.firstAndSaveCurrentPageNumber();
        ctrl.lastAndSaveCurrentPageNumber();
        ctrl.setJumpSaveCurrentPageSize();
        ctrl.setSizeSaveCurrentPageSize();
    }

    // 異常終了（本体号機設定なし）
    static testMethod void Test02() {
        // ページを設定
        PageReference testPage = Page.JEOL_ServiceShoriPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        ApexPages.currentPage().getParameters().put('mainPartNo', '');

        JEOL_ServiceShori_ctrl ctrl = new JEOL_ServiceShori_ctrl();
    }

    // 異常終了（取得件数0件）
    static testMethod void Test03() {
        // テストデータ作成
        testData();

        // ページを設定
        PageReference testPage = Page.JEOL_ServiceShoriPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        ApexPages.currentPage().getParameters().put('mainPartNo', '1234567890123456');

        JEOL_ServiceShori_ctrl ctrl = new JEOL_ServiceShori_ctrl();
    }

    // テストデータ作成
    private static void testData(){
        //品目
        ProductItem__c pItem = new ProductItem__c();
        pItem.Name = 'Test';
        pItem.Model__c = 'T001';
        pItem.Series__c = 'TS';
        pItem.JapaneseName__c = 'テスト';
        pItem.EnglishName__c = 'test';
        insert pItem;

        //シリアル番号付品目
        date myDate = date.today();
        datetime myDateTime = datetime.now();
        SerialNoProductItem__c spItem = new SerialNoProductItem__c();
        spItem.Name = 'Test';
        spItem.EfProductNo__c = 'No001';
        spItem.EfProductNoEndDate__c = myDateTime;
        spItem.SvcForm__c = 's01';
        spItem.SerialNo__c = 'tsts00001';
        spItem.ModelsAbbreviation__c = 'c3';
        spItem.AcceptanceDate__c = myDateTime;
        spItem.StatusOfUse__c = 'use';
        spItem.ShipDate__c = myDateTime;
        spItem.ParentNumber__c = 'p01';
        spItem.ParentItem__c = 'pItem';
        spItem.SpecialNote__c = 'memo';
        spItem.SalesTargetCustomer__c = 'sc01';
        spItem.ItemLink__c = pItem.Id;
        spItem.UnitBody__c = 'h01';
        insert spItem;

        //取引先
        Account acc = new Account();
        acc.Name = '取テスト１';
        acc.Code__c = 'tsttt01';
        insert acc;

        //顧客対応票
        Support__c spp = new Support__c();
        spp.Name = 'u001';
        spp.TypeOfService__c = '1：パーコール';
        spp.ServiceTypeCode__c = 'Z1';
        spp.ContactMatter__c = '至急でお願いします';
        spp.SerialNoItemsLink__c = spItem.Id;
        spp.Status__c = 'コール応答中';
        spp.RequestContent1__c = '依頼１';
        spp.RequestContent2__c = '依頼２';
        spp.RequestContent3__c = '依頼３';
        spp.FirstSupportPerson__c = '荒木';
        spp.CustomerFacultyOffice__c = '○支店';
        spp.RelevanceCcReceiptNo__c = 'ku001';
        spp.Search_StartDate__c = myDate;
        spp.Search_EndDate__c = myDate;
        spp.FailureCause1__c = '原因１';
        spp.FailureCause2__c = '原因２';
        spp.FailureCause3__c = '原因３';
        spp.CustomerCode__c = 'k001';
        spp.ServiceStartDate__c = myDate;
        spp.ServiceEndDate__c = myDate;
        spp.CustomerName__c = '花子';
        spp.CustomerAffiliation__c = '○株式会社';
        spp.CustomerContactPerson__c = '太郎';
        spp.SalesCustomer__c = acc.Id;
        spp.UketsukeSupportPerson__c = '荒木';
        spp.ServiceDate2__c = '受付開始日';
        spp.ReceptionDatetime__c = myDate;
        spp.ClassificationDeal1__c = '処置１';
        spp.ClassificationDeal2__c = '処置２';
        spp.ClassificationDeal3__c = '処置３';
        spp.FaultLocation1__c = '障害１';
        spp.FaultLocation2__c = '障害２';
        spp.FaultLocation3__c = '障害３';
        spp.ProductNo__c = 'sei001';
        spp.Responce__c = '対応';
        spp.ServiceDate__c = '対応開始日';
        spp.ServicePerson__c = '荒木';
        spp.CustomerPhone__c = '0120100123';
        spp.CustomerExtension__c = 'memo';
        spp.SecondSupportPerson__c = '新井';
        spp.SalesOrderNo__c = 'so001';
        spp.MaintenanceSerialNo__c = 'M00001';
        spp.UnitBody__c = 'g01';
        insert spp;
    }

}