objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ServiceAreaBranch__c</fullName>
        <label>サービスエリア支店</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <label>サービスエリア名</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>取引先カテゴリコード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>取引先カテゴリ</label>
    <nameField>
        <label>取引先カテゴリ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CategoryJunction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>取引先カテゴリジャンクション</relationshipLabel>
        <relationshipName>AccJunctionLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CategoryName__c</fullName>
        <description>API参照名に注意</description>
        <label>取引先カテゴリコード</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>取引先カテゴリジャンクション</relationshipLabel>
        <relationshipName>JunctionLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>取引先カテゴリジャンクション</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>取引先カテゴリジャンクション</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Model__c.object
<CustomObject>
    <description>デモレポート用機種マスタ</description>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>機種</label>
    <nameField>
        <label>形式</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductItem__c.object
<CustomObject>
    <fields>
        <fullName>EnglishName__c</fullName>
        <label>品目名（英名）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JapaneseName__c</fullName>
        <label>品目名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>機種</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SerialNoProductItem__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDate__c</fullName>
        <label>検収日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EfProductNoEndDate__c</fullName>
        <label>EF終了日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EfProductNo__c</fullName>
        <label>EF製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目リンク</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>シリアル番号付品目</relationshipLabel>
        <relationshipName>ItemRelation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ModelsAbbreviation__c</fullName>
        <label>機種略称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentItem__c</fullName>
        <label>親品目</label>
        <length>47</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentNumber__c</fullName>
        <label>親シリアル番号</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesTargetCustomer__c</fullName>
        <label>販売先取引先コード</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <externalId>true</externalId>
        <label>シリアル番号_連携用</label>
        <length>78</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ShipDate__c</fullName>
        <label>出荷日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SpecialNote__c</fullName>
        <label>特別契約メモ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SvcForm__c</fullName>
        <label>SVC形態</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>シリアル番号付品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDate__c</fullName>
        <formula>UnitBodyLink__r.AcceptanceDateFormula__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体検収日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContactMatter__c</fullName>
        <label>サポート員への連絡事項</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EfProductNoEndDate__c</fullName>
        <formula>UnitBodyLink__r.EFEndDateFormula__c</formula>
        <label>EF終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductNo__c</fullName>
        <label>製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestContent1__c</fullName>
        <label>依頼内容１</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestContent2__c</fullName>
        <label>依頼内容２</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestContent3__c</fullName>
        <label>依頼内容３</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNoItemsLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>シリアル番号付品目</label>
        <referenceTo>SerialNoProductItem__c</referenceTo>
        <relationshipLabel>顧客対応票</relationshipLabel>
        <relationshipName>SerialNoItems2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceTypeCode__c</fullName>
        <label>サービス種別コード</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipDate__c</fullName>
        <formula>UnitBodyLink__r.ShippingDateFormula__c</formula>
        <label>本体納入日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SpecialNote__c</fullName>
        <formula>UnitBodyLink__r.SpecialContractNote__c</formula>
        <label>特別契約メモ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>コール応答中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>コール保留</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>対応依頼</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応終了</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応にて完了</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>二次対応中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>二次対応完了</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TypeOfService__c</fullName>
        <label>サービス種別</label>
        <picklist>
            <picklistValues>
                <fullName>1：パーコール</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2：保守点検</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3：オーバホール</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4：改造（WS）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5：移転</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6：納入</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7：その他</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8：出荷済工事</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A:パーコール-D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B:保守D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C:Ｏ・Ｈ-Ｄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D:移転Ｄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E:ＷＳ-Ｄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F:納入D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G:ＥＦ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H:設置室</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I:設置室D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J:周辺機器</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K:周辺機器Ｄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L:対策工事</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M:講習</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N:受託分析</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O:営業支援</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P:対策ME①</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q:対策ME②</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R:対策ME③</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>顧客対応票</label>
    <nameField>
        <label>コールセンター受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDate__c</fullName>
        <label>検収日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EFProductNo__c</fullName>
        <label>EF製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>ItemLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>ItemLink__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>機種</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <label>シリアル番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <formula>ItemLink__r.Series__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>系列</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SvcForm__c</fullName>
        <label>SVC形態</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_ServiceUketsuke_ctrlTest.cls
@IsTest
private class JEOL_ServiceUketsuke_ctrlTest {
    // 定数
    private static final String SEARCH_TYPE_SALES = 'sales';
    private static final String SEARCH_TYPE_SUPPORT = 'support';

    // Cookie用定数（営業）
    private static final String COOKIE_LABEL_SALES_CUSTOMER_CODE = 'customerCode_sales';
    private static final String COOKIE_LABEL_SALES_CUSTOMER_NAME = 'customerName_sales';
    private static final String COOKIE_LABEL_SALES_CUSTOMER_CATEGORY = 'customerCategory_sales';
    private static final String COOKIE_LABEL_SALES_MODEL_NAME = 'modelName_sales';
    private static final String COOKIE_LABEL_SALES_MAIN_PART_NO_MACHINE = 'mainPartNoMachine_sales';
    private static final String COOKIE_LABEL_SALES_NAME = 'name_sales';
    private static final String COOKIE_LABEL_SALES_PRODUCT_NO = 'productNo_sales';
    private static final String COOKIE_LABEL_SALES_CENTER = 'center_sales';
    private static final String COOKIE_LABEL_SALES_UKETSUKE_SUPPORT_PERSON = 'uketsukeSupportPerson_sales';
    private static final String COOKIE_LABEL_SALES_SERVICE_DATE_STATUS = 'serviceDateStatus_sales';
    private static final String COOKIE_LABEL_SALES_TAIOU_START_DATE = 'taiouStartDate_sales';
    private static final String COOKIE_LABEL_SALES_TAIOU_END_DATE = 'taiouEndDate_sales';
    // Cookie用定数（サポート）
    private static final String COOKIE_LABEL_SUPPORT_CUSTOMER_CODE = 'customerCode_support';
    private static final String COOKIE_LABEL_SUPPORT_CUSTOMER_NAME = 'customerName_support';
    private static final String COOKIE_LABEL_SUPPORT_CENTER = 'center_support';
    private static final String COOKIE_LABEL_SUPPORT_SERIES = 'series_support';
    private static final String COOKIE_LABEL_SUPPORT_MAIN_PART_NO_MACHINE = 'mainPartNoMachine_support';
    private static final String COOKIE_LABEL_SUPPORT_UKETSUKE_SUPPORT_PERSON = 'uketsukeSupportPerson_support';
    private static final String COOKIE_LABEL_SUPPORT_SERVICE_TYPE = 'serviceType_support';
    private static final String COOKIE_LABEL_SUPPORT_NAME = 'name_support';
    private static final String COOKIE_LABEL_SUPPORT_PRODUCT_NO = 'productNo_support';
    private static final String COOKIE_LABEL_SUPPORT_KEYWORD = 'keyword_support';
    private static final String COOKIE_LABEL_SUPPORT_STATUS = 'status_support';
    private static final String COOKIE_LABEL_SUPPORT_UKETSUKE_START_DATE = 'uketsukeStartDate_support';
    private static final String COOKIE_LABEL_SUPPORT_UKETSUKE_END_DATE = 'uketsukeEndDate_support';
    private static final String COOKIE_LABEL_SUPPORT_SERVICE_DATE_STATUS = 'serviceDateStatus_support';
    private static final String COOKIE_LABEL_SUPPORT_TAIOU_START_DATE = 'taiouStartDate_support';
    private static final String COOKIE_LABEL_SUPPORT_TAIOU_END_DATE = 'taiouEndDate_support';
    // Cookie用定数（共通）
    private static final String COOKIE_PATH = '/apex/JEOL_ServiceUketsukePage';
    private static final String COOKIE_LABEL_SEARCH_TYPE = 'searchType';
    private static final String COOKIE_LABEL_PAGE_NUMBER = 'PageNumber';  // ページ番号
    private static final String COOKIE_LABEL_PAGE_SIZE = 'PageSize';  // ページサイズ
    private static final String COOKIE_LABEL_INIT_SEARCH_FLG = 'initSearchFlg';  // 画面起動時検索フラグ
// -------------------------------------------------------------------------------------------------------------------

    // コンストラクタ、各メソッド呼び出し、検索結果取得（クッキー系処理含む、取引先カテゴリ該当あり）
    private static testMethod void test00() {

        // テストデータ作成、本日日付取得
        date myDate = testData();

        PageReference testPage = Page.JEOL_ServiceUketsukePage;
        Test.setCurrentPage(testPage);

        // クッキー設定
        createCookies();

        JEOL_ServiceUketsuke_ctrl ctrl = new JEOL_ServiceUketsuke_ctrl();

        // 検索結果取得（営業）とページ制御系メソッド呼び出し
        ctrl.getSupport();
        ctrl.nextAndSaveCurrentPageNumber();
        ctrl.previousAndSaveCurrentPageNumber();
        ctrl.firstAndSaveCurrentPageNumber();
        ctrl.lastAndSaveCurrentPageNumber();
        ctrl.setJumpSaveCurrentPageSize();
        ctrl.setSizeSaveCurrentPageSize();

        // 各メソッド呼び出し
        ctrl.getCCategoryOptions();
        ctrl.getSeriesPIOptions();
        ctrl.getAreaOptions();
        ctrl.getServiceDateStatusList();
        ctrl.getServiceTypeList();
        ctrl.getStatusList();

        ctrl.customerCode_sales = '';
        ctrl.customerName_sales = '';
        ctrl.customerCategory_sales = '';
        ctrl.modelName_sales = '';
        ctrl.mainPartNoMachine_sales = '';
        ctrl.name_sales = '';
        ctrl.productNo_sales = '';
        ctrl.center_sales = '';
        ctrl.uketsukeSupportPerson_sales = '';
        ctrl.serviceDateStatus_sales = '';
        ctrl.taiouStartDate_sales = '';
        ctrl.taiouEndDate_sales = '';
        ctrl.search1();
        List<JEOL_ServiceUketsuke_ctrl.rowWrapper> wrapper = ctrl.getSupport(); 
        wrapper.get(0).getUrl();

        
        // クリアメソッド呼び出し
        ctrl.doFormClear();
    }

    private static testMethod void test01() {
        // テストデータ作成、本日日付取得
        date myDate = testData();

        Test.starttest();
        JEOL_ServiceUketsuke_ctrl ctrl = new JEOL_ServiceUketsuke_ctrl();
        
        ctrl.orderDesc = true;
        ctrl.serviceDateStatus_sales = '対応開始日';
        ctrl.taiouStartDate_sales = '3999/12/31';
        ctrl.customerCategory_sales = 'testCCcodetest';
        ctrl.search1();

        ctrl.customerName_sales = 'testCName';
        ctrl.serviceDateStatus_sales = '対応開始日';
        ctrl.taiouEndDate_sales = '1900/01/01';
        ctrl.search1();

        ctrl.serviceDateStatus_sales = '対応終了日';
        ctrl.taiouStartDate_sales = '3999/12/31';
        ctrl.taiouEndDate_sales = '1900/01/01';
        ctrl.search1();

        ctrl.serviceDateStatus_sales = '対応開始日';
        ctrl.taiouStartDate_sales = '';
        ctrl.taiouEndDate_sales = '';
        ctrl.search1();


        ctrl.serviceDateStatus_sales = '対応開始日';
        ctrl.taiouStartDate_sales = 'exeptionTest';
        ctrl.search1();

        ctrl.customerCode_sales = 'testCCode';
        ctrl.customerName_sales = 'testCName';
        ctrl.customerCategory_sales = 'testCCCode';
        ctrl.modelName_sales = 'testModelName';
        ctrl.mainPartNoMachine_sales = 'testPNM';
        ctrl.name_sales = 'testName';
        ctrl.productNo_sales = 'testPN';
        ctrl.center_sales = 'testCenter';
        ctrl.uketsukeSupportPerson_sales = 'testUSP';
        ctrl.serviceDateStatus_sales = '対応開始日';
        ctrl.taiouStartDate_sales = 'testTSD';
        ctrl.taiouEndDate_sales = 'testTED';

        ctrl.search1();
        Test.stoptest();
    }

// -------------------------------------------------------------------------------------------------------------------

    //search2テスト(対応開始日startDate、受付日startDate)
    private static testMethod void test09() {
        Test.starttest();
        JEOL_ServiceUketsuke_ctrl ctrl = new JEOL_ServiceUketsuke_ctrl();

        ctrl.serviceDateStatus_support = '対応開始日';
        ctrl.taiouStartDate_support = '3999/12/31';
        ctrl.uketsukeStartDate_support = '3999/12/31';
        ctrl.search2();

        ctrl.serviceDateStatus_support = '対応終了日';
        ctrl.taiouEndDate_support = '1900/01/01';
        ctrl.uketsukeEndDate_support = '1900/01/01';
        ctrl.search2();

        ctrl.serviceDateStatus_support = '対応終了日';
        ctrl.taiouStartDate_support = '';
        ctrl.taiouEndDate_support = '';
        ctrl.search2();

        ctrl.serviceDateStatus_support = '対応終了日';
        ctrl.taiouStartDate_support = 'testDate';
        ctrl.taiouEndDate_support = 'testDate';
        ctrl.search2();

        ctrl.serviceDateStatus_support = '';
        ctrl.uketsukeStartDate_support = '3999/12/31';
        ctrl.uketsukeEndDate_support = '1900/01/01';
        ctrl.search2();

        ctrl.customerCode_support = 'testCCode';
        ctrl.customerName_support = 'testCName';
        ctrl.center_support = 'testCenter';
        ctrl.series_support = 'testSeries';
        ctrl.mainPartNoMachine_support = 'testMPNM';
        ctrl.uketsukeSupportPerson_support = 'testUSP';
        ctrl.serviceType_support = 'testST';
        ctrl.name_support = 'testName';
        ctrl.productNo_support = 'testPN';
        ctrl.keyword_support = 'testKeyword';
        ctrl.status_support = 'testSTS';
        ctrl.uketsukeStartDate_support = 'testUSD';
        ctrl.uketsukeEndDate_support = 'testUED';
        ctrl.serviceDateStatus_support = '対応終了日';
        ctrl.taiouStartDate_support = '';
        ctrl.taiouEndDate_support = '';
        ctrl.search2();

        Test.stoptest();
    }

// -------------------------------------------------------------------------------------------------------------------

    // クッキー生成処理（画面起動時検索フラグON、検索タイプ＝販売）
    private static void createCookies(){
        List<Cookie> cookies = new List<Cookie>();
        // 営業タブ
        cookies.add(new Cookie(COOKIE_LABEL_SALES_CUSTOMER_CODE, 'k001', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_CUSTOMER_NAME, '花子', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_CUSTOMER_CATEGORY, 'testCCcode', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_MODEL_NAME, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_MAIN_PART_NO_MACHINE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_NAME, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_PRODUCT_NO, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_CENTER, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_UKETSUKE_SUPPORT_PERSON, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_SERVICE_DATE_STATUS, '対応開始日', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_TAIOU_START_DATE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SALES_TAIOU_END_DATE, '', COOKIE_PATH, -1, true));
        // サポートタブ
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_CUSTOMER_CODE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_CUSTOMER_NAME, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_CENTER, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_SERIES, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_MAIN_PART_NO_MACHINE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_UKETSUKE_SUPPORT_PERSON, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_SERVICE_TYPE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_NAME, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_PRODUCT_NO, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_KEYWORD, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_STATUS, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_UKETSUKE_START_DATE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_UKETSUKE_END_DATE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_SERVICE_DATE_STATUS, '対応開始日', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_TAIOU_START_DATE, '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_SUPPORT_TAIOU_END_DATE, '', COOKIE_PATH, -1, true));
        // 共通
        cookies.add(new Cookie(COOKIE_LABEL_SEARCH_TYPE, 'sales', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_NUMBER, '1', COOKIE_PATH, -1, true));  // ページ番号
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_SIZE, '10', COOKIE_PATH, -1, true));  // ページサイズ
        cookies.add(new Cookie(COOKIE_LABEL_INIT_SEARCH_FLG, 'true', COOKIE_PATH, -1, true));  // 画面起動時検索フラグ
        // クッキー生成
        Apexpages.currentPage().setCookies(cookies);
    }

    //テストデータ作成
    private static date testData(){

        //取引先
        Account acc = new Account();
        acc.Name = '取テスト１';
        acc.Code__c = 'tt01';
        acc.ServiceAreaBranch__c = '';
        acc.ServiceArea__c = '関東';
        acc.ServiceAreaBranch__c = '01';
        insert acc;

        // 取引先カテゴリ
        Category__c cc = new Category__c();
        cc.Name = 'testCCname';
        cc.Code__c = 'testCCcode';
        insert cc;

        // 取引先カテゴリジャンクション
        CategoryJunction__c ccj = new CategoryJunction__c();
        ccj.CategoryName__c = cc.Id;
        ccj.Account__c = acc.Id;
        insert ccj;

        //品目
        ProductItem__c pItem = new ProductItem__c();
        pItem.Name = 'Test';
        pItem.Model__c = 'T001';
        pItem.Series__c = 'TS';
        pItem.JapaneseName__c = 'テスト';
        pItem.EnglishName__c = 'test';
        insert pItem;
        
        //シリアル番号付品目
        date myDate = date.today();
        datetime myDateTime = datetime.now();
        SerialNoProductItem__c spItem = new SerialNoProductItem__c();
        spItem.Name = 'Test';
        spItem.EfProductNo__c = 'No001';
        spItem.EfProductNoEndDate__c = myDateTime;
        spItem.SvcForm__c = 's01';
        spItem.SerialNo__c = 's00001';
        spItem.ModelsAbbreviation__c = 'c3';
        spItem.AcceptanceDate__c = myDateTime;
        spItem.StatusOfUse__c = 'use';
        spItem.ShipDate__c = myDateTime; 
        spItem.ParentNumber__c = 'p01';
        spItem.ParentItem__c = 'pItem';
        spItem.SpecialNote__c = 'memo'; 
        spItem.SalesTargetCustomer__c = 'sc01';
        spItem.ItemLink__c = pItem.Id;
        spItem.UnitBody__c = 'h01';
        insert spItem;

        //顧客対応票
        Support__c spp = new Support__c();
        spp.Name = 'u001';
        spp.TypeOfService__c = '1：パーコール';
        spp.ServiceTypeCode__c = 'Z1';
        spp.ContactMatter__c = '至急でお願いします';
        spp.SerialNoItemsLink__c = spItem.Id;
        spp.Status__c = 'コール応答中';
        spp.RequestContent1__c = '依頼１';
        spp.RequestContent2__c = '依頼２';
        spp.RequestContent3__c = '依頼３';
        spp.FirstSupportPerson__c = '荒木';
        spp.CustomerFacultyOffice__c = '○支店';
        spp.RelevanceCcReceiptNo__c = 'ku001';
        spp.Search_StartDate__c = myDate;
        spp.Search_EndDate__c = myDate;
        spp.FailureCause1__c = '原因１';
        spp.FailureCause2__c = '原因２';
        spp.FailureCause3__c = '原因３';
        spp.CustomerCode__c = 'k001';
        spp.ServiceStartDate__c = myDate;
        spp.ServiceEndDate__c = myDate;
        spp.CustomerName__c = '花子';
        spp.CustomerAffiliation__c = '○株式会社';
        spp.CustomerContactPerson__c = '太郎';
        spp.SalesCustomer__c = acc.Id;
        spp.UketsukeSupportPerson__c = '荒木';
        spp.ServiceDate2__c = '受付開始日';
        spp.ReceptionDatetime__c = myDate;
        spp.ClassificationDeal1__c = '処置１';
        spp.ClassificationDeal2__c = '処置２';
        spp.ClassificationDeal3__c = '処置３';
        spp.FaultLocation1__c = '障害１';
        spp.FaultLocation2__c = '障害２';
        spp.FaultLocation3__c = '障害３';
        spp.ProductNo__c = 'sei001';
        spp.Responce__c = '対応';
        spp.ServiceDate__c = '対応開始日';
        spp.ServicePerson__c = '荒木';
        spp.CustomerPhone__c = '0120100123';
        spp.CustomerExtension__c = 'memo';
        spp.SecondSupportPerson__c = '新井';
        spp.SalesOrderNo__c = 'so001';
        spp.MaintenanceSerialNo__c = 'M00001';
        spp.UnitBody__c = 'g01';
        insert spp;
        
        return myDate;
    }

}