objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>住所</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>地域</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewContractEndDate__c</fullName>
        <label>契約完了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewContractStartDate__c</fullName>
        <label>契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrAssistant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>アシスタント</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MDM_Assistant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrNetMaintenance__c</fullName>
        <label>NET保守区分</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrOrdersMemp__c</fullName>
        <label>受注メモ</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.SalesAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.SalesAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (販売先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesContactFax__c</fullName>
        <label>販売先担当者FAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesContactPosition__c</fullName>
        <label>販売先担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesContactTel__c</fullName>
        <label>販売先担当者TEL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesTantoshya__c</fullName>
        <label>販売先担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>系列</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ShipmentAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ShipmentAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (出荷先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentContactPosition__c</fullName>
        <label>出荷先担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentContact_Fax__c</fullName>
        <label>出荷先担当者FAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentContact_Tel__c</fullName>
        <label>出荷先担当者TEL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentTantosha__c</fullName>
        <label>出荷先担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客先名</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RenewalAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RenewalAddress__c</fullName>
        <label>住所</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalContactFax__c</fullName>
        <label>日本電子・回答先（FAX等）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalContactPosition__c</fullName>
        <label>担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalContactTel__c</fullName>
        <label>日本電子・連絡先（電話番号等）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalTantoshya__c</fullName>
        <label>担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>保守契約管理</relationshipLabel>
        <relationshipName>MaintPipeline_UnitBody</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>地域</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssistantCode__c</fullName>
        <label>アシスタントコード</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assistant__c</fullName>
        <label>アシスタント</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder_MaintenancePL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NetMaintenance__c</fullName>
        <label>NET保守区分</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrdersMemp__c</fullName>
        <label>受注メモ</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (販売先取引先)</relationshipLabel>
        <relationshipName>SalesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesContactPosition__c</fullName>
        <label>販売先担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesStaffCode__c</fullName>
        <label>営業担当コード</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesStaff__c</fullName>
        <label>営業担当名</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesTantoshya__c</fullName>
        <label>販売先担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列（装置）</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentContactPosition__c</fullName>
        <label>出荷先担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentTantosha__c</fullName>
        <label>出荷先担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <recordTypes>
        <fullName>HosyuKeiyaku</fullName>
        <active>true</active>
        <label>保守契約詳細</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SelectListManage__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>表示名称</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceName__c</fullName>
        <label>選択リスト参照名</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>ソート番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>値</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>選択リスト管理</label>
    <nameField>
        <label>選択リストグループ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>DeliveryAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>納入先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>本体号機 (納入先取引先)</relationshipLabel>
        <relationshipName>DeliveryAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>本体号機 (販売先取引先)</relationshipLabel>
        <relationshipName>Sales_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <formula>ItemLink__r.Series__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>系列</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingDateFormula__c</fullName>
        <formula>Datevalue(ShippingDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>出荷日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_MaintenanceListNewAdd_ctrl.cls
public with sharing class JEOL_MaintenanceListNewAdd_ctrl {
    
    private static boolean addContractMaintenanceList(List<id> lsId, boolean isBatch, List<Integer> nbRowsInserted, List<String> messageError) {

        if (nbRowsInserted != NULL && nbRowsInserted.size() > 0) {
            nbRowsInserted[0] = 0;
        }
        if (messageError != NULL && messageError.size() > 0) {
            messageError[0] = '';
        }

        try {

            List<MaintenanceContractManagement__c> lsToBeAded = new List<MaintenanceContractManagement__c>();
            
            List<UnitBody__c> lsUB = [SELECT Id, Series__c, Name, ShippingDateFormula__c, SalesAccount__c, SalesAccount__r.phone, SalesAccount__r.fax, SalesAccount__r.Address__c, DeliveryAccount__c, DeliveryAccount__r.phone, DeliveryAccount__r.fax, DeliveryAccount__r.Area__c
                                      FROM UnitBody__c
                                      WHERE id IN :lsId
                                      AND Id NOT IN (SELECT UnitBody__c FROM MaintenanceContractManagement__c)
                                     ];



            List<String> lsArea = new List<String>();
            
            for (UnitBody__c so : lsUB) {
                if (so.DeliveryAccount__r.Area__c != null && so.DeliveryAccount__r.Area__c.length() > 0) {
                    lsArea.add(so.DeliveryAccount__r.Area__c);
                }
            }
            
            // Get the list of Area Code
            List<SelectListManage__c> lsAreaCode = [SELECT Value__c, Label__c
                                                    FROM SelectListManage__c
                                                    WHERE ReferenceName__c =: JEOLUtil.REFERENCE_NAME_MAINTENANCE_AREA
                                                    AND Label__c IN :lsArea
                                                    ORDER BY SortNo__c desc, Value__c desc
                                                   ];
                                                   
            Map<String, String> mpAreaCode = new Map<String, String>();
            if (lsAreaCode != null && lsAreaCode.size() > 0) {
                for (SelectListManage__c slm : lsAreaCode) {
                    mpAreaCode.put(slm.Label__c, slm.Value__c);
                }
            }

            for (UnitBody__c so : lsUB) {
            
                MaintenanceContractManagement__c row = new MaintenanceContractManagement__c();

                row.NewOdrSeries__c = so.Series__c;
                row.UnitBody__c = so.id;
                
                
                if (so.ShippingDateFormula__c != null) {
                    row.NewContractStartDate__c = so.ShippingDateFormula__c.addYears(1);
                    row.NewContractEndDate__c = row.NewContractStartDate__c.addYears(1).addDays(-1);      
                }

                row.RenewalAccount__c = so.SalesAccount__c;
                row.RenewalAddress__c = so.SalesAccount__r.Address__c;
                // row.RenewalContactPosition__c = null;
                // row.RenewalTantoshya__c = null;
                row.RenewalContactTel__c = so.SalesAccount__r.phone;
                row.RenewalContactFax__c = so.SalesAccount__r.fax;


                // row.NewOdrName__c = null;
                //row.NewOdrNetMaintenance__c = so.NetMaintenance__c;
                row.NewOdrSalesAccount__c = so.SalesAccount__c;
                //row.NewOdrSalesContactPosition__c = so.SalesContactPosition__c;
                //row.NewOdrSalesTantoshya__c = so.SalesTantoshya__c;
                row.NewOdrSalesContactTel__c = so.SalesAccount__r.phone;
                row.NewOdrSalesContactFax__c = so.SalesAccount__r.fax;
                row.NewOdrShipmentAccount__c = so.DeliveryAccount__c;
                //row.NewOdrShipmentContactPosition__c = so.ShipmentContactPosition__c;
                //row.NewOdrShipmentTantosha__c = so.ShipmentTantosha__c;
                row.NewOdrShipmentContact_Tel__c = so.DeliveryAccount__r.phone;
                row.NewOdrShipmentContact_Fax__c = so.DeliveryAccount__r.fax;

                //row.NewOdrOrdersMemp__c = so.OrdersMemp__c;
                //row.NewOdrSalesStaffCode__c = so.SalesStaffCode__c;
                //row.NewOdrSalesStaff__c = so.SalesStaff__c;
                //row.NewOdrAssistantCode__c = so.AssistantCode__c;
                //row.NewOdrAssistant__c = so.Assistant__c;

                //row.NewOdrFlagshipProduct__c = so.FlagshipProduct__c;

                if (mpAreaCode != null && mpAreaCode.containsKey(so.DeliveryAccount__r.Area__c)) {
                    row.NewOdrRegion__c =  mpAreaCode.get(so.DeliveryAccount__r.Area__c); 
                }

                row.NewOdrMaintenanceStartDate__c = row.NewContractStartDate__c;
                row.NewOdrMaintenanceEndDate__c = row.NewContractEndDate__c;      
                row.NewOdrContractAmountt__c = row.NewContractAmount__c;     

                // row.PreviousYearOrder__c = null;
                // row.RegionName__c =  null;
                // row.NewContractAmount__c = null;

                // row.PreviousYearPipeline__c =  null; 
                // row.AnnaiType__c = null; 
                // row.JeolPipelineResponsible__c = null;


                // row.QuotationCreated__c = false;
                // row.ContractSentDate__c = null;
                // row.QuotationSentDate__c = null;
                // row.RenewalNoticeSentDate__c = null;
                // row.RenewalNoticeCreated__c = false;
                // row.RenewalApproved__c = false;
                // row.PipelineStopped__c = false;
                // row.PipelineStoppedReason__c = null;

                // row.Memo__c = null;
                // row.NextYearNotes__c = null;          
                // row.LinkageStatus__c = default value;          
                // row.ProductNumber__c = later in the pipeline;
                
                lsToBeAded.add(row);
            }
            
            if (lsToBeAded != null && lsToBeAded.size() > 0) {
                insert lsToBeAded;

                if (nbRowsInserted != NULL && nbRowsInserted.size() > 0) {
                    nbRowsInserted[0] = lsToBeAded.size();
                }

                if (!isBatch) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.JEOL_MaintRenewalAdd_Message_DataAdded));
                }
            }

            return true;

        } catch(Exception e) {

            if (messageError != NULL && messageError.size() > 0) {
                messageError[0] = 'JEOL_MaintenanceListNewAdd_ctrl.addContractMaintenanceList でエラーが発生しました。' + e.getMessage();
            }
            return false;

        }
                          
    }       

    /**
     * Add the contract maintenance from the UnitBody table. 
     *
     * @param   nbRowsInserted Number of rows inserted
     * @param   messageError   Error messagethe location of the image, relative to the url argument
     * @return                 Indicates if the execution of the method has been a success
     */
     public static boolean addContractMaintenanceBatch(Integer nbRowsMax, List<Integer> nbRowsInserted, List<String> messageError) {

        try {

            date dTodayFirstDay = Date.newInstance(date.today().year(), date.today().month(), 1);
            
            List<UnitBody__c> lsUB;

            if (nbRowsMax != NULL) {
                lsUB = [SELECT Id
                        FROM UnitBody__c
                        WHERE UnitBody__c != null
                        AND (ShippingDateFormula__c >= 2016-04-01 AND ShippingDateFormula__c < :dTodayFirstDay)
                        AND Id NOT IN (SELECT UnitBody__c from MaintenanceContractManagement__c WHERE IsHeliumOnly__c = false)
                        AND Id NOT IN (SELECT UnitBodyLink__c from SalesOrder__c where RecordType.DeveloperName = 'HosyuKeiyaku' and (MaintenanceContractManagement__c = null OR MaintenanceContractManagement__r.IsHeliumOnly__c = false))
                        AND (NOT DeliveryAccount__r.Code__c  LIKE '0%')
                        LIMIT :nbRowsMax
                       ]; 
            } else {
                lsUB = [SELECT Id
                        FROM UnitBody__c
                        WHERE UnitBody__c != null
                        AND (ShippingDateFormula__c >= 2016-04-01 AND ShippingDateFormula__c < :dTodayFirstDay)
                        AND Id NOT IN (SELECT UnitBody__c from MaintenanceContractManagement__c WHERE IsHeliumOnly__c = false)
                        AND Id NOT IN (SELECT UnitBodyLink__c from SalesOrder__c where RecordType.DeveloperName = 'HosyuKeiyaku' and (MaintenanceContractManagement__c = null OR MaintenanceContractManagement__r.IsHeliumOnly__c = false))
                        AND (NOT DeliveryAccount__r.Code__c  LIKE '0%')
                       ];                 
            }

            List<id> lsId = new List<id>();
            for (UnitBody__c ub : lsUB) {
                lsId.add(ub.id);
            }
            return addContractMaintenanceList(lsId, true, nbRowsInserted, messageError);

        } catch (Exception e) {

            if (messageError != NULL && messageError.size() > 0) {
                messageError[0] = 'JEOL_MaintenanceListNewAdd_ctrl.addContractMaintenanceBatch でエラーが発生しました。' + e.getMessage();
            }
            return false;

        }

    }

}