objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>住所</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Undergraduate__c</fullName>
        <inlineHelpText>Undergraduate</inlineHelpText>
        <label>学部・事業所</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <formula>AddressLine1__c + &apos; &apos; + AddressLine2__c + &apos; &apos; + AddressLine3__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>住所</label>
        <type>Text</type>
    </fields>
    <label>部署</label>
    <nameField>
        <label>部署名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MaintenanceAccountBook__c.object
<CustomObject>
    <fields>
        <fullName>InspectionDone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>点検済</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inspection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>点検</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <label>保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>管理台帳</relationshipLabel>
        <relationshipName>MaintenanceAccountBook</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>月</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAmountEstimate__c</fullName>
        <label>売上（予定）</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>保守管理台帳</label>
    <nameField>
        <label>月</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewOdrContractAmountt__c</fullName>
        <label>保守契約金額</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NewOdrDepartment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オフィス</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>保守契約管理</relationshipLabel>
        <relationshipName>MDM_Department</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrFlagshipProduct__c</fullName>
        <label>商品名</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrMaintenancePeriodText__c</fullName>
        <formula>TRIM(SUBSTITUTE(TEXT(NewOdrMaintenanceStartDate__c), &apos;-&apos;, &apos;/&apos;) &amp; &apos; - &apos; &amp; SUBSTITUTE(TEXT(NewOdrMaintenanceEndDate__c), &apos;-&apos;, &apos;/&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約期間</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrRegion__c</fullName>
        <label>地域</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.SalesAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.SalesAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (販売先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>保守契約管理 (販売オーダ)</relationshipLabel>
        <relationshipName>NewOdrSalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>系列</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ShipmentAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ShipmentAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (出荷先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreviousYearOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>前年オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipName>PreviousYearOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <label>製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客先名</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RenewalAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>保守契約管理</relationshipLabel>
        <relationshipName>MaintPipeline_UnitBody</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model__c.object
<CustomObject>
    <description>デモレポート用機種マスタ</description>
    <label>機種</label>
    <nameField>
        <label>形式</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>FlagshipProduct__c</fullName>
        <label>受注代表商品名</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder_MaintenancePL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <label>製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <formula>ItemLink__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>機種</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_MaintenanceInspectionListCsv_ctrl.cls
public without sharing class JEOL_MaintenanceInspectionListCsv_ctrl extends JEOL_SearchBase_ctrl {

    public String month{get; set;}
    public String customerCode{get; set;}
    public String customerName{get; set;}
    public String unitBody{get; set;}
    public String status{get; set;}
    public String type{get; set;}

    private List<String> targetSeries;
    private List<String> targetRegions;

    Public List<List<String>> lslsstrRowMCM{get;set;}

    Public String sTitle{get;set;}

    Public String getFileName() {
        return 'InspectionList_' + date.today().format() + '.csv';
    }
    
    Public JEOL_MaintenanceInspectionListCsv_ctrl() {

        // Forbid the launch is the user has not the adequate permission set and ia not an admin
        Profile p = [Select Name from Profile where Id =: userinfo.getProfileid()];
        if (p.Name != 'System Admin' && 
            p.Name != 'System Administrator' && 
            p.Name != 'システム管理者' 
           ) {

            List<PermissionSetAssignment> lsPerm = [SELECT PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId= :UserInfo.getUserId() AND PermissionSet.Name = 'Maintenance_PermSet_02'];
            if (lsPerm == NULL || lsPerm.size() == 0) {
                return;
            }
            
        }

        initFieldFromCookie();
        String soql = ' SELECT ' +
                            ' Id, Name, Month__c, Inspection__c, InspectionDone__c, MaintenanceContractManagement__r.NewOdrSeries__c, MaintenanceContractManagement__r.NewOdrRegion__c, ' +
                            ' MaintenanceContractManagement__r.ProductNumber__c, MaintenanceContractManagement__r.PreviousYearOrder__r.FlagshipProduct__c, ' +
                            ' MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Name, MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Undergraduate__c, MaintenanceContractManagement__r.NewOdrContractAmountt__c, MaintenanceContractManagement__r.NewOdrSalesOrder__c, MaintenanceContractManagement__r.NewOdrSalesOrder__r.Name, ' +
                            ' MaintenanceContractManagement__r.UnitBody__c, Type__c, SalesAmountEstimate__c, MaintenanceContractManagement__r.UnitBody__r.Model__c, MaintenanceContractManagement__r.NewOdrFlagshipProduct__c, ' +
                            ' MaintenanceContractManagement__c, MaintenanceContractManagement__r.Name, MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Code__c, ' +
                            ' MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Address__c, MaintenanceContractManagement__r.UnitBody__r.Name, MaintenanceContractManagement__r.NewOdrMaintenancePeriodText__c, ' +
                            ' MaintenanceContractManagement__r.NewOdrDepartment__r.Name ' +
                      ' FROM ' +
                            ' MaintenanceAccountBook__c ';                    

        List<String> whereStrElems = getWhereStrList();
        if (whereStrElems.size() > 0) {
            soql += JEOLUtil.joinWhereConditions(whereStrElems);
        }
            
        lslsstrRowMCM = new List<List<String>>();
        
        sTitle = '';
        sTitle = ConcatenateField(sTitle, '保守契約管理: 保守契約管理番号', true);
        sTitle = ConcatenateField(sTitle, '販売オーダ', false);
        sTitle = ConcatenateField(sTitle, '系列', false);
        sTitle = ConcatenateField(sTitle, '保守管理台帳: 月', false);
        sTitle = ConcatenateField(sTitle, '点検', false);
        sTitle = ConcatenateField(sTitle, '点検済', false);
        sTitle = ConcatenateField(sTitle, '販売オフィス', false);
        sTitle = ConcatenateField(sTitle, '保守契約期間', false);
        sTitle = ConcatenateField(sTitle, '出荷先取引コード', false);
        sTitle = ConcatenateField(sTitle, '出荷先取引先', false);
        sTitle = ConcatenateField(sTitle, '出荷先取引住所', false);
        sTitle = ConcatenateField(sTitle, '商品名', false);
        sTitle = ConcatenateField(sTitle, '製番', false);
        sTitle = ConcatenateField(sTitle, '本体号機', false);
        sTitle = ConcatenateField(sTitle, '売上（予定）', false);
        sTitle = ConcatenateField(sTitle, '契約金額', false);

        List<String> lsstrRowMCM = new List<String>();
        integer iSize = 0;

system.debug('Query for csv: ' + soql);
        for (MaintenanceAccountBook__c mcm : Database.Query(soql + ' ORDER BY NAME LIMIT 10000 ')) {
                
            if (iSize == 1000) {
                lslsstrRowMCM.add(lsstrRowMCM);
                lsstrRowMCM = new List<String>();
                iSize = 0;
            }
            
            String sRow = '';
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.Name, true);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrSalesOrder__r.Name, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrSeries__c, false);
            sRow = ConcatenateField(sRow, mcm.Name, false);
            sRow = ConcatenateField(sRow, mcm.Inspection__c ? 1 : 0, false);
            sRow = ConcatenateField(sRow, mcm.InspectionDone__c ? 1 : 0, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrDepartment__r.Name, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrMaintenancePeriodText__c, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Code__c, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Name, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Address__c, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrFlagshipProduct__c, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.ProductNumber__c, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.UnitBody__r.Name, false);
            sRow = ConcatenateField(sRow, mcm.SalesAmountEstimate__c, false);
            sRow = ConcatenateField(sRow, mcm.MaintenanceContractManagement__r.NewOdrContractAmountt__c, false);
                        
            lsstrRowMCM.add(sRow);
            
            iSize += 1;
        }
        lslsstrRowMCM.add(lsstrRowMCM);
    }
    
    private String ConcatenateField(String strConcat, object field, boolean fFirstField) {    
        String sReturn = strConcat;
        if (!fFirstField) {
            sReturn += ',';
        }
        if (field != null) {
            if (field instanceOf boolean ||
                field instanceOf Decimal ||
                field instanceOf Date) {
                sReturn += field;
            } else {
                String sField = (String)field;
                sField = sField.replaceAll('[\n\r]', ' ');
                sReturn += '"' + sField.replace('"', '""') + '"';
            }
        }
        return sReturn;
    }


    private List<String> getWhereStrList() {

        List<String> strList = new List<String>();

        strList.add('Inspection__c = true');
        
        if (String.isNotBlank(this.month)) {
            strList.add(JEOLUtil.appendAfterLikeText('month__c', this.month));
        }
        if (this.targetSeries != null && this.targetSeries.size() > 0) {
            strList.add('(' + JEOLUtil.appendInText('MaintenanceContractManagement__r.NewOdrSeries__c', this.targetSeries) + ')');
        }
        if (this.targetRegions != null && this.targetRegions.size() > 0) {
            strList.add('(' + JEOLUtil.appendInText('MaintenanceContractManagement__r.NewOdrRegion__c', this.targetRegions) + ')');
        }
        
        if (String.isNotBlank(this.customerCode)) {
            strList.add('((' + JEOLUtil.appendAfterLikeText('MaintenanceContractManagement__r.RenewalAccount__r.Code__c', this.customerCode) + ') OR ' +
                         '(' + JEOLUtil.appendAfterLikeText('MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Code__c', this.customerCode) + ') OR ' +
                         '(' + JEOLUtil.appendAfterLikeText('MaintenanceContractManagement__r.NewOdrSalesAccount__r.Code__c', this.customerCode) + '))');
        }
        if (String.isNotBlank(this.customerName)) {
            strList.add('((' + JEOLUtil.appendLikeText('MaintenanceContractManagement__r.RenewalAccount__r.Name', this.customerName) + ') OR ' +
                         '(' + JEOLUtil.appendLikeText('MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Name', this.customerName) + ') OR ' +
                         '(' + JEOLUtil.appendLikeText('MaintenanceContractManagement__r.NewOdrSalesAccount__r.Name', this.customerName) + '))');
        }
        if (String.isNotBlank(this.unitBody)) {
            strList.add(JEOLUtil.appendAfterLikeText('MaintenanceContractManagement__r.UnitBody__r.Name', this.unitBody));
        }
        if (String.isNotBlank(this.status)) {        
            if (this.status == '1') {
                strList.add('InspectionDone__c = true');
            } else if (this.status == '2') {
                strList.add('InspectionDone__c = false');
            }
        }
        if (String.isNotBlank(this.type)) {
            strList.add(JEOLUtil.appendEqualText('type__c', this.type));
        }
        
        return strList;
    }
    
    
    private void initFieldFromCookie() {

        final String PARAM_MONTH = 'MONTH';
        final String PARAM_CUSTOMERCODE = 'CUSTOMERCODE';
        final String PARAM_CUSTOMERNAME = 'CUSTOMERNAME';
        final String PARAM_UNITBODY = 'UNITBODY';
        final String PARAM_STATUS = 'STATUS';
        final String PARAM_TYPE = 'TYPE';
        final String PARAM_SERIES = 'SERIES';
        final String PARAM_REGIONS = 'REGIONS';
            
        if (apexpages.currentpage().getparameters().containsKey(PARAM_MONTH)) {
            this.month = apexpages.currentpage().getparameters().get(PARAM_MONTH);
        }

        if (apexpages.currentpage().getparameters().containsKey(PARAM_CUSTOMERCODE)) {
            this.customerCode = apexpages.currentpage().getparameters().get(PARAM_CUSTOMERCODE);
        }

        if (apexpages.currentpage().getparameters().containsKey(PARAM_CUSTOMERNAME)) {
            this.customerName = apexpages.currentpage().getparameters().get(PARAM_CUSTOMERNAME);
        }

        if (apexpages.currentpage().getparameters().containsKey(PARAM_UNITBODY)) {
            this.UnitBody = apexpages.currentpage().getparameters().get(PARAM_UNITBODY);
        }
    
        if (apexpages.currentpage().getparameters().containsKey(PARAM_STATUS)) {
            this.status = apexpages.currentpage().getparameters().get(PARAM_STATUS);
        }

        if (apexpages.currentpage().getparameters().containsKey(PARAM_TYPE)) {
            this.type = apexpages.currentpage().getparameters().get(PARAM_TYPE);
        }

        if (apexpages.currentpage().getparameters().containsKey(PARAM_SERIES)) {
            String targetSeriesText = apexpages.currentpage().getparameters().get(PARAM_SERIES);
            if (String.isNotBlank(targetSeriesText)) {
                this.targetSeries = targetSeriesText.split('_');
            }
        }    

        if (apexpages.currentpage().getparameters().containsKey(PARAM_REGIONS)) {
            String targetRegionsText = apexpages.currentpage().getparameters().get(PARAM_REGIONS);
            if (String.isNotBlank(targetRegionsText)) {
                this.targetRegions = targetRegionsText.split('_');
            }
        }    

    }
                
}