objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ProductCatalog__c.object
<CustomObject>
    <fields>
        <fullName>ClassificationNo__c</fullName>
        <label>分類</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelType__c</fullName>
        <label>機種区分</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProductCatalog__c</fullName>
        <label>製品カタログ</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>品目カタログ情報</relationshipLabel>
        <relationshipName>CtalogItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SearchKeyWord__c</fullName>
        <label>検索キー</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>品目カタログ情報</label>
    <nameField>
        <label>カタログ情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductItem__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>区分</label>
        <picklist>
            <picklistValues>
                <fullName>製品</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>パーツ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>JapaneseName__c</fullName>
        <label>品目名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelType__c</fullName>
        <externalId>true</externalId>
        <label>形式</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tani__c</fullName>
        <label>単位</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>単価</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/QuotationDetailInformation__c.object
<CustomObject>
    <fields>
        <fullName>BranchNo__c</fullName>
        <formula>LEFT( RIGHT( QuoteNo_BranchNo_SEQ_Sync__c , 9) , 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>枝番</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Depth__c</fullName>
        <label>Depth</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DiscountAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>値引き金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DiscountRate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>値引き率</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IsDiscountTarget__c</fullName>
        <defaultValue>false</defaultValue>
        <label>値引設定対象</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsDisplayDecimal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gets its value from UserSetting__c&apos;s IsDisplayDecimal__c field.</description>
        <label>isDisplayDecimal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>見積書情報</label>
        <referenceTo>QuotationInformation__c</referenceTo>
        <relationshipLabel>見積書詳細情報</relationshipLabel>
        <relationshipName>QuotationDetailInformations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuoteNo__c</fullName>
        <formula>LEFT(QuoteNo_BranchNo_SEQ_Sync__c,  FIND(&quot;_&quot;, QuoteNo_BranchNo_SEQ_Sync__c) - 1 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>見積No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>ソート番号</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>単価</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>見積書詳細情報</label>
    <nameField>
        <displayFormat>QT{00000000}</displayFormat>
        <label>見積書詳細</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuotationInformation__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDate__c</fullName>
        <label>検収日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BranchNo__c</fullName>
        <label>枝番</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>契約先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.CustomerSituation__c</field>
                <operation>equals</operation>
                <value>有効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>見積書情報（契約先）</relationshipLabel>
        <relationshipName>ContractQuotationInformations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractContact_dummyField__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Visualforce画面にて検索ダイアログを出すためだけに使用。
値は入れないようにしてください。</description>
        <label>契約先担当者_検索ダイアログ用</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>見積書情報</relationshipLabel>
        <relationshipName>QuotationInformations_ContractContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreatedDateFormula__c</fullName>
        <formula>IF ($RecordType.DeveloperName == &apos;BaaN&apos;, RegisterDate__c, DateValue(CreatedDate))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>登録日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DepartmentCode__c</fullName>
        <label>部署コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverrideDepartmentCode__c</fullName>
        <label>部署コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuotationNameExpress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>見積名称出力</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuoteNo__c</fullName>
        <description>自社内管理の見積番号</description>
        <label>見積No.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAreaCode__c</fullName>
        <label>地域コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>納入先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.CustomerSituation__c</field>
                <operation>equals</operation>
                <value>有効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>見積書情報 (納入先)</relationshipLabel>
        <relationshipName>ShipmentQuotationInformations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentCode__c</fullName>
        <label>納入先コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentContact_dummyField__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>納入先担当者_検索ダイアログ用</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>見積書情報 (納入先担当者_検索ダイアログ用)</relationshipLabel>
        <relationshipName>QuotationInformations_ShipmentContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isDisplayDecimal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gets its value from UserSetting__c&apos;s IsD</description>
        <label>整数表示フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>見積書情報</label>
    <nameField>
        <label>見積名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDate__c</fullName>
        <label>検収日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UserSetting__c.object
<CustomObject>
    <fields>
        <fullName>DefaultRowsHeading__c</fullName>
        <label>見出し</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DefaultRowsItems__c</fullName>
        <label>項目</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DefaultRowsSubItems__c</fullName>
        <label>段下げ項目</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsDisplayDecimal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Checked, displays insignificant decimal values, for example: 1.0
If Un-checked, removes insignificant decimal values, for example: 1</description>
        <inlineHelpText>If Checked, displays insignificant decimal values, for example: 1.0
If Un-checked, removes insignificant decimal values, for example: 1</inlineHelpText>
        <label>明細数量の整数表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OverrideDepartmentCode__c</fullName>
        <label>部署コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductDivision__c</fullName>
        <label>品目区分</label>
        <picklist>
            <picklistValues>
                <fullName>製品</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>パーツ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QuotationNameExpress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>見積名称出力</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Word1__c</fullName>
        <label>文言1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Word2__c</fullName>
        <label>文言2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Word3__c</fullName>
        <label>文言3</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WordSettingDefaultDisplay1__c</fullName>
        <label>文言設定デフォルト表示1</label>
        <picklist>
            <picklistValues>
                <fullName>表示</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>非表示</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WordSettingDefaultDisplay2__c</fullName>
        <label>文言設定デフォルト表示2</label>
        <picklist>
            <picklistValues>
                <fullName>表示</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>非表示</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WordSettingDefaultDisplay3__c</fullName>
        <label>文言設定デフォルト表示3</label>
        <picklist>
            <picklistValues>
                <fullName>表示</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>非表示</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>個人設定</label>
    <nameField>
        <label>個人設定名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_QuotationEditorPageCtrlTest.cls
@IsTest
private class JEOL_QuotationEditorPageCtrlTest {

    private static testMethod void test01() {
        
        QuotationInformation__c quot = new QuotationInformation__c();
        insert quot;
       
        QuotationDetailInformation__c quotdet = new QuotationDetailInformation__c();
        quotdet.Parent__r = quot;
        quotdet.Parent__c = quot.id;
        quotdet.Depth__c = 1;
        quotdet.SortNo__c = 0;
        quotdet.IsDiscountTarget__c = true;
        quotdet.DiscountRate__c = 10;
        quotdet.DiscountAmount__c = 10;
        insert quotdet;

        Pagereference ref = Page.JEOL_QuotationEditorPage;
        Map<String, String> params = new Map<String, String>();
        params.put('id', quot.id);
        ref.getParameters().putAll(params);
                               
        Test.setCurrentPage(ref);
               
        JEOL_QuotationEditorPageCtrl ctrl = new JEOL_QuotationEditorPageCtrl();
        
        QuotationInformation__c ret01 = ctrl.getProxyObject();
        String ret02 = ctrl.getDetailType();
        ctrl.setDetailType('dummy');
        
        List<SelectOption> ret1 = ctrl.getQuoteTypeOptions();
        List<SelectOption> ret2 = ctrl.getSeriesOptions();
        List<SelectOption> ret3 = ctrl.getUnitOptions();
        List<SelectOption> ret4 = ctrl.getSalesAreaOptions();
        List<SelectOption> ret5 = ctrl.getDelivConditionOptions();
        List<SelectOption> ret6 = ctrl.getQuantityUnitOptions();
        List<SelectOption> ret7 = ctrl.getDepartmentOptions();
        List<SelectOption> ret8 = ctrl.getProductDivisionOptions();
        Pagereference ret9 = ctrl.quotationCopy();
        Pagereference ret10 = ctrl.quotationCopyAndBranch();
        ctrl.acceptanceDateCalc();
        List<SelectOption> ret11 = ctrl.getCandidateUnitBody();
        ctrl.salesAreaAttachment();
        ctrl.salesAreaAttachmentBis();
        ctrl.quoteTypeAttachment();
        ctrl.delivConditionAttachment();
        ctrl.departmentInfoAttachment();
        ctrl.overDepartmentInfoAttachment();
        ctrl.ContractAttachmentFromCode();
        ctrl.ShipmentAttachmentFromCode();
        ctrl.ContractAttachment();
        ctrl.ShipmentAttachment();
        ctrl.contractContactAttachment();
        ctrl.shipmentContactAttachment();
        ctrl.contractAccountInputCopy();
        ctrl.includeDestinationData();
        ctrl.ajaxSaveAction();
        ctrl.deleteMultiRows();
        ctrl.doSaveWithPrintDatePart1();
        ctrl.doSaveWithPrintDatePart2();
        ctrl.doSaveWithDestinationPrintDatePart1();
        ctrl.doSaveWithDestinationPrintDatePart2();
        ctrl.doSaveWithCertificationPrintDatePart1();
        ctrl.doSaveWithCertificationPrintDatePart2();
        PageReference ret12 = ctrl.deleteAction();
        
        Map<String, String> mapss = new Map<String, String>();
        mapss.put('JapaneseName__c', 'dummy');
        mapss.put('Name', 'dummy');
        mapss.put('Division__c', 'dummy');
        mapss.put('ModelType__c', 'dummy');
        List<ProductItem__c> ret13 = JEOL_QuotationEditorPageCtrl.getProductMaster(mapss);
        
        ProductItem__c ret14 = JEOL_QuotationEditorPageCtrl.searchProductItem('dummy');

        Map<String, String> mapss2 = new Map<String, String>();
        mapss2.put('Name', 'dummy');
        mapss2.put('QuoteNo__c', 'dummy');
        mapss2.put('BranchNo__c', 'dummy');
        mapss2.put('CreatedDateFormula__c', '2015/08/16');
        List<QuotationInformation__c> ret15 = JEOL_QuotationEditorPageCtrl.getQuotationInfo(mapss2);
     
        Map<String, String> mapss3 = new Map<String, String>();
        mapss3.put('Parent__c', quot.id);
        List<QuotationDetailInformation__c> ret16 = JEOL_QuotationEditorPageCtrl.getQuotationDetails(mapss3);

        Map<String, String> mapss4 = new Map<String, String>();
        mapss4.put('ClassificationNo__c', 'dummy');
        mapss4.put('SearchKeyWord__c', 'dummy');
        mapss4.put('ProductCatalog__c', 'dummy');
        List<ProductCatalog__c> ret17 = JEOL_QuotationEditorPageCtrl.getCatalogHead(mapss4);
        
        List<ProductCatalog__c> ret18 = JEOL_QuotationEditorPageCtrl.getChildStructure('dummy', 'dummy');
        
        List<JEOL_QuotationEditorPageCtrl.QuotationDetailItem> ret19 = ctrl.qdm.getItems();
        List<JEOL_QuotationEditorPageCtrl.QuotationDetailItem> ret20 = ctrl.qdm.getBaseItems();
        ctrl.qdm.createQuotationDetail();
        ctrl.qdm.createHeadingDetail();
        ctrl.qdm.createOverheadDetail();
        ctrl.qdm.createSubtotalDetail();
        ctrl.qdm.createCommissionDetail();
        QuotationDetailInformation__c ret21 = ctrl.qdm.createInitalizedRecord();
        integer ret22 = ctrl.qdm.getCurrentSize();
        ctrl.qdm.refreshDetailProductItem();
        ctrl.qdm.importDetailFromQuotation();
        
        ctrl.qdm.createdItemInfos = '{"sortNo":"18","items":[{"Name":"331465","JapaneseName__c":"ＦＴ　ＮＭＲ装置","UnitPrice__c":"75000000","Tani__c":"PC","ModelType__c":"JNM-ECX400(A)"},{"Name":"307645","JapaneseName__c":"ＦＴ　ＮＭＲ装置","UnitPrice__c":"460000000","Tani__c":"PC","ModelType__c":"JNM-ECA800"}]}';
        ctrl.qdm.createSelectedProductItemDetails();
        
        JEOL_QuotationEditorPageCtrl.QuotationDetailItem qdi = new JEOL_QuotationEditorPageCtrl.QuotationDetailItem(quotdet);
        qdi.executeAmountCalc();
        Decimal ret23 = qdi.getAmount();
        qdi.deleteAction();
        qdi.copyAction();
        QuotationDetailInformation__c ret24 = qdi.detailCopy();
        Integer ret25 = qdi.compareTo(qdi);
        
    }

    private static testMethod void test02() {
        
        QuotationInformation__c quot = new QuotationInformation__c();
        quot.UnitBody__c = '1234';
        insert quot;
               
        QuotationDetailInformation__c quotdet = new QuotationDetailInformation__c();
        quotdet.Parent__r = quot;
        quotdet.Parent__c = quot.id;
        quotdet.Depth__c = 1;
        quotdet.SortNo__c = 0;
        quotdet.IsDiscountTarget__c = true;
        quotdet.DiscountRate__c = 10;
        quotdet.DiscountAmount__c = 10;
        insert quotdet;

        Pagereference ref = Page.JEOL_QuotationEditorPage;
        Map<String, String> params = new Map<String, String>();
        params.put('id', quot.id);
        params.put(JEOL_QuotationEditorPageCtrl.URL_PARAM_NAME_ISCOPY, 'true');
        params.put(JEOL_QuotationEditorPageCtrl.URL_PARAM_NAME_ISBRANCH, 'true');
        params.put(JEOL_QuotationEditorPageCtrl.SCROLL_TOP, '1');
        
        ref.getParameters().putAll(params);
                               
        Test.setCurrentPage(ref);
               
        JEOL_QuotationEditorPageCtrl ctrl = new JEOL_QuotationEditorPageCtrl();
        
    }
    
    private static testMethod void test03() {
        
        UserSetting__c usrSet = new UserSetting__c();
        usrSet.WordSettingDefaultDisplay1__c = '表示';
        usrSet.WordSettingDefaultDisplay2__c = '表示';
        usrSet.WordSettingDefaultDisplay3__c = '表示';
        usrSet.Word1__c = 'dummy';
        usrSet.Word2__c = 'dummy';
        usrSet.Word3__c = 'dummy';
        usrSet.ProductDivision__c = '製品';
        usrSet.QuotationNameExpress__c = true;
        usrSet.IsDisplayDecimal__c = true;
        usrSet.DefaultRowsItems__c = 1;
        usrSet.DefaultRowsHeading__c = 1;
        usrSet.DefaultRowsSubItems__c = 1;
        insert usrSet;
                              
                            
        
        Pagereference ref = Page.JEOL_QuotationEditorPage;
        Map<String, String> params = new Map<String, String>();

        ref.getParameters().putAll(params);
                               
        Test.setCurrentPage(ref);
               
        JEOL_QuotationEditorPageCtrl ctrl = new JEOL_QuotationEditorPageCtrl();
        
    }

    private static testMethod void test04() {
        
        Account acc = new Account();
        acc.Name = 'acc';
        acc.Code__c = '12345';
        insert acc;
        
        Contact con = new contact();
        con.account = acc;
        con.accountid = acc.id;
        con.LastName = 'dummy';
        insert con;
        
        QuotationInformation__c quot = new QuotationInformation__c();
        quot.UnitBody__c = '1234';
        quot.ShipmentCode__c = '12345';
        quot.SalesAreaCode__c = '01';
        quot.DepartmentCode__c = '01';
        quot.OverrideDepartmentCode__c = '01';
        quot.ContractContact_dummyField__c = con.id;
        quot.ShipmentContact_dummyField__c = con.id;
        quot.ContractAccount__c = acc.id;
        quot.ShipmentAccount__c = acc.id;
        insert quot;

        ProductItem__c pi = new ProductItem__c();
        insert pi;
        
        UnitBody__c ub = new UnitBody__c();
        ub.UnitBody__c = '1234';
        ub.AcceptanceDate__c = Datetime.Now();
        ub.ItemLink__c = pi.id;
        ub.DeliveryAccount__c = acc.id;
        insert ub;
               
        QuotationDetailInformation__c quotdet = new QuotationDetailInformation__c();
        quotdet.Parent__r = quot;
        quotdet.Parent__c = quot.id;
        quotdet.Depth__c = 1;
        quotdet.SortNo__c = 0;
        quotdet.IsDiscountTarget__c = true;
        quotdet.DiscountRate__c = 10;
        quotdet.DiscountAmount__c = 10;
        insert quotdet;

        Pagereference ref = Page.JEOL_QuotationEditorPage;
        Map<String, String> params = new Map<String, String>();
        params.put('id', quot.id);
        
        ref.getParameters().putAll(params);
                               
        Test.setCurrentPage(ref);
               
        JEOL_QuotationEditorPageCtrl ctrl = new JEOL_QuotationEditorPageCtrl();
        
        ctrl.acceptanceDateCalc();

        List<SelectOption> ret1 = ctrl.getCandidateUnitBody();
        
        ctrl.salesAreaAttachment();
        ctrl.departmentInfoAttachment();
        ctrl.overDepartmentInfoAttachment();
        ctrl.contractContactAttachment();
        ctrl.shipmentContactAttachment();
        
        ctrl.listRowToDel = '123,456';
        ctrl.deleteMultiRows();

        List<String> ret2 = JEOL_QuotationEditorPageCtrl.getSuggestions('dummy');
        Pagereference ret3 = ctrl.getPreviewUrl();
        Pagereference ret4 = ctrl.getDestinationPreviewUrl();
        Pagereference ret5 = ctrl.getCertificationPreviewUrl();
        ctrl.UserSettingSave();
    }
    
}