objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ProductItem__c.object
<CustomObject>
    <fields>
        <fullName>JapaneseName__c</fullName>
        <label>品目名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>OrderAmount__c</fullName>
        <label>オーダ額</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (販売先取引先)</relationshipLabel>
        <relationshipName>SalesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SerialNoItemLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>シリアル番号付品目</label>
        <referenceTo>SerialNoProductItem__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SerialNoItemLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列（装置）</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (出荷先取引先)</relationshipLabel>
        <relationshipName>ShipmentAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesOrderLine__c.object
<CustomObject>
    <fields>
        <fullName>ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>販売オーダライン</relationshipLabel>
        <relationshipName>SalesOrderLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrderLink__c</fullName>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>販売オーダライン</relationshipLabel>
        <relationshipName>SalesOrderLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>販売オーダライン</label>
    <nameField>
        <label>販売オーダ</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SerialNoProductItem__c.object
<CustomObject>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目リンク</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>シリアル番号付品目</relationshipLabel>
        <relationshipName>ItemRelation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SalesTargetCustomer__c</fullName>
        <label>販売先取引先コード</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <externalId>true</externalId>
        <label>シリアル番号_連携用</label>
        <length>78</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>シリアル番号付品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceOrder__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>顧客対応票</label>
        <referenceTo>Support__c</referenceTo>
        <relationshipLabel>サービスオーダ</relationshipLabel>
        <relationshipName>ServiceOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductItem__c</fullName>
        <formula>Customer__r.UnitBodyLink__r.ItemLink__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>品目</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>サービスオ販売先取引先ーダ ()</relationshipLabel>
        <relationshipName>ServiceOrders_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>サービスオーダ</relationshipLabel>
        <relationshipName>ServiceOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>サービスオーダ</label>
    <nameField>
        <label>サービスオーダ</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ServiceOrderControl__c.object
<CustomObject>
    <fields>
        <fullName>ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>サービスオーダ材料費</relationshipLabel>
        <relationshipName>ServiceOrderControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceOrder__c</fullName>
        <label>サービスオーダ</label>
        <referenceTo>ServiceOrder__c</referenceTo>
        <relationshipLabel>サービスオーダ材料費</relationshipLabel>
        <relationshipName>ServiceOrderControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>サービスオーダ材料費</label>
    <nameField>
        <label>サービスオーダ材料費名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support__c.object
<CustomObject>
    <fields>
        <fullName>SerialNoItemsLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>シリアル番号付品目</label>
        <referenceTo>SerialNoProductItem__c</referenceTo>
        <relationshipLabel>顧客対応票</relationshipLabel>
        <relationshipName>SerialNoItems2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>顧客対応票</label>
    <nameField>
        <label>コールセンター受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>ItemLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>本体号機 (販売先取引先)</relationshipLabel>
        <relationshipName>Sales_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <label>シリアル番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <formula>ItemLink__r.Series__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>系列</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_JuchuOrderViewTest.cls
@IsTest
private class JEOL_JuchuOrderViewTest {

    // ID指定なし
    private static testMethod void test01() {

        PageReference testPage = Page.JEOL_JuchuOrderView;
//        testPage.getParameters().put('Id', '');
        Test.setCurrentPage(testPage);

        JEOL_JuchuOrderView ctrl = new JEOL_JuchuOrderView();
    }

    // 検索該当なし
    private static testMethod void test02() {

        PageReference testPage = Page.JEOL_JuchuOrderView;
        testPage.getParameters().put('Id', 'test');
        Test.setCurrentPage(testPage);

        JEOL_JuchuOrderView ctrl = new JEOL_JuchuOrderView();
    }

    // 検索該当あり（販売）
    private static testMethod void test03() {

        String tgtId = testDataSales();

        PageReference testPage = Page.JEOL_JuchuOrderView;
        testPage.getParameters().put('Id', tgtId);
        Test.setCurrentPage(testPage);

        JEOL_JuchuOrderView ctrl = new JEOL_JuchuOrderView();
        JEOL_JuchuOrderView.ViewWrapper tgt = ctrl.target;

        // 値取得処理呼び出し
        tgt.getIsSales();
        tgt.getIsService();
        tgt.getOrderNo();
        tgt.getOrderDate();
        tgt.getCarryDeliveryTime();
        tgt.getSalesStaff();
        tgt.getProductNumber();
        tgt.getOrdersMemp();
        tgt.getOrderAmount();
        tgt.getTaxAmount();
        tgt.getCurrencyIsoCode();
        tgt.getSumAmount();
        tgt.getSalesContactPosition();
        tgt.getSalesTantoshya();
        tgt.getSalesContactTel();
        tgt.getShipmentContactPosition();
        tgt.getShipmentTantosha();
        tgt.getShipmentContactTel();
        tgt.getCustomerOrderNo();
        tgt.getCallCenterReceptionNo();
        tgt.getSchedulingDivision();
        tgt.getKosohin();
        tgt.getBillingSystem();
        tgt.getPaperDivision();
        tgt.getQuotation();
        tgt.getInvoice();
        tgt.getBill();
        tgt.getModelPI();
        tgt.getUnitBody();
        tgt.getSalesAccount();
        tgt.getShipmentAccount();
        tgt.getLines();
    }

    // 検索該当あり（サービス）
    private static testMethod void test04() {

        String tgtId = testDataService();

        PageReference testPage = Page.JEOL_JuchuOrderView;
        testPage.getParameters().put('Id', tgtId);
        Test.setCurrentPage(testPage);

        JEOL_JuchuOrderView ctrl = new JEOL_JuchuOrderView();
        JEOL_JuchuOrderView.ViewWrapper tgt = ctrl.target;

        // 値取得処理呼び出し
        tgt.getIsSales();
        tgt.getIsService();
        tgt.getOrderNo();
        tgt.getOrderDate();
        tgt.getCarryDeliveryTime();
        tgt.getSalesStaff();
        tgt.getProductNumber();
        tgt.getOrdersMemp();
        tgt.getOrderAmount();
        tgt.getTaxAmount();
        tgt.getCurrencyIsoCode();
        tgt.getSumAmount();
        tgt.getSalesContactPosition();
        tgt.getSalesTantoshya();
        tgt.getSalesContactTel();
        tgt.getShipmentContactPosition();
        tgt.getShipmentTantosha();
        tgt.getShipmentContactTel();
        tgt.getCustomerOrderNo();
        tgt.getCallCenterReceptionNo();
        tgt.getSchedulingDivision();
        tgt.getKosohin();
        tgt.getBillingSystem();
        tgt.getPaperDivision();
        tgt.getQuotation();
        tgt.getInvoice();
        tgt.getBill();
        tgt.getModelPI();
        tgt.getUnitBody();
        tgt.getSalesAccount();
        tgt.getShipmentAccount();
        tgt.getLines();
    }

    // テストデータ作成（販売）
    private static String testDataSales(){
        // 品目
        ProductItem__c pi = new ProductItem__c();
        pi.Name = 'testITEMname';
        pi.Series__c = 'testPI';
        pi.JapaneseName__c = 'testModelNamePI';
        insert pi;

        // シリアル番号付品目
        SerialNoProductItem__c snpi = new SerialNoProductItem__c();
        snpi.Name = 'testSNPIname';
        snpi.ItemLink__c = pi.Id;
        snpi.SerialNo__c = 'testSNo';
        snpi.UnitBody__c = 'testUnitBody';
        snpi.StatusOfUse__c = '1';
        snpi.SalesTargetCustomer__c = 'testCode';
        insert snpi;

        // 販売先取引先
        Account accSL = new Account();
        accSL.Name = 'testACNSL';
        accSL.Code__c = 'testACCSL';
        insert accSL;

        // 出荷先取引先
        Account accSP = new Account();
        accSP.Name = 'testACNSP';
        accSP.Code__c = 'testACCSP';
        insert accSP;

        // 販売オーダ
        SalesOrder__c so = new SalesOrder__c();
        so.Name = 'testSOname';
        so.OrderAmount__c = 10000000;
        so.SalesAccount__c = accSL.Id;
        so.ShipmentAccount__c = accSP.Id;
        so.SerialNoItemLink__c = snpi.Id;
        insert so;

        // 販売オーダライン
        SalesOrderLine__c sol = new SalesOrderLine__c();
        sol.Name = 'testSOLname';
        sol.SalesOrderLink__c = so.Id;
        sol.ProductItem__c = pi.Id;
        insert sol;

        return so.Id;
    }

    // テストデータ作成（サービス）
    private static String testDataService(){
        // 品目
        ProductItem__c pi = new ProductItem__c();
        pi.Name = 'testITEMname';
        pi.Series__c = 'testPI';
        pi.JapaneseName__c = 'testModelNamePI';
        insert pi;

        // シリアル番号付品目
        SerialNoProductItem__c snpi = new SerialNoProductItem__c();
        snpi.Name = 'testSNPIname';
        snpi.ItemLink__c = pi.Id;
        snpi.SerialNo__c = 'testSNo';
        snpi.UnitBody__c = 'testUnitBody';
        snpi.StatusOfUse__c = '1';
        snpi.SalesTargetCustomer__c = 'testCode';
        insert snpi;

        // 顧客対応票
        Support__c spt = new Support__c();
        spt.Name = 'testSPTname';
        spt.SerialNoItemsLink__c = snpi.Id;
        insert spt;

        // 販売先取引先
        Account accSL = new Account();
        accSL.Name = 'testACNSL';
        accSL.Code__c = 'testACCSL';
        insert accSL;

        // 出荷先取引先
        Account accSP = new Account();
        accSP.Name = 'testACNSP';
        accSP.Code__c = 'testACCSP';
        insert accSP;

        // サービスオーダ
        ServiceOrder__c so = new ServiceOrder__c();
        so.Name = 'testSOname';
        so.SalesAccount__c = accSL.Id;
        so.ShipmentAccount__c = accSP.Id;
        so.Customer__c = spt.Id;
        insert so;

        // サービスオーダ材料費
        ServiceOrderControl__c soc = new ServiceOrderControl__c();
        soc.Name = 'testSOLname';
        soc.ServiceOrder__c = so.Id;
        soc.ProductItem__c = pi.Id;
        insert soc;

        return so.Id;
    }

}