objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>住所</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>国</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DispatchTime__c</fullName>
        <label>派遣時間</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DistanceSection__c</fullName>
        <label>距離区分</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>郵便番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <label>サービスエリア名</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>都道府県</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Component__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDateFormula__c</fullName>
        <formula>Datevalue(AcceptanceDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>検収日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>構成品</relationshipLabel>
        <relationshipName>ItemLink_Component</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ModelAbbreviation__c</fullName>
        <label>機種略称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>構成品</relationshipLabel>
        <relationshipName>Component</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <label>シリアル番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingDateFormula__c</fullName>
        <formula>Datevalue(ShippingDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>出荷日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>構成品</relationshipLabel>
        <relationshipName>Component</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>構成品</label>
    <nameField>
        <label>構成品</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Affiliation__c</fullName>
        <label>所属</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DM__c</fullName>
        <label>DM送付除外</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extension__c</fullName>
        <label>内線</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HeadquartersSection__c</fullName>
        <label>所属（本部）</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TantoshaCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>担当者コード</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Model__c.object
<CustomObject>
    <description>デモレポート用機種マスタ</description>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>機種</label>
    <nameField>
        <label>形式</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductItem__c.object
<CustomObject>
    <fields>
        <fullName>EnglishName__c</fullName>
        <label>品目名（英名）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JapaneseName__c</fullName>
        <label>品目名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>機種</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>FlagshipProduct__c</fullName>
        <label>受注代表商品名</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaintenanceEndDateFormula__c</fullName>
        <formula>Datevalue(MaintenanceEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaintenanceStartDateFormula__c</fullName>
        <formula>Datevalue(MaintenanceStartDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaintenanceType__c</fullName>
        <label>保守種類</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <label>製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (販売先取引先)</relationshipLabel>
        <relationshipName>SalesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列（装置）</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBodyLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <recordTypes>
        <fullName>HosyuKeiyaku</fullName>
        <active>true</active>
        <label>保守契約詳細</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>AcceptanceDateFormula__c</fullName>
        <formula>Datevalue(AcceptanceDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>検収日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>窓口：１</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>本体号機 (窓口：１)</relationshipLabel>
        <relationshipName>Contact1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>窓口：２</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>本体号機 (窓口：２)</relationshipLabel>
        <relationshipName>Contact2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DeliveryAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>納入先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>本体号機 (納入先取引先)</relationshipLabel>
        <relationshipName>DeliveryAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EFEndDateFormula__c</fullName>
        <formula>Datevalue(EFEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EF終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EFProductNo__c</fullName>
        <label>EF製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>ItemLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ModelAbbreviation__c</fullName>
        <label>機種略称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>ItemLink__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>機種</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>本体号機 (販売先取引先)</relationshipLabel>
        <relationshipName>Sales_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <label>シリアル番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <formula>ItemLink__r.Series__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>系列</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingDateFormula__c</fullName>
        <formula>Datevalue(ShippingDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>出荷日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SpecialContractNote__c</fullName>
        <label>特別契約メモ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusOfUse__c</fullName>
        <label>使用状況</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SvcForm__c</fullName>
        <label>SVC形態</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_NonyusakiShokai_ctrl.cls
public with sharing class JEOL_NonyusakiShokai_ctrl extends JEOL_SearchBase_ctrl{

    // 検索条件
    public UnitBody__c targetRec {get; set;}
    public List<SalesOrder__c> ConservativeInfos{get; set;}
    
    /**
    * コンストラクタ
    */
    public JEOL_NonyusakiShokai_ctrl(Apexpages.Standardcontroller ctrl){
        try {
            
            String targetId = Apexpages.currentPage().getParameters().get('id');
            UnitBody__c targetRec = getTargetRecord(targetId);
            this.targetRec = targetRec;
            conservativeInfos = getConservativeInfos();
        } catch(Exception e) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, '不正な操作がありました。');
            ApexPages.addMessage(msg);
        }
    }
    
    public List<SalesOrder__c> getConservativeInfos() {
        String unitBody = this.targetRec.UnitBody__c;
        
        List<SalesOrder__c> children;
        if (String.isNotBlank(unitBody)) {
            String recordTypeId;
            for (RecordType rec: [select Id from RecordType where SobjectType = 'SalesOrder__c' and developerName = 'HosyuKeiyaku']) {
                recordTypeId = rec.id;
            }
            children = [SELECT id, FlagshipProduct__c, Name, ProductNumber__c, MaintenanceType__c
                        FROM SalesOrder__c
                        WHERE UnitBody__c = : unitBody
                        AND RecordTypeId =: recordTypeId
                        AND MaintenanceStartDateFormula__c <= TODAY
                        AND MaintenanceEndDateFormula__c >= TODAY
                        ORDER BY MaintenanceType__c ASC , MaintenanceStartDateFormula__c DESC
                        LIMIT 3];
        }
        if (children == null) {
            children = new List<SalesOrder__c>();
        }
        while (children.size() < 3) {
            children.add(new SalesOrder__c());
        }
        return children;
    }

    /**
    * メイン情報取得
    */
    private UnitBody__c getTargetRecord(String targetId) {
        UnitBody__c targetRec;
        List<UnitBody__c> recs = [
                SELECT
                    Id,
                    Name,
                    SerialNo__c,
                    UnitBody__c,
                    ItemLink__c,
                    ItemLink__r.JapaneseName__c,
                    ItemLink__r.EnglishName__c,
                    ModelAbbreviation__c,
                    Series__c,
                    ShippingDateFormula__c,
                    AcceptanceDateFormula__c,
                    StatusOfUse__c,
                    DeliveryAccount__r.Code__c,
                    DeliveryAccount__r.Name,
                    SalesAccount__r.Code__c,
                    SalesAccount__r.Name,
                    DeliveryAccount__r.ServiceArea__c,
                    DeliveryAccount__r.Country__c,
                    DeliveryAccount__r.DispatchTime__c,
                    DeliveryAccount__r.DistanceSection__c,
                    DeliveryAccount__r.PostalCode__c,
                    DeliveryAccount__r.Address__c,
                    SpecialContractNote__c,
                    SvcForm__c,
                    EfProductNo__c,
                    EFEndDateFormula__c,
                    Contact1__r.TantoshaCode__c,
                    Contact1__r.Name,
                    Contact1__r.HeadquartersSection__c,
                    Contact1__r.Affiliation__c,
                    Contact1__r.Phone,
                    Contact1__r.Extension__c,
                    Contact1__r.MobilePhone,
                    Contact1__r.Fax,
                    Contact1__r.Email,
                    Contact1__r.DM__c,
                    Contact2__r.TantoshaCode__c,
                    Contact2__r.Name,
                    Contact2__r.HeadquartersSection__c,
                    Contact2__r.Affiliation__c,
                    Contact2__r.Phone,
                    Contact2__r.Extension__c,
                    Contact2__r.MobilePhone,
                    Contact2__r.Fax,
                    Contact2__r.Email,
                    Contact2__r.DM__c,
                    DeliveryAccount__r.State__c,
                    (select id, name from SalesOrder__r)
                FROM
                    UnitBody__c
                WHERE
                    Id =: targetId
        ];
        for (UnitBody__c rec: recs) {
            targetRec = rec;
        }
        
        return targetRec;
    }

    public List<PartsItem> getPartsItems() {
        List<Component__c> partsItems;
        String parentId = this.targetRec.id;
        partsItems = [
            SELECT
                id,
                ItemLink__r.Name,
                ItemLink__r.JapaneseName__c,
                ItemLink__r.Model__c,
                ModelAbbreviation__c,
                SerialNo__c ,
                ShippingDateFormula__c,
                AcceptanceDateFormula__c
            FROM
                Component__c 
            WHERE
                UnitBody__c =: parentId
            ORDER BY
                SerialNo__c
        ];
        if (partsItems == null) {
            partsItems = new List<Component__c>(); 
        }
        List<PartsItem> items = new List<PartsItem>();
        for (Component__c rec: partsItems) {
            items.add(new PartsItem(rec));
        }
        return items;
    }
    
    public class PartsItem {
        public Component__c rec{get; set;}
        
        public PartsItem(Component__c rec) {
            this.rec = rec;
        }
        
        public String getModelText() {
            String ret;
            if (this.rec != null && this.rec.ItemLink__r != null) {
                String modelName = this.rec.ItemLink__r.Name;
                if (String.isNotBlank(ModelName) && (modelName == 'K999999' || modelName.startsWith('ZZ'))) {
                    ret = this.rec.ModelAbbreviation__c;
                } else {
                    ret = this.rec.ItemLink__r.Model__c;
                }
            }
            return ret;
        }
    }
}