objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>住所</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_MapViewCtrlTest.cls
@IsTest
private class JEOL_MapViewCtrlTest {

    private static testMethod void test01() {
        
        Account acc = new account();
        acc.Name = 'dummy';
        acc.Code__c = '12345';
        acc.Address__c = 'AAA市BBB区CCC町DDD村';
        insert acc;
       
        JEOL_MapViewCtrl ctrl = new JEOL_MapViewCtrl(new ApexPages.StandardController(acc));
      
        List<Account> lsAcc = ctrl.getNearAccounts();
        
        acc.Address__c = '';
        List<Account> lsAcc2 = ctrl.getNearAccounts();
        
    }

}