objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>取引先カテゴリコード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>取引先カテゴリ</label>
    <nameField>
        <label>取引先カテゴリ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CategoryJunction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>取引先カテゴリジャンクション</relationshipLabel>
        <relationshipName>AccJunctionLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CategoryName__c</fullName>
        <description>API参照名に注意</description>
        <label>取引先カテゴリコード</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>取引先カテゴリジャンクション</relationshipLabel>
        <relationshipName>JunctionLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>取引先カテゴリジャンクション</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>取引先カテゴリジャンクション</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Model__c.object
<CustomObject>
    <description>デモレポート用機種マスタ</description>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>機種</label>
    <nameField>
        <label>形式</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductItem__c.object
<CustomObject>
    <fields>
        <fullName>EnglishName__c</fullName>
        <label>品目名（英名）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GaibuID__c</fullName>
        <externalId>true</externalId>
        <label>品目（外部ID用）</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HalfTextName__c</fullName>
        <label>品名（半角）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HyozyunNoki__c</fullName>
        <label>標準納期</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JapaneseName__c</fullName>
        <label>品目名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Kikaku__c</fullName>
        <label>規格</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meka__c</fullName>
        <label>メーカー</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>機種</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShireSakiCode__c</fullName>
        <label>仕入先</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShiyoKishu__c</fullName>
        <label>使用機種</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShukkaStatusName__c</fullName>
        <label>仕入先名称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Soko__c</fullName>
        <label>倉庫</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tani__c</fullName>
        <label>単位</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZaikoKanriKubun__c</fullName>
        <label>在庫管理区分</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>Kikaku__c</fullName>
        <formula>UnitBodyLink__r.Standard__c</formula>
        <label>規格</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (販売先取引先)</relationshipLabel>
        <relationshipName>SalesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SerialNoItemLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>シリアル番号付品目</label>
        <referenceTo>SerialNoProductItem__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SerialNoItemLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列（装置）</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (出荷先取引先)</relationshipLabel>
        <relationshipName>ShipmentAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesResult__c.object
<CustomObject>
    <description>削除対象Object
※別売上Objectに変更</description>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>売上</relationshipLabel>
        <relationshipName>SalesResults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>hanbaisaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (販売先)</relationshipLabel>
        <relationshipName>aaaS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>seikyusaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>請求先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (請求先)</relationshipLabel>
        <relationshipName>cccS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>shukkasaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (出荷先)</relationshipLabel>
        <relationshipName>bbbS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>売上</label>
    <nameField>
        <label>売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SelectListManage__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>表示名称</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceName__c</fullName>
        <label>選択リスト参照名</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>ソート番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>値</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>選択リスト管理</label>
    <nameField>
        <label>選択リストグループ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SerialNoProductItem__c.object
<CustomObject>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目リンク</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>シリアル番号付品目</relationshipLabel>
        <relationshipName>ItemRelation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Kikaku__c</fullName>
        <formula>ItemLink__r.Kikaku__c</formula>
        <label>規格</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <externalId>true</externalId>
        <label>シリアル番号_連携用</label>
        <length>78</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>シリアル番号付品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_HanbaiList_ctrlTest.cls
@IsTest
private class JEOL_HanbaiList_ctrlTest {

    // Cookei用定数
    private static final String COOKIE_PATH = '/apex/JEOL_HanbaiListPage';
    private static final String COOKIE_LABEL_PAGE_NUMBER = 'PageNumber';
    private static final String COOKIE_LABEL_PAGE_SIZE = 'PageSize';
    private static final String COOKIE_LABEL_INIT_SEARCH_FLG = 'initSearchFlg';

    // コンストラクタ、各メソッド呼び出し、検索結果取得（クッキー系処理含む）
    private static testMethod void test01() {

        // テストデータ生成
        testData();

        PageReference testPage = Page.JEOL_HanbaiListPage;
        Test.setCurrentPage(testPage);

        // クッキー設定
        createCookies();

        JEOL_HanbaiList_ctrl ctrl = new JEOL_HanbaiList_ctrl();

        // 検索結果取得とページ制御系メソッド呼び出し
        ctrl.getSalesOrderList();
        ctrl.nextAndSaveCurrentPageNumber();
        ctrl.previousAndSaveCurrentPageNumber();
        ctrl.firstAndSaveCurrentPageNumber();
        ctrl.lastAndSaveCurrentPageNumber();
        ctrl.setJumpSaveCurrentPageSize();
        ctrl.setSizeSaveCurrentPageSize();

        // 各値取得用メソッド呼び出し
        ctrl.getRegionOptions();
        ctrl.getOrderTypeOptions();
        ctrl.getSeriesOptions();
        ctrl.getOrgUnitOptions();
        ctrl.getCCategoryOptions();

        // クリアメソッド呼び出し
        ctrl.doFormClear();

	    // 全パラメータ指定
        ctrl.kigyoTani = 'testTani';
        ctrl.eTantoCode = 'testETcd';
        ctrl.eTantoName = 'testETname';
        ctrl.hanbaisakiCode = 'testACSLcd';
        ctrl.hanbaisakiNameHan = 'testACSLnameHan';
        ctrl.hanbaisakiName = 'testACSLname';
        ctrl.shukkasakiCode = 'testACSPcd';
        ctrl.shukkasakiNameHan = 'testACSPnameHan';
        ctrl.shukkasakiName = 'testACSPname';
        ctrl.customerCategory = 'testCCcode';
        ctrl.orderType = 'testOtype';
        ctrl.keiretsu = 'testKiretsu';
        ctrl.tiki = 'testTiki';
        ctrl.shohinName = 'testSname';
        ctrl.goki = 'testGoky';
        ctrl.Search1();

	    // 取引先カテゴリ検索時'where'生成用
        ctrl.kigyoTani = '';
        ctrl.eTantoCode = '';
        ctrl.eTantoName = '';
        ctrl.hanbaisakiCode = '';
        ctrl.hanbaisakiNameHan = '';
        ctrl.hanbaisakiName = '';
        ctrl.shukkasakiCode = '';
        ctrl.shukkasakiNameHan = '';
        ctrl.shukkasakiName = '';
        ctrl.customerCategory = 'testCCcode';
        ctrl.orderType = '';
        ctrl.keiretsu = '';
        ctrl.tiki = '';
        ctrl.shohinName = '';
        ctrl.goki = '';
        ctrl.Search1();
    }

    // クッキー生成処理（画面起動時検索フラグON、一部条件指定）
    private static void createCookies(){
        List<Cookie> cookies = new List<Cookie>();
        cookies.add(new Cookie('kigyoTani', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('eTantoCode', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('eTantoName', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('hanbaisakiCode', 'testACCSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('hanbaisakiNameHan', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('hanbaisakiName', 'testACNSL', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('shukkasakiCode', 'testACCSP', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('shukkasakiNameHan', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('shukkasakiName', 'testACNSP', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('customerCategory', 'testCCcode', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('orderType', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('keiretsu', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('tiki', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('shohinName', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('goki', '', COOKIE_PATH, -1, true));
        cookies.add(new Cookie('isExcludePartsSupply', 'true', COOKIE_PATH, -1, true));
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_NUMBER, '1', COOKIE_PATH, -1, true));  // ページ番号
        cookies.add(new Cookie(COOKIE_LABEL_PAGE_SIZE, '10', COOKIE_PATH, -1, true));  // ページサイズ
        cookies.add(new Cookie(COOKIE_LABEL_INIT_SEARCH_FLG, 'true', COOKIE_PATH, -1, true));
        Apexpages.currentPage().setCookies(cookies);
    }

    // テストデータ作成
    private static void testData(){
        
        //品目
        ProductItem__c pItem = new ProductItem__c();
        pItem.name = 'SalsOrderTest';
        pItem.Meka__c = 'testMeka';
        pItem.Model__c = 'mTest';
        pItem.Kikaku__c = 'kTest';
        pItem.Series__c = 'NM';
        pItem.ZaikoKanriKubun__c = 'zTest';
        pItem.ShireSakiCode__c = 'ssc';
        pItem.ShukkaStatusName__c = 'ssnTestName';
        pItem.ShiyoKishu__c ='skTest';
        pItem.Soko__c = 'sTest';
        pItem.Tani__c = 'kg';
        pItem.HyozyunNoki__c = 9999.99;
        pItem.HalfTextName__c = 'ﾃｽﾄ';
        pItem.JapaneseName__c = 'テスト';
        pItem.EnglishName__c = 'test';
        pItem.GaibuID__c = 'T999999999';
        insert pItem;
        
        SerialNoProductItem__c snpItem = new SerialNoProductItem__c();
        snpItem.itemLink__c = pItem.id;
        snpItem.SerialNo__c = 'test' + pItem.id;
        insert snpItem;
        
        // 販売先取引先
        Account accSL = new Account();
        accSL.Name = 'testACNSL';
        accSL.Code__c = 'testACCSL';
        insert accSL;

        // 請求先取引先
        Account accSEL = new Account();
        accSEL.Name = 'testSEL';
        accSEL.Code__c = 'testSEL';
        insert accSEL;

        // 出荷先取引先
        Account accSP = new Account();
        accSP.Name = 'testACNSP';
        accSP.Code__c = 'testACCSP';
        insert accSP;

        // 販売オーダ
        SalesOrder__c so = new SalesOrder__c();
        so.SerialNoItemLink__c = snpItem.id;
        so.Name = 'testSOname';
        so.SalesAccount__c = accSL.Id;
        so.ShipmentAccount__c = accSP.Id;
        insert so;

        SalesResult__c res = new SalesResult__c();
        res.name = 'testResult';
        res.SalesOrder__c = so.id;
        res.shukkasaki__c = accSP.id;
        res.seikyusaki__c = accSEL.id;
        res.hanbaisaki__c = accSL.id;
        insert res;
        update so;
        update res;

        // 取引先カテゴリ
        Category__c cc = new Category__c();
        cc.Name = 'testCCname';
        cc.Code__c = 'testCCcode';
        insert cc;

        // 取引先カテゴリジャンクション
        CategoryJunction__c ccj = new CategoryJunction__c();
        ccj.CategoryName__c = cc.Id;
        ccj.Account__c = accSL.Id;  // 販売先取引先のほうを紐づけ
        insert ccj;

        SelectListManage__c slm = new SelectListManage__c();
        slm.name = 'オーダタイプ';
        slm.referenceName__c = JEOLUtil.REFERENCE_NAME_SALES_ORDER_TYPE;
        slm.value__c = 'testType';
        slm.label__c = 'testType';
        slm.sortNo__c = '1';
        insert slm;

        slm = new SelectListManage__c();
        slm.name = '企業単位';
        slm.referenceName__c = JEOLUtil.REFERENCE_NAME_ORG_UNIT;
        slm.value__c = 'j';
        slm.label__c = 'j';
        slm.sortNo__c = '1';
        insert slm;
    }

}