objects/Account.object
<CustomObject>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>郵便番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Undergraduate__c</fullName>
        <inlineHelpText>Undergraduate</inlineHelpText>
        <label>学部・事業所</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>AnnaiType__c</fullName>
        <label>案内種類</label>
        <picklist>
            <picklistValues>
                <fullName>1page</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2pages</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>JEOLContactPosition__c</fullName>
        <label>日本電子・連絡先（担当者所属）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JEOLContactTel__c</fullName>
        <label>日本電子・連絡先（電話番号等）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JEOLRegionName__c</fullName>
        <label>日本電子・連絡先（支店）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JEOLReplyContactFax__c</fullName>
        <label>日本電子・回答先（FAX等）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JEOLReplyContactPosition__c</fullName>
        <label>日本電子・回答先（担当者所属）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JEOLReplyRegionName__c</fullName>
        <label>日本電子・回答先（支店）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JeolPipelineResponsible2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>更新案内担当者2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MCM_JeolPipelineResponsible2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JeolPipelineResponsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>更新案内担当者</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MainPipeline_JeolResp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewContractAmount__c</fullName>
        <label>契約金額</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NewContractEndDate__c</fullName>
        <label>契約完了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewContractStartDate__c</fullName>
        <label>契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrRegion__c</fullName>
        <label>地域</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesContactFax__c</fullName>
        <label>販売先担当者FAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesContactPosition__c</fullName>
        <label>販売先担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesContactTel__c</fullName>
        <label>販売先担当者TEL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesTantoshya__c</fullName>
        <label>販売先担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreviousYearOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>前年オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipName>PreviousYearOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RenewalAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客先名</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RenewalAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RenewalAddress2__c</fullName>
        <label>住所2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalAddress__c</fullName>
        <label>住所</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalCompanyName__c</fullName>
        <label>送付先（会社名）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalContactPosition__c</fullName>
        <label>担当者所属</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalCustomerNameReply__c</fullName>
        <label>お客様名称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalDeliveryLocation__c</fullName>
        <label>納入場所</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalFooterComment__c</fullName>
        <label>フッターコメント</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RenewalItemsName__c</fullName>
        <label>保守契約機器</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalListOptions__c</fullName>
        <label>オプション</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RenewalOptionCustomerNameLabel__c</fullName>
        <label>お客様名/契約者様名</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RenewalOptionDateFormat__c</fullName>
        <label>西暦/和暦</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RenewalOptionHideChangeInfo__c</fullName>
        <defaultValue>true</defaultValue>
        <label>更新エリアを隠す</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenewalPostalCode__c</fullName>
        <label>郵便番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalPrintDate__c</fullName>
        <label>印刷日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RenewalQuotation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>更新案内見積書</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>QuotationInformation__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PCS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>QuotationInformation__c</referenceTo>
        <relationshipLabel>保守契約管理 (更新案内見積書)</relationshipLabel>
        <relationshipName>MCM_RenewalQuotation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RenewalTantoshya__c</fullName>
        <label>担当者名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalTopSectionText__c</fullName>
        <defaultValue>&quot;なお、ご契約手続きにつきましては、お手数ですが、年間保守契約継続依頼書に必要事項をご記入の上、&quot; + BR() + &quot;ＦＡＸまたは郵送にてご返送いただければ幸いと存じます。 　 　 　 　 　 　 　 　 　 　 　 　 　 　 　敬具&quot;</defaultValue>
        <label>トップセクション</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RenewalUndergraduate__c</fullName>
        <label>送付先（学部事業所）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>保守契約管理</relationshipLabel>
        <relationshipName>MaintPipeline_UnitBody</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QuotationInformation__c.object
<CustomObject>
    <fields>
        <fullName>BranchNo__c</fullName>
        <label>枝番</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>郵便番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteNo__c</fullName>
        <description>自社内管理の見積番号</description>
        <label>見積No.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>見積書情報</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>本体号機</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>見積書情報</label>
    <nameField>
        <label>見積名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>BranchNo__c</fullName>
        <formula>Quote__r.BranchNo__c</formula>
        <label>見積枝番</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumptionTax__c</fullName>
        <label>受注総額(消費税抜)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ItemName__c</fullName>
        <formula>UnitBodyLink__r.ItemLink__r.JapaneseName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>装置名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder_MaintenancePL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaintenanceEndDateFormula__c</fullName>
        <formula>Datevalue(MaintenanceEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaintenancePeriod__c</fullName>
        <formula>TEXT(MaintenanceEndDateFormula__c - MaintenanceStartDateFormula__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>契約期間</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaintenanceStartDateFormula__c</fullName>
        <formula>Datevalue(MaintenanceStartDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QuoteNo__c</fullName>
        <formula>Quote__r.Name</formula>
        <label>見積No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>ItemName__c</fullName>
        <formula>ItemLink__r.JapaneseName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>品目名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_MaintenanceAnnaiPrintPageCtrl.cls
/*
 * Created : 2015/10/06 by Polus (Voxer)
 */
public with sharing class JEOL_MaintenanceAnnaiPrintPageCtrl {
    
    public List<PageBlock> pdfPages{get; set;}
    public String outputType{get; set;}
    public String renderTarget{get; set;}
    //
    public MaintenanceContractManagement__c rec {get;set;}
    public SalesOrder__c prevSalesOrder {get; set;}
    public Account renewalAccount {get; set;}

    public String blankDate {get;set;}
    //
    
    public static final Integer MAX_LINE_SIZE_FIRST = 22;
    public static final Integer MAX_LINE_SIZE = 42;
    public static final Integer BASE_TEXT_LENGTH = 17;

    public JEOL_MaintenanceAnnaiPrintPageCtrl() {
        Map<String, String> params = Apexpages.currentPage().getParameters();
        String recId = params.get('id');
        outputType = 'print';
        if (params.containsKey('preview') && String.isNotBlank(params.get('preview'))) {
            outputType = 'preview';
        }
        if (params.containsKey('print') && String.isNotBlank(params.get('print'))) {
            outputType = 'print';
        }
        if (outputType == 'print') {
            renderTarget = 'pdf';
        }
        rec = getTargetRecord(recId);
        prevSalesOrder = getPrevYearSalesOrder(rec);
        renewalAccount = getRenewalAccountForRec(rec);
        this.pdfPages = createPdfPages(rec);
        blankDate = '平成 　年 　月　　日';
    }

    private Account getRenewalAccountForRec(MaintenanceContractManagement__c targetRec){
        List<Account> ras = [
                SELECT
                        Id, Name, PostalCode__c, Undergraduate__c
                        FROM
                                Account
                        WHERE
                                Id =: targetRec.RenewalAccount__c
                ];

                if(ras.size() == 1){
                        system.debug('ras[0]: ' + ras[0]);
                        return ras[0];
                }
                else
                        return null;
    }

      private SalesOrder__c getPrevYearSalesOrder(MaintenanceContractManagement__c targetRec){
                List<SalesOrder__c> sos = [
                        SELECT 
                                Id, Name, ItemName__c, MaintenanceStartDateFormula__c, MaintenanceEndDateFormula__c, 
                                MaintenancePeriod__c,ConsumptionTax__c, UnitBody__c
                        FROM 
                                SalesOrder__c 
                        WHERE 
                                Id =: targetRec.PreviousYearOrder__c
                ];

        if(sos.size() == 1)
            return sos[0];
        else return null;
    }
    
    private List<PageBlock> createPdfPages(MaintenanceContractManagement__c targetRec) {
    
        integer iCurrentPageNo = 1;
        List<PageBlock> pdfPages = new List<PageBlock>();

        PageBlock headerPage = new PageBlock();
        headerPage.isFirst = true;
        QuotationHeader head = new QuotationHeader(targetRec);
        headerPage.setHead(head);

        Integer totalLineSize = 0;
        PageBlock page = headerPage;
        totalLineSize += page.getQuotatinNameLinesSize();
        pdfPages.add(page);
        
        // Section with line items
        Integer lineBodySize = BASE_TEXT_LENGTH;
        Integer countLineSize = 0;
                
        System.debug('pdfPages: ' + pdfPages);
        return pdfPages;
    }
    
    private MaintenanceContractManagement__c getTargetRecord(String targetId) {
        MaintenanceContractManagement__c targetaRecord = null;
        List< MaintenanceContractManagement__c > recs = [
            SELECT
                id, name, CurrencyIsoCode, LastModifiedDate, CreatedDate, PreviousYearOrder__c, RenewalAccount__c, UnitBody__c, RenewalPrintDate__c,
                NewContractStartDate__c, NewContractEndDate__c, NewContractAmount__c, RenewalTantoshya__c, JEOLContactTel__c, 
                JEOLReplyContactFax__c, NewOdrRegion__c,NewOdrSalesTantoshya__c,NewOdrSalesContactPosition__c,NewOdrSalesContactTel__c,
                NewOdrSalesContactFax__c, UnitBody__r.UnitBody__c,
                JeolPipelineResponsible__c,JeolPipelineResponsible__r.Name, JeolPipelineResponsible__r.Phone, JeolPipelineResponsible__r.Fax,JeolPipelineResponsible__r.Email,
                JeolPipelineResponsible2__c, JeolPipelineResponsible2__r.Name, JeolPipelineResponsible2__r.Phone, JeolPipelineResponsible2__r.Fax, JeolPipelineResponsible2__r.Email,
                RenewalAddress__c, RenewalAddress2__c,RenewalPostalCode__c,
                JEOLRegionName__c,JEOLContactPosition__c,JEOLReplyRegionName__c,JEOLReplyContactPosition__c, RenewalContactPosition__c, RenewalQuotation__r.QuoteNo__c, RenewalQuotation__r.BranchNo__c,
                RenewalOptionDateFormat__c, RenewalCompanyName__c, RenewalUndergraduate__c,RenewalTopSectionText__c,RenewalDeliveryLocation__c,
                RenewalItemsName__c, JeolPipelineResponsible__r.LastName, JeolPipelineResponsible2__r.LastName, RenewalOptionCustomerNameLabel__c,
                RenewalCustomerNameReply__c,RenewalFooterComment__c,RenewalListOptions__c,RenewalOptionHideChangeInfo__c,AnnaiType__c
            FROM
                MaintenanceContractManagement__c
            WHERE
                Id =: targetId
        ];
        if (recs != null && recs.size() > 0) {
            targetaRecord = recs.get(0);
            
        } else {
            throw new JEOLException('不正な操作が行われました。');
        }
        return targetaRecord;
    }


    public class PageBlock {
        public Boolean isFirst{get; set;}
        public Boolean isLast{get; set;}
        public Boolean isShowTotal{get; set;}
        public Boolean isAccompanyingPaper{get; set;}
        public Boolean isShowNote{get; set;}
        public Boolean isShowNoteLabel{get; set;}
        public QuotationHeader head{get; set;}
        public List<String> quotatinNameLines{get; set;}
        public List<String> noteTextLines{get; set;}
        public Integer pageNo{get; set;}
        
        public PageBlock() {
            this.isFirst = false;
            this.isLast = false;
            this.isShowTotal = false;
            this.isAccompanyingPaper = false;
            this.isShowNote = false;
            this.isShowNoteLabel = false;
            this.head = null;
            this.pageNo = 1;
        }
        public void setHead(QuotationHeader head) {
            this.head = head;
            this.noteTextLines = head.noteTextLines;
            this.quotatinNameLines = head.quotatinNameLines;
        }
        public Integer getNoteTextLineSize() {
            return this.noteTextLines.size();
        }
        public Integer getQuotatinNameLinesSize() {
            return this.quotatinNameLines.size();
        }
        public Boolean getHasNoteText() {
            return (this.noteTextLines != NULL && this.noteTextLines.size() > 0);
        }

    }
    public class QuotationHeader {
        Public String CompanyAddress{get; set;}
        public MaintenanceContractManagement__c rec{get; set;}
        public List<String> quotatinNameLines{get; set;}
        public List<String> noteTextLines{get; set;}
        public List<String> otherTextLines{get; set;}
        
        public QuotationHeader(MaintenanceContractManagement__c quotation) {
            this.rec = quotation;
            
                // Just create a data with 1 line and a dummy data
                this.quotatinNameLines =  new List<String>();
                this.quotatinNameLines.add('DUMMY');
            
            this.CompanyAddress = '';   
        }
    }


    public Integer getPageSize() {
        Integer pageSize = 0;
        if (this.pdfPages != null) {
            pageSize = this.pdfPages.size();
        }
        return pageSize;
    }

    public String getPrintDate() {
        String returnDate = '';
        returnDate = this.getDateFormat(rec.RenewalPrintDate__c, rec.RenewalOptionDateFormat__c == null || rec.RenewalOptionDateFormat__c != '2', false);
        return returnDate;
    }

    public String getNewContractStartDate() {
        String returnDate = '';
        if (rec.NewContractStartDate__c != null) {
            returnDate = this.getDateFormat(rec.NewContractStartDate__c, rec.RenewalOptionDateFormat__c == null || rec.RenewalOptionDateFormat__c != '2', false);
        }
        return returnDate;
    }

    public String getNewContractEndDate() {
        String returnDate = '';
        if (rec.NewContractEndDate__c != null) {
            returnDate = this.getDateFormat(rec.NewContractEndDate__c, rec.RenewalOptionDateFormat__c == null || rec.RenewalOptionDateFormat__c != '2', false);
        }
        return returnDate;
    }

    public String getMaintenanceStartDateFormula() {
        String returnDate = '';
        if (prevSalesOrder.MaintenanceStartDateFormula__c != null) {
            returnDate = this.getDateFormat(prevSalesOrder.MaintenanceStartDateFormula__c, rec.RenewalOptionDateFormat__c == null || rec.RenewalOptionDateFormat__c != '2', false);
        }
        return returnDate;
    }

    public String getMaintenanceEndDateFormula() {
        String returnDate = '';
        if (prevSalesOrder.MaintenanceEndDateFormula__c != null) {
            returnDate = this.getDateFormat(prevSalesOrder.MaintenanceEndDateFormula__c, rec.RenewalOptionDateFormat__c == null || rec.RenewalOptionDateFormat__c != '2', false);
        }
        return returnDate;
    }

    private String getDateFormat(Date value, boolean isJapaneseEraOutput, boolean addSpace) {

        String year = '　　';
        String month = '　　';
        String day = '　　';

        if (value != NULL) {
            if (isJapaneseEraOutput) {
                Map<String, String> eraData = JEOLUtil.getJapaneseEraData(value);
                if (eraData.containsKey('name') && eraData.containsKey('year')) {
                    year = eraData.get('name') + (addSpace ? '　' : ' ') + eraData.get('year');
                } else {
                    year = String.valueOf(value.year());
                }
            } else {
                year = String.valueOf(value.year());
            }
            month = String.valueOf(value.month());
            if (month.length() < 2) {
                month = ' ' + month;
            }
            day = String.valueOf(value.day());
            if (day.length() < 2) {
                day = ' ' + day;
            }            
        }

        if (UserInfo.getLanguage() != 'ja') {
            return year + (addSpace ? ' ' : '') + '/' + (addSpace ? ' ' : '') + month + (addSpace ? ' ' : '') + '/' + (addSpace ? ' ' : '') + day;
        } else {
            return year + '年' + (addSpace ? '　' : '') + month + '月' + (addSpace ? '　' : '') + day + '日';
        }
    }

}