objects/Account.object
<CustomObject>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>住所（1）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine2__c</fullName>
        <label>住所（2）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine3__c</fullName>
        <label>住所（3）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>地域</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>郵便番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>住所（1）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine2__c</fullName>
        <label>住所（2）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine3__c</fullName>
        <label>住所（3）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DepartmentCode__c</fullName>
        <externalId>true</externalId>
        <label>部署コード</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>電話番号</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>郵便番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <description>Used to set the order of display</description>
        <label>ソート番号</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SupervisorName__c</fullName>
        <label>責任者氏名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupervisorPosition__c</fullName>
        <label>責任者役職</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>部署</label>
    <nameField>
        <label>部署名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>BillingMethodHelium__c</fullName>
        <label>請求方法（ヘリウム）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingMethodHontai__c</fullName>
        <label>請求方法（本体）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewContractAmount__c</fullName>
        <label>契約金額</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NewOdrDepartment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オフィス</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>保守契約管理</relationshipLabel>
        <relationshipName>MDM_Department</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrMaintenanceEndDate__c</fullName>
        <label>保守契約終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrMaintenanceStartDate__c</fullName>
        <label>保守契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrNetMaintenance__c</fullName>
        <label>NET保守区分</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrRegion__c</fullName>
        <label>地域</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.SalesAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.SalesAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (販売先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>系列</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ShipmentAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ShipmentAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (出荷先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuotationSentDate__c</fullName>
        <label>見積書送付日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RenewalAddress__c</fullName>
        <label>住所</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubAmountHelium__c</fullName>
        <label>台帳金額（ヘリウム）</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubAmountHontaiNoInspec__c</fullName>
        <label>台帳金額（本体、点検無し）</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>保守契約管理</relationshipLabel>
        <relationshipName>MaintPipeline_UnitBody</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MaintenanceMultipleAnnai__c.object
<CustomObject>
    <fields>
        <fullName>ListIdLong__c</fullName>
        <description>For more than 255 characters</description>
        <label>ListIdLong</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ListId__c</fullName>
        <label>ListId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <label>UnitBody</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>MaintenanceMultipleAnnai</label>
    <nameField>
        <label>MaintenanceMultipleAnnai Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>地域</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssistantCode__c</fullName>
        <label>アシスタントコード</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumptionTax__c</fullName>
        <label>受注総額(消費税抜)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder_MaintenancePL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaintenanceEndDate__c</fullName>
        <label>保守契約終了日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MaintenanceStartDate__c</fullName>
        <label>保守契約開始日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SalesOffice__c</fullName>
        <label>販売オフィス</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesStaffCode__c</fullName>
        <label>営業担当コード</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UpdateStatus__c</fullName>
        <label>契約更新状況</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <recordTypes>
        <fullName>SalesOrder</fullName>
        <active>true</active>
        <label>販売オーダ</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>ItemLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_MaintenanceMultipleAnnai_ctrlTest.cls
@isTest
private class JEOL_MaintenanceMultipleAnnai_ctrlTest {
    private static Date startDate = Date.newInstance(2015, 5, 1);
    private static Date endDate = Date.newInstance(2015, 5, 30);
    //User(ユーザ)
    private static User testUser = JEOL_TestDataFactory.createTestUser();
    //Account(取引先)
    private static Account testAccount = JEOL_TestDataFactory.createAccountTestObject('TestAccountName01', '000000001', false, '有効', false, '有効');
    /*
     * Description: Test Constructor(コンストラクターテスト)
     * MethodName : JEOL_MaintenanceMultipleAnnai_ctrl_Test01
     */
    private static testMethod void JEOL_MaintenanceMultipleAnnai_ctrl_Test01() {
        System.runAs (testUser) {
            // Preparation
            // MaintenanceContractManagement(保守契約管理)
            // exist LastYear
            Boolean existLastYear = true;
            List<MaintenanceContractManagement__c> mcmList = createTestData01(startDate, endDate,existLastYear);
            List<Id> mcmIdList = new List<Id>();
            for(MaintenanceContractManagement__c mcm :mcmList){
                mcmIdList.add(mcm.Id);
            }
            // Set Page
            PageReference testPage = Page.JEOL_MaintenanceMultipleAnnai;
            Test.setCurrentPage(testPage);
            Apexpages.currentpage().getparameters().put('Id', String.join(mcmIdList, ','));
            MaintenanceMultipleAnnai__c mma = createMMATestData(String.join(mcmIdList, ','));
            //Test Start
            Test.startTest();
            JEOL_MaintenanceMultipleAnnai_ctrl ctrl = new JEOL_MaintenanceMultipleAnnai_ctrl();
            ctrl.MultipleAnnaiSummary = mma;
            ctrl.indiceOption = 1;
            ctrl.getIsPrintForbidden();
            ctrl.getSalesPipelines();
            ctrl.PrintSogoAnnai1();
            ctrl.PrintSogoAnnai2();
            ctrl.getHidePicklistAnnai();
            ctrl.changeOrder2();
            ctrl.getNbOption();
            ctrl.lsOptions = JEOL_TestDataFactory.createMAOTestData('契約書を作成する', false, true, 3);
            ctrl.optionMoveUp();
            ctrl.indiceOption = 0;
            ctrl.optionMoveDown();
            //Test Stop
            Test.stopTest();
        }
    }

    /*
     * Description: Test Constructor(コンストラクターテスト)
     * MethodName : JEOL_MaintenanceMultipleAnnai_ctrl_Test02
     */
    private static testMethod void JEOL_MaintenanceMultipleAnnai_ctrl_Test02() {
        System.runAs (testUser) {
            // Preparation
            // MaintenanceContractManagement(保守契約管理)
            // exist LastYear
            Boolean existLastYear = true;
            List<MaintenanceContractManagement__c> mcmList = createTestData01(startDate, endDate,existLastYear);
            List<Id> mcmIdList = new List<Id>();
            for(MaintenanceContractManagement__c mcm :mcmList){
                mcmIdList.add(mcm.Id);
            }
            // Set Page
            PageReference testPage = Page.JEOL_MaintenanceMultipleAnnai;
            Test.setCurrentPage(testPage);
            Apexpages.currentpage().getparameters().put('Id', String.join(mcmIdList, ','));
            //Test Start
            Test.startTest();
            JEOL_MaintenanceMultipleAnnai_ctrl ctrl = new JEOL_MaintenanceMultipleAnnai_ctrl();
            //Test Stop
            Test.stopTest();
        }
    }

    /*
     * Description: Create MaintenanceMultipleAnnai TestData
     * MethodName : createMMATestData
     * @ return maintenanceMultipleAnnai
     */
    private static MaintenanceMultipleAnnai__c createMMATestData(String urlParam){
        MaintenanceMultipleAnnai__c maintenanceMultipleAnnai = new MaintenanceMultipleAnnai__c();
        maintenanceMultipleAnnai.Name = '東京';
        maintenanceMultipleAnnai.ListId__c = urlParam;
        maintenanceMultipleAnnai.ListIdLong__c = urlParam;

        insert maintenanceMultipleAnnai;
        return maintenanceMultipleAnnai;
    }

    /*
     * Description: Create SalesOrder TestData(部署テストデータ作成)
     * MethodName : createSalesOrderTestData
     * @ return SalesOrder(販売オーダ)
     */
    private static SalesOrder__c createSalesOrderTestData(){
        // SalesOrder (販売オーダ)
        RecordType salesOrderRecType = JEOL_TestDataFactory.getRecordType('SalesOrder__c');
        //SalesOrder
        SalesOrder__c salesOrder = new SalesOrder__c();
        salesOrder.RecordTypeId = salesOrderRecType.Id;
        salesOrder.Name = 'TestSalesOrderNo.0001';
        salesOrder.MaintenanceStartDate__c = Datetime.newInstance(2015,5,1,5,30,30);
        salesOrder.MaintenanceEndDate__c = Datetime.newInstance(2015,5,30,5,30,30);
        salesOrder.UpdateStatus__c = '契約中';
        salesOrder.Area__c = '東京';
        salesOrder.SalesStaffCode__c = 'S00000001';
        salesOrder.AssistantCode__c = 'A00000001';
        salesOrder.SalesOffice__c = '東京';
        salesOrder.ConsumptionTax__c = 1000;
        insert salesOrder;
        return salesOrder;
    }

    /*
     * Description: Create Department TestData(部署テストデータ作成)
     * MethodName : createDepartmentTestData
     * @ return Department(部署)
     */
    private static Department__c createDepartmentTestData(){
        Department__c department = new Department__c();
        department.Name = '東京';
        department.DepartmentCode__c = 'S0101';
        department.AddressLine1__c = '東京都千代田区大手町2-1-1';
        department.AddressLine2__c = '大手町野村ビル';
        department.AddressLine3__c = '住所3';
        department.SupervisorName__c = 'テスト名前 苗字';
        department.SupervisorPosition__c = '支店長';
        department.Phone__c = '00-1234-5678';
        department.PostalCode__c = '000-0001';
        department.SortNo__c = 1;
        insert department;
        return department;
    }

    /*
     * Description:Create UnitBody TestData(本体号機テストデータ作成)
     * MethodName :createUnitBodyTestData
     * @ return 本体号機
     */
    private static UnitBody__c createUnitBodyTestData(){
        // ProductItem(品目)
        ProductItem__c productItme = createProductItemTestData();
        // UnitBody(本体号機)
        UnitBody__c unitBody = new UnitBody__c();
        unitBody.Name = '本体号機テスト名';
        unitBody.ItemLink__c = productItme.Id;
        insert unitBody;
        return unitBody;
    }

    /*
     * Description:Create ProductItem TestData(品目テストデータ作成)
     * MethodName :createProductItemTestData
     * @ return 品目
     */
    private static ProductItem__c createProductItemTestData(){
        // ProductItem(品目)
        ProductItem__c productItme = new ProductItem__c();
        productItme.Name = 'テスト品目名';
        insert productItme;
        return productItme;
    }

    /*
     * Description: Create MaintenanceContractManagement TestData(保守契約管理テストデータ作成)
     * MethodName : createTestData01
     * @ parameter Date startDay (保守契約管理.保守契約開始日)
     * @ parameter Date endDay (保守契約管理.保守契約終了日)
     * @ parameter Boolean existLastYear (true:前年保守契約管理あり)
     * @ return MaintenanceContractManagementList(保守契約管理リスト)
     */
    private static List<MaintenanceContractManagement__c> createTestData01(Date startDay, Date endDay, Boolean existLastYear){
        // Department(部署)
        Department__c testDepartment = createDepartmentTestData();
        // UnitBody(本体号機)
        UnitBody__c testUnitBody = createUnitBodyTestData();
        // SalesOrder
        SalesOrder__c salesOrder = createSalesOrderTestData();
        // LastYear MaintenanceContractManagement (前年保守契約管理)
        // lastYearStartDate and lastYearEndDate
        Date lastYearStartDate = Date.newInstance(startDay.year() - 1, 5, 1);
        Date lastYearEndDate = Date.newInstance(startDay.year() - 1, 5, 30);
        MaintenanceContractManagement__c lastYearMcm = new MaintenanceContractManagement__c();
        if(existLastYear){
            lastYearMcm.NewOdrSalesAccount__c = testAccount.Id;
            lastYearMcm.NewOdrShipmentAccount__c = testAccount.Id;
            lastYearMcm.NewOdrSalesStaff__c = testUser.Id;
            lastYearMcm.NewOdrNetMaintenance__c = 'No';
            lastYearMcm.NewOdrSeries__c = 'CA';
            lastYearMcm.NewOdrRegion__c = '東京支店';
            lastYearMcm.QuotationSentDate__c = lastYearStartDate;
            lastYearMcm.NewOdrMaintenanceStartDate__c = lastYearStartDate;
            lastYearMcm.NewOdrMaintenanceEndDate__c = lastYearEndDate;
            lastYearMcm.BillingMethodHontai__c = '請求方法';
            lastYearMcm.BillingMethodHelium__c = '請求方法';
            lastYearMcm.SubAmountHontaiNoInspec__c = 3000;
            lastYearMcm.SubAmountHelium__c = 2000;
            lastYearMcm.NewOdrDepartment__c = testDepartment.Id;
            lastYearMcm.UnitBody__c = testUnitBody.Id;
            insert lastYearMcm;
        }
        //MaintenanceContractManagement(保守契約管理レコード作成)
        List<MaintenanceContractManagement__c> mcmList = new List<MaintenanceContractManagement__c>();
        for(Integer i = 1; i < 3; i++){
            MaintenanceContractManagement__c mcm = new MaintenanceContractManagement__c();
            mcm.NewOdrSalesAccount__c = testAccount.Id;
            mcm.NewOdrShipmentAccount__c = testAccount.Id;
            mcm.NewOdrSalesStaff__c = testUser.Id;
            mcm.NewOdrNetMaintenance__c = 'No';
            mcm.NewOdrSeries__c = 'CA';
            mcm.NewOdrRegion__c = '東京支店';
            mcm.QuotationSentDate__c = startDay;
            mcm.NewOdrMaintenanceStartDate__c = startDay;
            mcm.NewOdrMaintenanceEndDate__c = endDay;
            mcm.BillingMethodHontai__c = '請求方法';
            mcm.BillingMethodHelium__c = '請求方法';
            mcm.SubAmountHontaiNoInspec__c = 3000;
            mcm.SubAmountHelium__c = 2000;
            mcm.NewOdrDepartment__c = testDepartment.Id;
            mcm.UnitBody__c = testUnitBody.Id;
            mcm.NewContractAmount__c = 100000;
            mcm.RenewalAddress__c = '住所';
            mcm.RenewalCompanyName__c = '送付先会社名';
            mcm.RenewalTantoshya__c = '担当者名';
            mcm.JEOLContactPosition__c = '日本電子・連絡先（担当者所属）';
            mcm.JEOLReplyContactPosition__c = '日本電子・回答先（担当者所属）';
            mcm.JEOLRegionName__c = '日本電子・連絡先（支店）';
            mcm.JEOLReplyRegionName__c = '日本電子・回答先（支店）';
            mcm.JeolPipelineResponsible__c = testUser.Id;
            mcm.JeolPipelineResponsible2__c = testUser.Id;
            mcm.JEOLContactTel__c = '日本電子・連絡先（電話番号等）';
            mcm.JEOLReplyContactFax__c = '日本電子・回答先（FAX等）';
            mcm.RenewalCustomerNameReply__c = '客様名称';
            mcm.RenewalFooterComment__c = 'フッターコメント';
            if(i == 1){
                mcm.PreviousYearOrder__c = salesOrder.Id;
                mcm.PreviousYearPipeline__c = lastYearMcm.Id;
            }
            mcmList.add(mcm);
        }

        insert mcmList;
        return mcmList;
    }
}