objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>取引先コード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>取引先カテゴリコード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>取引先カテゴリ</label>
    <nameField>
        <label>取引先カテゴリ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CategoryJunction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>取引先カテゴリジャンクション</relationshipLabel>
        <relationshipName>AccJunctionLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CategoryName__c</fullName>
        <description>API参照名に注意</description>
        <label>取引先カテゴリコード</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>取引先カテゴリジャンクション</relationshipLabel>
        <relationshipName>JunctionLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KigyoTani__c</fullName>
        <label>企業単位</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>取引先カテゴリジャンクション</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>取引先カテゴリジャンクション</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesResult__c.object
<CustomObject>
    <description>削除対象Object
※別売上Objectに変更</description>
    <fields>
        <fullName>JishaTasha__c</fullName>
        <label>自社／他社</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesForeign__c</fullName>
        <label>売上金額（外貨）</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>bumon__c</fullName>
        <label>部門</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hanbaisaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (販売先)</relationshipLabel>
        <relationshipName>aaaS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>keiretsu__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kigyoTani__c</fullName>
        <label>企業単位</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>seikyusaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>請求先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (請求先)</relationshipLabel>
        <relationshipName>cccS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>shukkasaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (出荷先)</relationshipLabel>
        <relationshipName>bbbS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>uriageNendo__c</fullName>
        <label>売上年度</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>売上</label>
    <nameField>
        <label>売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_UriageShokaiList_ctrlTest.cls
@IsTest
private class JEOL_UriageShokaiList_ctrlTest {

    // 検索（企業単位）、検索結果取得、各メソッド呼び出し
    private static testMethod void test01() {

        // テストデータ生成
        testData();

        PageReference testPage = Page.JEOL_UriageShokaiListPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        System.currentPageReference().getParameters().put('kigyoTani','testT1');
        System.currentPageReference().getParameters().put('bumon','');
        System.currentPageReference().getParameters().put('keiretsu','');
        System.currentPageReference().getParameters().put('nendo','');
        System.currentPageReference().getParameters().put('hanbaisakiCode','testHNcd');
        System.currentPageReference().getParameters().put('hanbaisakiName','testHNname');
        System.currentPageReference().getParameters().put('shukkasakiCode','testSHcd');
        System.currentPageReference().getParameters().put('shukkasakiName','testSHname');
        System.currentPageReference().getParameters().put('seikyusakiCode','testSEcd');
        System.currentPageReference().getParameters().put('seikyusakiName','testSEname');
        System.currentPageReference().getParameters().put('customerCategory','testCCcode');

        JEOL_UriageShokaiList_ctrl ctrl = new JEOL_UriageShokaiList_ctrl();
        ctrl.changeOrder();
        List<JEOL_UriageShokaiList_ctrl.RowWrapper> wraps = ctrl.getSalesResult();
        if (!wraps.isEmpty()) {
            wraps.get(0).getUrl();
        }
        
    }

    // 検索（部門）
    private static testMethod void test02() {

        PageReference testPage = Page.JEOL_UriageShokaiListPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        System.currentPageReference().getParameters().put('bumon','tst');

        JEOL_UriageShokaiList_ctrl ctrl = new JEOL_UriageShokaiList_ctrl();
    }

    // 検索（系列）
    private static testMethod void test03() {

        PageReference testPage = Page.JEOL_UriageShokaiListPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        System.currentPageReference().getParameters().put('keiretsu','testKR');

        JEOL_UriageShokaiList_ctrl ctrl = new JEOL_UriageShokaiList_ctrl();
    }

    // 検索（年度）
    private static testMethod void test04() {

        PageReference testPage = Page.JEOL_UriageShokaiListPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        System.currentPageReference().getParameters().put('nendo','8888');

        JEOL_UriageShokaiList_ctrl ctrl = new JEOL_UriageShokaiList_ctrl();
    }

    // 検索（取引先カテゴリwhere句生成）
    private static testMethod void test05() {

        // テストデータ生成
        testData();

        PageReference testPage = Page.JEOL_UriageShokaiListPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        System.currentPageReference().getParameters().put('customerCategory','testCCcode');

        JEOL_UriageShokaiList_ctrl ctrl = new JEOL_UriageShokaiList_ctrl();
    }

    // 検索（addEqualCriteriaのwhere句作成、取引先カテゴリ該当なし）
    private static testMethod void test06() {

        // テストデータ作成
        testData();

        PageReference testPage = Page.JEOL_UriageShokaiListPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        System.currentPageReference().getParameters().put('hanbaisakiCode','testHNcd');
        System.currentPageReference().getParameters().put('customerCategory','testCCcodetest');

        JEOL_UriageShokaiList_ctrl ctrl = new JEOL_UriageShokaiList_ctrl();
    }

    // 検索（addLikeCriteriaのwhere句作成）
    private static testMethod void test07() {

        // テストデータ生成
        testData();

        PageReference testPage = Page.JEOL_UriageShokaiListPage;
        Test.setCurrentPage(testPage);

        // パラメータ設定
        System.currentPageReference().getParameters().put('hanbaisakiName','testHNname');

        JEOL_UriageShokaiList_ctrl ctrl = new JEOL_UriageShokaiList_ctrl();
    }

    // テストデータ作成
    private static void testData(){
        // 販売先取引先
        Account accHN = new Account();
        accHN.Name = 'testHNname';
        accHN.Code__c = 'testHNcd';
        insert accHN;

        // 出荷先取引先
        Account accSH = new Account();
        accSH.Name = 'testSHname';
        accSH.Code__c = 'testSHcd';
        insert accSH;

        // 請求先取引先
        Account accSE = new Account();
        accSE.Name = 'testSEname';
        accSE.Code__c = 'testSEcd';
        insert accSE;

        // 取引先カテゴリ
        Category__c cc = new Category__c();
        cc.Name = 'testCCname';
        cc.Code__c = 'testCCcode';
        insert cc;

        // 取引先カテゴリジャンクション
        CategoryJunction__c ccj = new CategoryJunction__c();
        ccj.CategoryName__c = cc.Id;
        ccj.Account__c = accHN.Id;  // 販売先取引先を登録
        insert ccj;

        // 売上（１：自社品：ベース）
        SalesResult__c sr11 = new SalesResult__c();
        sr11.Name = 'testSRname11';
        sr11.hanbaisaki__c = accHN.Id;
        sr11.shukkasaki__c = accSH.Id;
        sr11.seikyusaki__c = accSE.Id;
        sr11.kigyoTani__c = 'testT1';
        sr11.uriageNendo__c = '8888';
        sr11.bumon__c = 'tst';
        sr11.keiretsu__c = 'testKR';
        sr11.SalesForeign__c = 10000;
        sr11.JishaTasha__c = '自社品';
        insert sr11;
    }

}