objects/AsiaMaintenanceAccountBook__c.object
<CustomObject>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <label>Maintenance Contract Management</label>
        <referenceTo>AsiaMaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>Maintenance Account Book (MaintenanceContractManagement)</relationshipLabel>
        <relationshipName>MaintenanceAccountBook</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Maintenance Account Book</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaMaintenanceContractManagement__c.object
<CustomObject>
    <label>Maintenance Contract Management</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Maintenance Contract Management No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_MaintenanceAccountBookRed_ctrl.cls
public with sharing class JEOLAsia_MaintenanceAccountBookRed_ctrl {
	String sParentID = null;
    public JEOLAsia_MaintenanceAccountBookRed_ctrl(ApexPages.StandardController stdController) {
		if(!Test.isRunningTest()) {
            stdController.addFields(new List<String>{'MaintenanceContractManagement__r'});
        }
        AsiaMaintenanceAccountBook__c accBk = (AsiaMaintenanceAccountBook__c) stdController.getRecord();
        If (accBk != null && accBk.id != null && accBk.MaintenanceContractManagement__r != null) {
            sParentID = '' + accBk.MaintenanceContractManagement__r.id;
        }
	}

    public PageReference redirect(){
        if(sParentID != null){
            PageReference pageRef = new PageReference('/apex/JEOLAsia_MaintenanceAccountBook');
            pageRef.getParameters().put('id', sParentID);
            return pageRef;

        } else {
            return null;
        }
    }
}