objects/AsiaMaintenanceAccountBook__c.object
<CustomObject>
    <fields>
        <fullName>BillingAmount__c</fullName>
        <label>Billing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <label>Maintenance Contract Management</label>
        <referenceTo>AsiaMaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>Maintenance Account Book (MaintenanceContractManagement)</relationshipLabel>
        <relationshipName>MaintenanceAccountBook</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>PaymentAmount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Maintenance Account Book</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaMaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewContractEndDate__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewContractStartDate__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreviousYearPipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Year Pipeline</label>
        <referenceTo>AsiaMaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>Maintenance Contract Management</relationshipLabel>
        <relationshipName>PreviousYearPipeline_lkup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Maintenance Contract Management</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Maintenance Contract Management No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewContractEndDate__c</fullName>
        <label>契約完了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewContractStartDate__c</fullName>
        <label>契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>系列</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreviousYearPipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>前年保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipName>PreviousYearPipeline_lkup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_MaintenanceAccountBookCtrlTest.cls
@isTest
private class JEOLAsia_MaintenanceAccountBookCtrlTest {

	private static User testUser = JEOLAsia_TestDataFactory.createTestUser();

	private static testMethod void test01()
	{
		System.runAs (testUser)
		{
			Test.startTest();

			AsiaMaintenanceContractManagement__c contManPrev = new AsiaMaintenanceContractManagement__c();
			contManPrev.NewOdrSeries__c = 'testAPP';
			contManPrev.NewOdrSalesStaff__c = testUser.Id;
			contManPrev.NewContractStartDate__c = Date.parse('2016/05/01');
			contManPrev.NewContractEndDate__c = Date.parse('2016/05/31');
			insert contManPrev;

			AsiaMaintenanceContractManagement__c contMan = new AsiaMaintenanceContractManagement__c();
			contMan.NewOdrSeries__c = 'testAP';
			contMan.NewOdrSalesStaff__c = testUser.Id;
			contMan.NewContractStartDate__c = Date.parse('2017/05/01');
			contMan.NewContractEndDate__c = Date.parse('2017/05/31');
			contMan.PreviousYearPipeline__r = contManPrev;
			contMan.PreviousYearPipeline__c = contManPrev.Id;
			insert contMan;

			AsiaMaintenanceAccountBook__c accBk = new AsiaMaintenanceAccountBook__c();
			accBk.Name = 'testAMABName';
			accBk.PaymentAmount__c = 5000;
			accBk.BillingAmount__c = 10000;
			accBk.MaintenanceContractManagement__r = contManPrev;
			accBk.MaintenanceContractManagement__c = contManPrev.id;
			insert accBk;

			Pagereference ref = Page.JEOLAsia_MaintenanceAccountBook;
	        Test.setCurrentPage(ref);

			JEOLAsia_MaintenanceAccountBookCtrl ctrl = new JEOLAsia_MaintenanceAccountBookCtrl(new ApexPages.StandardController(contMan));

			PageReference retAddF = ctrl.addFirstRow();
			PageReference retAddL = ctrl.addLastRow();
			PageReference retRmvF = ctrl.removeFirstRow();
			PageReference retRmvL = ctrl.removeLastRow();
			PageReference retImp = ctrl.importPreviousYearData();
			PageReference retSave = ctrl.save();

			Test.stopTest();
		}
	}

	private static testMethod void test02()
	{
		System.runAs (testUser)
		{
			Test.startTest();

			AsiaMaintenanceContractManagement__c contManPrev = new AsiaMaintenanceContractManagement__c();
			contManPrev.NewOdrSeries__c = 'testAPP';
			contManPrev.NewOdrSalesStaff__c = testUser.Id;
			contManPrev.NewContractStartDate__c = Date.parse('2016/05/01');
			contManPrev.NewContractEndDate__c = Date.parse('2016/05/31');
			insert contManPrev;

			AsiaMaintenanceContractManagement__c contMan = new AsiaMaintenanceContractManagement__c();
			contMan.NewOdrSeries__c = 'testAP';
			contMan.NewOdrSalesStaff__c = testUser.Id;
			contMan.NewContractStartDate__c = Date.parse('2017/05/01');
			contMan.PreviousYearPipeline__r = contManPrev;
			contMan.PreviousYearPipeline__c = contManPrev.Id;
			insert contMan;

			Pagereference ref = Page.JEOLAsia_MaintenanceAccountBook;
	        Test.setCurrentPage(ref);

			JEOLAsia_MaintenanceAccountBookCtrl ctrl = new JEOLAsia_MaintenanceAccountBookCtrl(new ApexPages.StandardController(contMan));

			Test.stopTest();
		}
	}

	private static testMethod void test03()
	{
		System.runAs (testUser)
		{
			Test.startTest();

			AsiaMaintenanceContractManagement__c contManPrev = new AsiaMaintenanceContractManagement__c();
			contManPrev.NewOdrSeries__c = 'testAPP';
			contManPrev.NewOdrSalesStaff__c = testUser.Id;
			contManPrev.NewContractStartDate__c = Date.parse('2016/05/01');
			contManPrev.NewContractEndDate__c = Date.parse('2016/05/31');
			insert contManPrev;

			AsiaMaintenanceContractManagement__c contMan = new AsiaMaintenanceContractManagement__c();
			contMan.NewOdrSeries__c = 'testAP';
			contMan.NewOdrSalesStaff__c = testUser.Id;
			contMan.NewContractEndDate__c = Date.parse('2017/05/31');
			contMan.PreviousYearPipeline__r = contManPrev;
			contMan.PreviousYearPipeline__c = contManPrev.Id;
			insert contMan;

			Pagereference ref = Page.JEOLAsia_MaintenanceAccountBook;
	        Test.setCurrentPage(ref);

			JEOLAsia_MaintenanceAccountBookCtrl ctrl = new JEOLAsia_MaintenanceAccountBookCtrl(new ApexPages.StandardController(contMan));

			Test.stopTest();
		}
	}
	private static testMethod void test04()
	{
		System.runAs (testUser)
		{
			Test.startTest();

			AsiaMaintenanceContractManagement__c contManPrev = new AsiaMaintenanceContractManagement__c();
			contManPrev.NewOdrSeries__c = 'testAPP';
			contManPrev.NewOdrSalesStaff__c = testUser.Id;
			contManPrev.NewContractStartDate__c = Date.parse('2016/05/01');
			contManPrev.NewContractEndDate__c = Date.parse('2016/05/31');
			insert contManPrev;

			AsiaMaintenanceContractManagement__c contMan = new AsiaMaintenanceContractManagement__c();
			contMan.NewOdrSeries__c = 'testAP';
			contMan.NewOdrSalesStaff__c = testUser.Id;
			contMan.PreviousYearPipeline__r = contManPrev;
			contMan.PreviousYearPipeline__c = contManPrev.Id;
			insert contMan;

			Pagereference ref = Page.JEOLAsia_MaintenanceAccountBook;
	        Test.setCurrentPage(ref);

			JEOLAsia_MaintenanceAccountBookCtrl ctrl = new JEOLAsia_MaintenanceAccountBookCtrl(new ApexPages.StandardController(contMan));

			Test.stopTest();
		}
	}
}