objects/AsiaProfitCalculation__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <picklist>
            <picklistValues>
                <fullName>ASIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConsumptionTaxAmount__c</fullName>
        <label>Consumption Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContractAddress__c</fullName>
        <label>Contract Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractEmail__c</fullName>
        <label>Contract Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ContractName1__c</fullName>
        <label>Contract Name 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractName2__c</fullName>
        <label>Contract Name 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount1__c</fullName>
        <label>Custom Reduction Amount 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount2__c</fullName>
        <label>Custom Reduction Amount 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount3__c</fullName>
        <label>Custom Reduction Amount 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DeliveryCondition3__c</fullName>
        <label>Delivery Condition 3</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryDate_ArbitrarilyTitle__c</fullName>
        <label>Delivery Date Arbitrarily Title</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryDate_Arbitrarily__c</fullName>
        <label>Delivery Date Arbitrarily</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryDeadline__c</fullName>
        <label>Delivery Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OutputConsumptionTaxAmount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Output Consumption Tax Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputSubtotalReduction1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Output Subtotal Reduction 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputSubtotalReduction2__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Output Subtotal Reduction 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputTotalAmount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Output Total Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputTotalTaxAmount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Output Total Tax Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PaymentConditionTextarea__c</fullName>
        <label>Payment Condition Textarea</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Print2SPDetail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Print Spare Parts Detail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrintProformaInvoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Print Proforma Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrintQuotationFirstPage__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Print First Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuoteExpirationDate__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QuoteValidityPeriodDays__c</fullName>
        <label>Validity Period (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuoteValidityPeriod__c</fullName>
        <label>Validity Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesAssistant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Assistant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProfitCalculation_SalesAssistant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProfitCalculation_SalesPerson</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentName1__c</fullName>
        <label>Shipment Name 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentName2__c</fullName>
        <label>Shipment Name 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubtotalReductionAmount1__c</fullName>
        <label>Subtotal Reduction Amount 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubtotalReductionAmount2__c</fullName>
        <label>Subtotal Reduction Amount 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubtotalReductionName1__c</fullName>
        <label>Subtotal Reduction Name 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubtotalReductionName2__c</fullName>
        <label>Subtotal Reduction Name 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalTaxAmount__c</fullName>
        <label>Total Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <label>Quotation Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AsiaQuotationTermsConditions__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>&quot;This quotation is based on DDP customer&quot;</defaultValue>
        <label>Price</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ProfitCalculation__c</fullName>
        <label>Profit Calculation</label>
        <referenceTo>AsiaProfitCalculation__c</referenceTo>
        <relationshipLabel>Quotation Terms &amp; Conditions</relationshipLabel>
        <relationshipName>Quotation_Terms_Conditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation Terms &amp; Conditions</label>
    <nameField>
        <label>AsiaQuotationTermsConditions</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/salesperson__c.object
<CustomObject>
    <description>取引先に対して、年度と部門毎の担当者</description>
    <label>営業担当者</label>
    <nameField>
        <displayFormat>sp-{00000000}</displayFormat>
        <label>営業担当者_name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_QuotationTermsConditionsCtrTest.cls
@IsTest
private class JEOLAsia_QuotationTermsConditionsCtrTest {
	private static User testUser = JEOLAsia_TestDataFactory.createTestUser();
	private static testMethod void test01() {
		System.runAs (testUser) {
			Test.startTest();

			AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteExpirationDate__c = Date.today(), ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	        insert asiaProfitCalcObj;

			AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	        insert conditionObj;

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;            

            pageRef.getParameters().put('pcid', String.valueOf(asiaProfitCalcObj.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);
	        ctrl.saveAction();
	        ctrl.getValidityPeriod();

			Test.stopTest();
		}
	}

	private static testMethod void test02() {
		System.runAs (testUser) {
			Test.startTest();

			AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteValidityPeriodDays__c = 10, ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	        insert asiaProfitCalcObj;

			AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	        insert conditionObj;

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;
            

            pageRef.getParameters().put('pcid', 'test');
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);

			Test.stopTest();
		}
	}

	private static testMethod void test03() {
		System.runAs (testUser) {
			Test.startTest();

			AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteValidityPeriod__c = 10, ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	        insert asiaProfitCalcObj;

			AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	        insert conditionObj;

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;
            
            pageRef.getParameters().put('id', String.valueOf(conditionObj.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);

			Test.stopTest();
		}
	}

	private static testMethod void test04() {
		System.runAs (testUser) {
			Test.startTest();

			AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteExpirationDate__c = Date.today(), ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	        insert asiaProfitCalcObj;

			AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	        insert conditionObj;

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;
            
            pageRef.getParameters().put('id', 'test');
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);

			Test.stopTest();
		}
	}

	private static testMethod void test05() {
		System.runAs (testUser) {
			Test.startTest();

			AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteValidityPeriodDays__c = 10, ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	        insert asiaProfitCalcObj;

			AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	        insert conditionObj;

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;            

            pageRef.getParameters().put('pcid', String.valueOf(asiaProfitCalcObj.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);
	        ctrl.saveAction();
	        ctrl.getValidityPeriod();

			Test.stopTest();
		}
	}

	private static testMethod void test06() {
		System.runAs (testUser) {
			Test.startTest();

			AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteValidityPeriod__c = 10, ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	        insert asiaProfitCalcObj;

			AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	        insert conditionObj;

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;            

            pageRef.getParameters().put('pcid', String.valueOf(asiaProfitCalcObj.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);
	        ctrl.saveAction();
	        ctrl.getValidityPeriod();

			Test.stopTest();
		}
	}

	private static testMethod void test07() {
		System.runAs (testUser) {
			Test.startTest();

			AsiaProfitCalculation__c AsiaProfitCalculationObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteExpirationDate__c = Date.today(), ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	        insert AsiaProfitCalculationObj;


			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;            

            pageRef.getParameters().put('pcid', String.valueOf(AsiaProfitCalculationObj.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);
	        ctrl.saveAction();
	        ctrl.getValidityPeriod();

			Test.stopTest();
		}
	}

	private static testMethod void test08() {
		System.runAs (testUser) {
			Test.startTest();

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;
            pageRef.getParameters().put('id', Null);
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);

			Test.stopTest();
		}
	}

	private static testMethod void test09() {
		System.runAs (testUser) {
			Test.startTest();

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationTermsConditionsPage;
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationTermsConditionsCtrl ctrl = new JEOLAsia_QuotationTermsConditionsCtrl(sc);

			Test.stopTest();
		}
	}
}