objects/AsiaProfitCalculation__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <picklist>
            <picklistValues>
                <fullName>ASIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConsumptionTaxAmount__c</fullName>
        <label>Consumption Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContractAddress__c</fullName>
        <label>Contract Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractContact_dummyField__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Visualforce画面にて検索ダイアログを出すためだけに使用。
値は入れないようにしてください。</description>
        <label>ContractContact_dummyField</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>JEOL Asia</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotation (ContractContact_dummyField)</relationshipLabel>
        <relationshipName>ProfitCalculation_ContractContact_dummy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractEmail__c</fullName>
        <label>Contract Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ContractName1__c</fullName>
        <label>Contract Name 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractName2__c</fullName>
        <label>Contract Name 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount1__c</fullName>
        <label>Custom Reduction Amount 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount2__c</fullName>
        <label>Custom Reduction Amount 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount3__c</fullName>
        <label>Custom Reduction Amount 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DeliveryCondition3__c</fullName>
        <label>Delivery Condition 3</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryDate_ArbitrarilyTitle__c</fullName>
        <label>Delivery Date Arbitrarily Title</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryDate_Arbitrarily__c</fullName>
        <label>Delivery Date Arbitrarily</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryDeadline__c</fullName>
        <label>Delivery Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OutputConsumptionTaxAmount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Output Consumption Tax Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputSubtotalReduction1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Output Subtotal Reduction 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputSubtotalReduction2__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Output Subtotal Reduction 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputTotalAmount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Output Total Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputTotalTaxAmount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Output Total Tax Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PaymentConditionTextarea__c</fullName>
        <label>Payment Condition Textarea</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Print2SPDetail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Print Spare Parts Detail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrintProformaInvoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Print Proforma Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrintQuotationFirstPage__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Print First Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuoteExpirationDate__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SalesAssistant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Assistant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProfitCalculation_SalesAssistant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProfitCalculation_SalesPerson</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentContact_dummyField__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ShipmentContact_dummyField</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>JEOL Asia</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotation (ShipmentContact_dummyField)</relationshipLabel>
        <relationshipName>ProfitCalculation_ShipmentContact_dummy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentName1__c</fullName>
        <label>Shipment Name 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentName2__c</fullName>
        <label>Shipment Name 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubtotalReductionAmount1__c</fullName>
        <label>Subtotal Reduction Amount 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubtotalReductionAmount2__c</fullName>
        <label>Subtotal Reduction Amount 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubtotalReductionName1__c</fullName>
        <label>Subtotal Reduction Name 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubtotalReductionName2__c</fullName>
        <label>Subtotal Reduction Name 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalTaxAmount__c</fullName>
        <label>Total Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <label>Quotation Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AsiaProfitCalculationDetail__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Depth__c</fullName>
        <label>Depth</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Profit Calculation</label>
        <referenceTo>AsiaProfitCalculation__c</referenceTo>
        <relationshipName>ProfitCalculation_ProfitCalculatioDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>Sort No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quotation Detail</label>
    <nameField>
        <label>Asia_ProfitCalculationDetail Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaQuotationDescription__c.object
<CustomObject>
    <fields>
        <fullName>ProductSpecification__c</fullName>
        <label>Specification</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ProfitCalculationDetail__c</fullName>
        <label>Quotation Line</label>
        <referenceTo>AsiaProfitCalculationDetail__c</referenceTo>
        <relationshipLabel>Quotation Specifications</relationshipLabel>
        <relationshipName>QuotationSpecifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation Specifications</label>
    <nameField>
        <displayFormat>QD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaQuotationTermsConditions__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>&quot;This quotation is based on DDP customer&quot;</defaultValue>
        <label>Price</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ProfitCalculation__c</fullName>
        <label>Profit Calculation</label>
        <referenceTo>AsiaProfitCalculation__c</referenceTo>
        <relationshipLabel>Quotation Terms &amp; Conditions</relationshipLabel>
        <relationshipName>Quotation_Terms_Conditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation Terms &amp; Conditions</label>
    <nameField>
        <label>AsiaQuotationTermsConditions</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaTermsAndConditons__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <picklist>
            <picklistValues>
                <fullName>ASIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>Sort No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TermsAndConditions__c</fullName>
        <label>Terms And Conditions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Terms And Conditions Of Sale</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Category__c.object
<CustomObject>
    <label>取引先カテゴリ</label>
    <nameField>
        <label>取引先カテゴリ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/salesperson__c.object
<CustomObject>
    <description>取引先に対して、年度と部門毎の担当者</description>
    <label>営業担当者</label>
    <nameField>
        <displayFormat>sp-{00000000}</displayFormat>
        <label>営業担当者_name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_QuotationSpecificationCtrlTest.cls
@IsTest
private class JEOLAsia_QuotationSpecificationCtrlTest {
	private static User testUser = JEOLAsia_TestDataFactory.createTestUser();
	private static testMethod void test01() {
		System.runAs (testUser) {
			Test.startTest();

			testUser.Phone = '123456789';
	            testUser.Email = 'test@mail.com';
	            update testUser;

	            Contact contact = new Contact(Email = 'test@mail.com', LastName = 'test');
	            insert contact;

	            AsiaTermsAndConditons__c asiaTermAndCondObj = new AsiaTermsAndConditons__c(Company__c = 'ASIA', SortNo__c = 1, TermsAndConditions__c = 'Rich Text Area for Term and Condition Testing');
	            insert asiaTermAndCondObj;

	            

	            AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, ShipmentContact_dummyField__c = contact.Id, ContractContact_dummyField__c = contact.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteExpirationDate__c = Date.today(), ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	            insert asiaProfitCalcObj;

	            List<AsiaProfitCalculationDetail__c> asiaProfitCalcDetailList = new List<AsiaProfitCalculationDetail__c>();
	            asiaProfitCalcDetailList.add(new AsiaProfitCalculationDetail__c(Parent__c = asiaProfitCalcObj.id, Category__c = 'A', Body__c = '品名B', Name = 'test', SortNo__c = 1, Depth__c = 0));
	            asiaProfitCalcDetailList.add(new AsiaProfitCalculationDetail__c(Parent__c = asiaProfitCalcObj.id, Category__c = 'G', Body__c = '品名B', Name = 'test', SortNo__c = 1, Depth__c = 0));
	            insert asiaProfitCalcDetailList;

	            AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	            insert conditionObj;

	            List<AsiaQuotationDescription__c>asiaQuotationDescList = new List<AsiaQuotationDescription__c>();
	            asiaQuotationDescList.add(new AsiaQuotationDescription__c(ProfitCalculationDetail__c = asiaProfitCalcDetailList[0].Id, CurrencyIsoCode = 'JPY'));
	            asiaQuotationDescList.add(new AsiaQuotationDescription__c(ProfitCalculationDetail__c = asiaProfitCalcDetailList[0].Id, CurrencyIsoCode = 'JPY', ProductSpecification__c = 'test <br/><br>This is Testing. \r\n Testing again. \n <br/><table><tr><td>testing</td></tr><tr><td>testing</td></tr></table><br>Testing<br/><br/><br>This is Testing. \r\n Testing again. \n <br/>'));
	            asiaQuotationDescList.add(new AsiaQuotationDescription__c(ProfitCalculationDetail__c = asiaProfitCalcDetailList[1].Id, CurrencyIsoCode = 'JPY'));
	            asiaQuotationDescList.add(new AsiaQuotationDescription__c(ProfitCalculationDetail__c = asiaProfitCalcDetailList[1].Id, CurrencyIsoCode = 'JPY', ProductSpecification__c = 'test <br/><br>This is Testing. \r\n Testing again. \n <br/><table><tr><td>testing</td></tr><tr><td>testing</td></tr></table><br>Testing<br/><br/><br>This is Testing. \r\n Testing again. \n <br/>'));
	            insert asiaQuotationDescList;

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationSpecificationPage;
            
            pageRef.getParameters().put('id', String.valueOf(asiaQuotationDescList[1].Id));
            pageRef.getParameters().put('pcid', String.valueOf(testUser.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationSpecificationCtrl ctrl = new JEOLAsia_QuotationSpecificationCtrl(sc);

	        ctrl.getCategoryASize();
	        ctrl.getCategoryBSize();
	        ctrl.getCategoryGSize();
	        ctrl.saveActionxxe();

			Test.stopTest();
		}
	}

	private static testMethod void test02() {
		System.runAs (testUser) {
			Test.startTest();

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationSpecificationPage;
            
            pageRef.getParameters().put('retURL', String.valueOf(testUser.Id));
            pageRef.getParameters().put('save_new', String.valueOf(testUser.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationSpecificationCtrl ctrl = new JEOLAsia_QuotationSpecificationCtrl(sc);

			Test.stopTest();
		}
	}

	private static testMethod void test03() {
		System.runAs (testUser) {
			Test.startTest();

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationSpecificationPage;
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationSpecificationCtrl ctrl = new JEOLAsia_QuotationSpecificationCtrl(sc);

			Test.stopTest();
		}
	}

	private static testMethod void test04() {
		System.runAs (testUser) {
			Test.startTest();

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationSpecificationPage;
            
            pageRef.getParameters().put('id', '');
            pageRef.getParameters().put('pcid', String.valueOf(testUser.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationSpecificationCtrl ctrl = new JEOLAsia_QuotationSpecificationCtrl(sc);

			Test.stopTest();
		}
	}

	private static testMethod void test05() {
		System.runAs (testUser) {
			Test.startTest();

			testUser.Phone = '123456789';
	            testUser.Email = 'test@mail.com';
	            update testUser;

	            Contact contact = new Contact(Email = 'test@mail.com', LastName = 'test');
	            insert contact;

	            AsiaTermsAndConditons__c asiaTermAndCondObj = new AsiaTermsAndConditons__c(Company__c = 'ASIA', SortNo__c = 1, TermsAndConditions__c = 'Rich Text Area for Term and Condition Testing');
	            insert asiaTermAndCondObj;

	            

	            AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, ShipmentContact_dummyField__c = contact.Id, ContractContact_dummyField__c = contact.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteExpirationDate__c = Date.today(), ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	            insert asiaProfitCalcObj;

	            List<AsiaProfitCalculationDetail__c> asiaProfitCalcDetailList = new List<AsiaProfitCalculationDetail__c>();
	            asiaProfitCalcDetailList.add(new AsiaProfitCalculationDetail__c(Parent__c = asiaProfitCalcObj.id, Category__c = 'A', Body__c = '品名B', Name = 'test', SortNo__c = 1, Depth__c = 0));
	            insert asiaProfitCalcDetailList;

	            AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	            insert conditionObj;


			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationSpecificationPage;

            pageRef.getParameters().put('pcid', String.valueOf(testUser.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationSpecificationCtrl ctrl = new JEOLAsia_QuotationSpecificationCtrl(sc);

	        ctrl.getCategoryASize();
	        ctrl.getCategoryBSize();
	        ctrl.getCategoryGSize();
	        ctrl.saveActionxxe();

			Test.stopTest();
		}
	}

	private static testMethod void test06() {
		System.runAs (testUser) {
			Test.startTest();

			testUser.Phone = '123456789';
	            testUser.Email = 'test@mail.com';
	            update testUser;

	            Contact contact = new Contact(Email = 'test@mail.com', LastName = 'test');
	            insert contact;

	            AsiaTermsAndConditons__c asiaTermAndCondObj = new AsiaTermsAndConditons__c(Company__c = 'ASIA', SortNo__c = 1, TermsAndConditions__c = 'Rich Text Area for Term and Condition Testing');
	            insert asiaTermAndCondObj;

	            

	            AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, ShipmentContact_dummyField__c = contact.Id, ContractContact_dummyField__c = contact.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteExpirationDate__c = Date.today(), ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	            insert asiaProfitCalcObj;

	            List<AsiaProfitCalculationDetail__c> asiaProfitCalcDetailList = new List<AsiaProfitCalculationDetail__c>();
	            asiaProfitCalcDetailList.add(new AsiaProfitCalculationDetail__c(Parent__c = asiaProfitCalcObj.id, Category__c = 'B', Body__c = '品名B', Name = 'test', SortNo__c = 1, Depth__c = 0));
	            insert asiaProfitCalcDetailList;

	            AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	            insert conditionObj;

	            List<AsiaQuotationDescription__c>asiaQuotationDescList = new List<AsiaQuotationDescription__c>();
	            asiaQuotationDescList.add(new AsiaQuotationDescription__c(ProfitCalculationDetail__c = asiaProfitCalcDetailList[0].Id, CurrencyIsoCode = 'JPY'));
	            asiaQuotationDescList.add(new AsiaQuotationDescription__c(ProfitCalculationDetail__c = asiaProfitCalcDetailList[0].Id, CurrencyIsoCode = 'JPY', ProductSpecification__c = 'test <br/><br>This is Testing. \r\n Testing again. \n <br/><table><tr><td>testing</td></tr><tr><td>testing</td></tr></table><br>Testing<br/><br/><br>This is Testing. \r\n Testing again. \n <br/>'));
	            insert asiaQuotationDescList;

			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationSpecificationPage;
            
            pageRef.getParameters().put('id', String.valueOf(asiaQuotationDescList[1].Id));
            pageRef.getParameters().put('pcid', String.valueOf(testUser.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationSpecificationCtrl ctrl = new JEOLAsia_QuotationSpecificationCtrl(sc);

	        ctrl.getCategoryASize();
	        ctrl.getCategoryBSize();
	        ctrl.getCategoryGSize();
	        ctrl.saveActionxxe();

			Test.stopTest();
		}
	}

	private static testMethod void test07() {
		System.runAs (testUser) {
			Test.startTest();

			testUser.Phone = '123456789';
	            testUser.Email = 'test@mail.com';
	            update testUser;

	            Contact contact = new Contact(Email = 'test@mail.com', LastName = 'test');
	            insert contact;

	            AsiaTermsAndConditons__c asiaTermAndCondObj = new AsiaTermsAndConditons__c(Company__c = 'ASIA', SortNo__c = 1, TermsAndConditions__c = 'Rich Text Area for Term and Condition Testing');
	            insert asiaTermAndCondObj;

	            

	            AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, ShipmentContact_dummyField__c = contact.Id, ContractContact_dummyField__c = contact.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteExpirationDate__c = Date.today(), ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	            insert asiaProfitCalcObj;

	            List<AsiaProfitCalculationDetail__c> asiaProfitCalcDetailList = new List<AsiaProfitCalculationDetail__c>();
	            asiaProfitCalcDetailList.add(new AsiaProfitCalculationDetail__c(Parent__c = asiaProfitCalcObj.id, Category__c = 'B', Body__c = '品名B', Name = 'test', SortNo__c = 1, Depth__c = 0));
	            insert asiaProfitCalcDetailList;

	            AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	            insert conditionObj;


			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationSpecificationPage;            
            pageRef.getParameters().put('pcid', String.valueOf(testUser.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationSpecificationCtrl ctrl = new JEOLAsia_QuotationSpecificationCtrl(sc);

	        ctrl.getCategoryASize();
	        ctrl.getCategoryBSize();
	        ctrl.getCategoryGSize();
	        ctrl.saveActionxxe();

			Test.stopTest();
		}
	}

	private static testMethod void test08() {
		System.runAs (testUser) {
			Test.startTest();

			testUser.Phone = '123456789';
	            testUser.Email = 'test@mail.com';
	            update testUser;

	            Contact contact = new Contact(Email = 'test@mail.com', LastName = 'test');
	            insert contact;

	            AsiaTermsAndConditons__c asiaTermAndCondObj = new AsiaTermsAndConditons__c(Company__c = 'ASIA', SortNo__c = 1, TermsAndConditions__c = 'Rich Text Area for Term and Condition Testing');
	            insert asiaTermAndCondObj;

	            

	            AsiaProfitCalculation__c asiaProfitCalcObj = new AsiaProfitCalculation__c(SalesAssistant__c = testUser.Id, SalesPerson__c = testUser.Id, ShipmentContact_dummyField__c = contact.Id, ContractContact_dummyField__c = contact.Id, Company__c = 'ASIA', PaymentConditionTextarea__c = 'Testing in Payment Condition Textarea.', PrintProformaInvoice__c = true, 
	            											OutputConsumptionTaxAmount__c = true, ConsumptionTaxAmount__c = 1000, OutputTotalTaxAmount__c = true, TotalTaxAmount__c = 1000, OutputTotalAmount__c = true, 
	            											TotalAmount__c = 1000, CustomReductionAmount3__c = 1000, OutputSubtotalReduction2__c = true, SubtotalReductionName2__c = 'test', SubtotalReductionAmount2__c = 1000,
	            											CustomReductionAmount2__c = 1000, OutputSubtotalReduction1__c = true, SubtotalReductionName1__c = 'test', SubtotalReductionAmount1__c = 1000, CustomReductionAmount1__c = 1000,
	            											QuoteExpirationDate__c = Date.today(), ContractName1__c = 'test', ContractName2__c = 'test', ShipmentName1__c = 'test', ShipmentName2__c = 'test',
	            											Print2SPDetail__c = true, ContractAddress__c = 'test', PrintQuotationFirstPage__c = false, ContractEmail__c = 'test@mail.com', DeliveryCondition3__c = 'test',
	            											DeliveryDeadline__c = Date.today(), DeliveryDate_Arbitrarily__c = 'test', DeliveryDate_ArbitrarilyTitle__c = 'test');
	            insert asiaProfitCalcObj;

	            List<AsiaProfitCalculationDetail__c> asiaProfitCalcDetailList = new List<AsiaProfitCalculationDetail__c>();
	            asiaProfitCalcDetailList.add(new AsiaProfitCalculationDetail__c(Parent__c = asiaProfitCalcObj.id, Category__c = 'G', Body__c = '品名B', Name = 'test', SortNo__c = 1, Depth__c = 0));
	            insert asiaProfitCalcDetailList;

	            AsiaQuotationTermsConditions__c conditionObj = new AsiaQuotationTermsConditions__c(CurrencyIsoCode = 'JPY', Price__c = 'This quotation is based on DDP customer', ProfitCalculation__c = asiaProfitCalcObj.id);
	            insert conditionObj;


			ApexPages.StandardController sc = new ApexPages.StandardController(testUser);
			PageReference pageRef = Page.JEOLAsia_QuotationSpecificationPage;
            pageRef.getParameters().put('pcid', String.valueOf(testUser.Id));
            Test.setCurrentPage(pageRef);
	        JEOLAsia_QuotationSpecificationCtrl ctrl = new JEOLAsia_QuotationSpecificationCtrl(sc);

	        ctrl.getCategoryASize();
	        ctrl.getCategoryBSize();
	        ctrl.getCategoryGSize();
	        ctrl.saveActionxxe();

			Test.stopTest();
		}
	}
}