objects/AsiaMaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Maintenance Contract Management</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Maintenance Contract Management No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOLAsia_MaintenanceAnnaiPrintPageTest.cls
@isTest
private class JEOLAsia_MaintenanceAnnaiPrintPageTest {

	private static User testUser = JEOLAsia_TestDataFactory.createTestUser();

	private static testMethod void test01()
    {
    	System.runAs (testUser)
    	{
    		Test.startTest();

    		AsiaMaintenanceContractManagement__c contMan = new AsiaMaintenanceContractManagement__c();
			contMan.NewOdrSeries__c = 'testAP';
			contMan.NewOdrSalesStaff__c = testUser.Id;
			insert contMan;

			PageReference testPage = Page.JEOL_QuotationPrintPage;
	        Map<String, String> params = testPage.getParameters();
	        params.put('id', contMan.Id);
	        params.put('preview', 'true');
	        params.put('print', 'true');
	        Test.setCurrentPage(testPage);

			JEOLAsia_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOLAsia_MaintenanceAnnaiPrintPageCtrl();
			ctrl.rec = new AsiaMaintenanceContractManagement__c();
			ctrl.prevSalesOrder = new SalesOrder__c();
			ctrl.renewalAccount = new Account();
			ctrl.blankDate = 'testDate';

			JEOLAsia_MaintenanceAnnaiPrintPageCtrl.PageBlock pb = new JEOLAsia_MaintenanceAnnaiPrintPageCtrl.PageBlock();
			ctrl.pdfPages = new List<JEOLAsia_MaintenanceAnnaiPrintPageCtrl.PageBlock>();

			JEOLAsia_MaintenanceAnnaiPrintPageCtrl.QuotationHeader qh = new JEOLAsia_MaintenanceAnnaiPrintPageCtrl.QuotationHeader(new AsiaMaintenanceContractManagement__c());

			qh.quotatinNameLines.add('testNL01');
			qh.quotatinNameLines.add('testNL02');

			pb.setHead(qh);
			pb.getQuotatinNameLinesSize();
			pb.getHasNoteText();

        	Test.stopTest();
    	}
    }
}