objects/AsiaMaintenanceAccountBook__c.object
<CustomObject>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <label>Maintenance Contract Management</label>
        <referenceTo>AsiaMaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>Maintenance Account Book (MaintenanceContractManagement)</relationshipLabel>
        <relationshipName>MaintenanceAccountBook</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Maintenance Account Book</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaMaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewContractEndDate__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewContractStartDate__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.SalesAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.SalesAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Maintenance Contract Management (SalesAccount)</relationshipLabel>
        <relationshipName>ASalesOdr_Pipeline_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ShipmentAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ShipmentAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Maintenance Contract Management (ShipmentAccount)</relationshipLabel>
        <relationshipName>ASalesOdr_Pipeline_Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Master No.</label>
        <referenceTo>AsiaProjectMaster__c</referenceTo>
        <relationshipLabel>Maintenance Contract Management</relationshipLabel>
        <relationshipName>MaintenanceContractManagement_ProjMaster</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuotationSentDate__c</fullName>
        <label>QT Issued Date</label>
        <type>Date</type>
    </fields>
    <label>Maintenance Contract Management</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Maintenance Contract Management No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AsiaProjectMaster__c.object
<CustomObject>
    <fields>
        <fullName>ContractAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.CustomerSituation__c</field>
                <operation>equals</operation>
                <value>有効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Master (Contract Account)</relationshipLabel>
        <relationshipName>ProjectMaster_ContractAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>Series</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.CustomerSituation__c</field>
                <operation>equals</operation>
                <value>有効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Master (Shipment Account)</relationshipLabel>
        <relationshipName>ProjectMaster_ShipmentAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Master</label>
    <nameField>
        <displayFormat>PJM-{00000000}</displayFormat>
        <label>Project No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewContractEndDate__c</fullName>
        <label>契約完了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewContractStartDate__c</fullName>
        <label>契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.SalesAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.SalesAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (販売先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>系列</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ShipmentAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ShipmentAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (出荷先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuotationSentDate__c</fullName>
        <label>見積書送付日</label>
        <type>Date</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_MaintenanceBillingListTest.cls
@IsTest
private class JEOLAsia_MaintenanceBillingListTest {
    // User(ユーザ)
    private static User testUser = JEOLAsia_TestDataFactory.createTestUser();

    private static Date dTodayFirstDay = Date.newInstance(Date.today().year(), Date.today().month(), 1);
    //Account(取引先)
    private static Account testAccount = JEOLAsia_TestDataFactory.createAccountTestObject('AccountName', 'T123456', false, '有効', false, '有効');
    private static Map<Id, AsiaProjectMaster__c> projectMasterMap;

    /*
     * Description: Test Constructor(without search conditions)
     * MethodName : JEOL_MaintenanceListToRenew_ctrl_Test01
     */
    private static testMethod void JEOLAsia_MaintenanceBillingList_ctrl_Test01() {
        // Preparation(None)
        System.runAs (testUser) {
            Test.startTest();

            JEOLAsia_MaintenanceBillingList_ctrl ctrl = new JEOLAsia_MaintenanceBillingList_ctrl();

            Test.stopTest();
        }
    }

    /*
     * Description: Test series Button(selected series is two)
     * MethodName : seriesSelectBtn_Test01
     */
    private static testMethod void seriesSelectBtn_Test01() {
        JEOLAsia_MaintenanceBillingList_ctrl ctrl = new JEOLAsia_MaintenanceBillingList_ctrl();
        Integer selectedCount = 1;
        for(JEOLAsia_MaintenanceBillingList_ctrl.OptionDetail od :ctrl.SeriesOptions){
            if(selectedCount < 3){
                od.isSelected = true;
            }
        }
        System.runAs (testUser) {
            Test.startTest();

            ctrl.seriesSelectApply();
            ctrl.getSelectedSeries();

            Test.stopTest();
        }
    }

    /*
     * Description: Test series Button(All select)
     * MethodName : seriesSelectBtn_Test01
     */
    private static testMethod void seriesSelectBtn_Test02() {
        JEOLAsia_MaintenanceBillingList_ctrl ctrl = new JEOLAsia_MaintenanceBillingList_ctrl();
        ctrl.seriesSelectAllSelect();
        System.runAs (testUser) {
            Test.startTest();

            ctrl.seriesSelectApply();
            ctrl.getSelectedSeries();

            Test.stopTest();
        }
    }



    /*
     * Description: Test Search/Clear Method(with search coditions)
     * MethodName : doSearch_Clear_Test01
     */
    private static testMethod void doSearch_Clear_Test01() {
        // Preparation
        createTestData01();
        // Set Search Conditions
        JEOLAsia_MaintenanceBillingList_ctrl ctrl = new JEOLAsia_MaintenanceBillingList_ctrl();
        ctrl.month = '2016';
        ctrl.customerCode = '0001';
        ctrl.customerName = 'TestName';


        ctrl.getStatusOptions();
        ctrl.status = 'Only Inspected';

        ctrl.invoiceNumber = '';

        ctrl.getCCategoryOptions();

        System.runAs (testUser) {
            Test.startTest();

            // Search
            ctrl.doSearch();
            // Search Reult
            ctrl.getSalesPipelines();
            // Clear
            ctrl.doFormClear();

            Test.stopTest();
        }
    }

    private static void createTestData01(){
        // create maintenance contract management records
        List<AsiaMaintenanceContractManagement__c> mcmList = createMcm();

        String sType = '1';
        String sStartMonth;
        String sEndMonth;
        Integer mcmCount = 0;
        for(AsiaMaintenanceContractManagement__c mcm :mcmList){
            if(mcmCount < 3){
                List<AsiaMaintenanceAccountBook__c> mabList = new List<AsiaMaintenanceAccountBook__c>();
                sStartMonth = Datetime.newInstance(projectMasterMap.get(mcm.ProjectMaster__c).ContractStartDate__c, Time.newInstance(0,0,0,0)).format('yyyyMM');
                sEndMonth = datetime.newInstance(projectMasterMap.get(mcm.ProjectMaster__c).ContractEndDate__c, Time.newInstance(0,0,0,0)).format('yyyyMM');

                Integer iStartYear = Integer.valueOf(sStartMonth.substring(0, 4));
                Integer iStartMonth = Integer.valueOf(sStartMonth.substring(4));
                Integer iEndYear = Integer.valueOf(sEndMonth.substring(0, 4));
                Integer iEndMonth = Integer.valueOf(sEndMonth.substring(4));

                if (iEndYear > iStartYear + 10) {
                    iEndYear = iStartYear;
                    iEndMonth = iStartMonth;
                }

                for(Integer i = 0; i < 12; i ++){
                    AsiaMaintenanceAccountBook__c mabRow = new AsiaMaintenanceAccountBook__c();
                    mabRow.MaintenanceContractManagement__c = mcm.Id;
                    mabRow.Month__c = ('0000' + string.valueof(iStartYear)).substring(string.valueof(iStartYear).length()) + ('00' + string.valueof(iStartMonth)).substring(string.valueof(iStartMonth).length());
                    mabRow.Name = mabRow.Month__c.Substring(0, 4) + '/' + mabRow.Month__c.Substring(4);
                    mabList.add(mabRow);
                    // Get the next month
                    iStartMonth += 1;
                    if (iStartMonth > 12) {
                        iStartYear += 1;
                        iStartMonth = 1;
                    }
                }
                try{
                    //insert mabList;
                }catch(Exception e){
                    system.debug('★★★★★★★★★★★★★ Maintenance Account Book Insert Error  start ★★★★★★★★');
                    system.debug('★★ LineNo' + e.getLineNumber() + ': ' + e.getMessage() + ' ★★');
                    system.debug('★★★★★★★★★★★★★ Maintenance Account Book Insert Error  end ★★★★★★★★');
                }
            }
            mcmCount ++;
        }

    }

    /**
     * [createMcm create maintenance contract management records]
     * @return [maintenance contract management records]
     */
    private static List<AsiaMaintenanceContractManagement__c> createMcm(){
        List<AsiaMaintenanceContractManagement__c> mcmList = new List<AsiaMaintenanceContractManagement__c>();
        List<AsiaProjectMaster__c> pmList = createProjectMasterData();
        projectMasterMap = new Map<Id, AsiaProjectMaster__c>();
        for(AsiaProjectMaster__c pm :pmList){
            projectMasterMap.put(pm.Id, pm);
        }
        // create maintenance contract management record (2 Pages Records)
        for(Integer i = 0; i < 102; i ++){
            AsiaMaintenanceContractManagement__c mcm = new AsiaMaintenanceContractManagement__c();
            mcm.NewOdrSalesAccount__c = testAccount.Id;
            mcm.NewOdrShipmentAccount__c = testAccount.Id;
            mcm.NewOdrSalesStaff__c = testUser.Id;
            if(i < 10){
                mcm.NewOdrSeries__c = 'CA';
            }else if( i < 20){
                mcm.NewOdrSeries__c = 'AP';
            }else if(i < 30){
                mcm.NewOdrSeries__c = 'BS';
            }else if(i < 50){
                mcm.NewOdrSeries__c = 'GC';
            }else if(i < 70){
                mcm.NewOdrSeries__c = 'EM';
            }else if(i < 102){
                mcm.NewOdrSeries__c = 'XP';
            }
            if(i < 70){
                mcm.ProjectMaster__c = pmList[i].Id;
            }else{
                mcm.ProjectMaster__c = pmList[0].Id;
            }

            mcm.QuotationSentDate__c = dTodayFirstDay.addDays(i);
            mcm.NewContractStartDate__c = dTodayFirstDay.addDays(i);
            mcm.NewContractEndDate__c = dTodayFirstDay.addDays((i+30));
            mcmList.add(mcm);
        }
        try{
            insert mcmList;
        }catch(Exception e){
            system.debug('★★★★★★★★★★★★★ Maintenance Contract Management Insert Error  start ★★★★★★★★');
            system.debug('★★ LineNo' + e.getLineNumber() + ': ' + e.getMessage() + ' ★★');
            system.debug('★★★★★★★★★★★★★ Maintenance Contract Management Insert Error  end ★★★★★★★★');
        }
        return mcmList;
    }

    /**
     * [createProjectMasterData create project master records]
     * @return [project master records]
     */
    private static List<AsiaProjectMaster__c> createProjectMasterData(){
        List<AsiaProjectMaster__c> projectMasterList = new List<AsiaProjectMaster__c>();
        for(Integer i = 0; i < 70; i ++){
            AsiaProjectMaster__c projectMaster = new AsiaProjectMaster__c();
            if(i < 10){
                projectMaster.ProjectNumber__c = 'PM-00000' + String.valueOf(i);
            }else {
                projectMaster.ProjectNumber__c = 'PM-0000' + String.valueOf(i);
            }
            projectMaster.ContractAccount__c = testAccount.Id;
            projectMaster.ShipmentAccount__c = testAccount.Id;
            if(i < 10){
                projectMaster.Series__c = 'CA';
            }else if( i < 20){
                projectMaster.Series__c = 'AP';
            }else if(i < 30){
                projectMaster.Series__c = 'BS';
            }else if(i < 50){
                projectMaster.Series__c = 'GC';
            }else if(i < 70){
                projectMaster.Series__c = 'EM';
            }
            projectMaster.SalesPerson__c = testUser.Id;
            projectMaster.ContractStartDate__c = dTodayFirstDay.addDays(i);
            projectMaster.ContractEndDate__c = dTodayFirstDay.addDays((i+30));
            projectMaster.ContractPrice__c = i*1000;
            projectMasterList.add(projectMaster);
        }
        try{
            insert projectMasterList;
        }catch(Exception e){
            system.debug('★★★★★★★★★★★★★ ProjectMaster Insert Error  start ★★★★★★★★');
            system.debug('★★ LineNo' + e.getLineNumber() + ': ' + e.getMessage() + ' ★★');
            system.debug('★★★★★★★★★★★★★ ProjectMaster Insert Error  end ★★★★★★★★');
        }
        return projectMasterList;
    }
}