objects/AsiaProfitCalculation__c.object
<CustomObject>
    <fields>
        <fullName>JProdCostCurrency__c</fullName>
        <label>JProdCostCurrency</label>
        <picklist>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JPY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubtotalACostUnit__c</fullName>
        <label>Subtotal A (JProd Cost Unit)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubtotalADiscountRate__c</fullName>
        <label>SubtotalADiscountRate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SubtotalADiscountType__c</fullName>
        <label>Subtotal A Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>Rate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Value</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubtotalADiscount__c</fullName>
        <label>SubtotalADiscount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubtotalASalesUnit__c</fullName>
        <label>Subtotal A (Sales Unit)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProfitRate__c</fullName>
        <label>Total Profit Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <label>Quotation Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AsiaProfitCalculationDetail2SP__c.object
<CustomObject>
    <fields>
        <fullName>CostPriceJPY__c</fullName>
        <label>Cost Price (JPY)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProfitCalculationDetail__c</fullName>
        <label>Profit Calculation Detail</label>
        <referenceTo>AsiaProfitCalculationDetail__c</referenceTo>
        <relationshipName>Profit_Calculation_2SP_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>Sort No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quotation 2SP Parts</label>
    <nameField>
        <displayFormat>2SP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaProfitCalculationDetail__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CostPriceJProdUnit__c</fullName>
        <label>Cost Price (JProd unit)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Depth__c</fullName>
        <label>Depth</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Profit Calculation</label>
        <referenceTo>AsiaProfitCalculation__c</referenceTo>
        <relationshipName>ProfitCalculation_ProfitCalculatioDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>Sort No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>1.明細
2.見出し
3.諸経費
4.小計</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quotation Detail</label>
    <nameField>
        <label>Asia_ProfitCalculationDetail Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaProfitCalculationRate__c.object
<CustomObject>
    <fields>
        <fullName>CurrencyBase__c</fullName>
        <label>Currency Base</label>
        <picklist>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CurrencyToConvert__c</fullName>
        <label>Currency To Convert</label>
        <picklist>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Profit_Calculation__c</fullName>
        <label>Profit Calculation</label>
        <referenceTo>AsiaProfitCalculation__c</referenceTo>
        <relationshipName>ProfitCalculation_ProfitCalculationRate</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReadOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ReadOnly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quotation Rate</label>
    <nameField>
        <displayFormat>PCR-{00000000}</displayFormat>
        <label>Profit Calculation Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Category__c.object
<CustomObject>
    <label>取引先カテゴリ</label>
    <nameField>
        <label>取引先カテゴリ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/JEOLAsia_QuotationExportCSVCtrlTest.cls
@IsTest
public class JEOLAsia_QuotationExportCSVCtrlTest {
    // User(ユーザ)
    private static User testUser = JEOLAsia_TestDataFactory.createTestUser();
    /*
* Description: Test Constructor
* MethodName : Test01
*/
    private static testMethod void test01() {
        // Preparation(None)
        System.runAs (testUser) {
            Test.startTest();
            Id id = createCalculationData();
           	createCalculationDetail2SP(id);
            createCalculationRateData(id,'USD');
            
            
            Pagereference ref = Page.JEOLAsia_QuotationExportCSV;
            Map<String, String> params = new Map<String, String>();
            
            params.put('ID', id);
            ref.getParameters().putAll(params);
            
            Test.setCurrentPage(ref);
            JEOLAsia_QuotationExportCSVCtrl ctrl = new JEOLAsia_QuotationExportCSVCtrl();
            ctrl.getFileName();
            List<List<String>> rowList =  ctrl.lslsstrRowMCM;
            Id i=  ctrl.qtId;
            String s = ctrl.sTitle;
            
            Test.stopTest();
        }
    }
   
    /**
* [createCalculation create project master records]
* @return [AsiaProfitCalculation Id]
*/
    private static Id createCalculationData(){
        AsiaProfitCalculation__c entity = new AsiaProfitCalculation__c();
        entity.JProdCostCurrency__c = 'USD';
        entity.SubtotalACostUnit__c = 999999;
        entity.SubtotalASalesUnit__c = 99999.64;
        entity.SubtotalADiscountRate__c = 99;
        entity.SubtotalADiscount__c = 9999;
        entity.SubtotalADiscountType__c = 'Value';
        entity.TotalProfitRate__c = 10;
        try{
            insert entity;
        }catch(Exception e){
            system.debug('★★★★★★★★★★★★★ AsiaProfitCalculation Insert Error  start ★★★★★★★★');
            system.debug('★★ LineNo' + e.getLineNumber() + ': ' + e.getMessage() + ' ★★');
            system.debug('★★★★★★★★★★★★★ AsiaProfitCalculation Insert Error  end ★★★★★★★★');
        }
        return entity.Id;
    }
    /**
* [createCalculationRateData create project master records]
* @return [AsiaProfitCalculationRate records]
*/
    private static List<AsiaProfitCalculationRate__c> createCalculationRateData(Id id,String currencyBase){
        List<AsiaProfitCalculationRate__c> entityList = new List<AsiaProfitCalculationRate__c>(); 
        AsiaProfitCalculationRate__c entity;
        for(Integer i = 0; i < 2; i ++){
            entity = new AsiaProfitCalculationRate__c();            
            entity.CurrencyToConvert__c  = 'JPY';
            entity.CurrencyBase__c = currencyBase;            
            entity.Profit_Calculation__c = id;
            entity.Type__c  = '2'; 
            entity.ReadOnly__c=false;
            entity.Rate__c=0.01;
            entityList.add(entity);
        }
        try{
            insert entityList;
        }catch(Exception e){
            system.debug('★★★★★★★★★★★★★ AsiaProfitCalculationRate Insert Error  start ★★★★★★★★');
            system.debug('★★ LineNo' + e.getLineNumber() + ': ' + e.getMessage() + ' ★★');
            system.debug('★★★★★★★★★★★★★ AsiaProfitCalculationRate Insert Error  end ★★★★★★★★');
        }
        
        return entityList;
    }
    /**
* [createCalculationDetailData create project master records]
* @return [AsiaProfitCalculationDetail records]
*/
    private static List<AsiaProfitCalculationDetail__c> createCalculationDetailData(Id id){
        List<AsiaProfitCalculationDetail__c> entityList = new List<AsiaProfitCalculationDetail__c>();        
        AsiaProfitCalculationDetail__c entity;
        for(Integer i = 0; i < 5; i ++){
            entity = new AsiaProfitCalculationDetail__c();            
            entity.CurrencyIsoCode = 'JPY';
            entity.Depth__c = 1;            
            entity.Parent__c = id;
            entity.SortNo__c = i; 
            entity.Quantity__c=3;
            entity.UnitPrice__c=0;
            entity.CostPriceJProdUnit__c=0;
            entity.Category__c='A';
            entityList.add(entity);
            
        }
        try{
            insert entityList;
           
        }catch(Exception e){
            system.debug('★★★★★★★★★★★★★ AsiaProfitCalculationDetail Insert Error  start ★★★★★★★★');
            system.debug('★★ LineNo' + e.getLineNumber() + ': ' + e.getMessage() + ' ★★');
            system.debug('★★★★★★★★★★★★★ AsiaProfitCalculationDetail Insert Error  end ★★★★★★★★');
        }
        
        return entityList;
    }
    /**
* [createdetail2SP create AsiaProfitCalculationDetail2SP records]
* @return [AsiaProfitCalculationDetail2SP records]
*/
    private static List<AsiaProfitCalculationDetail2SP__c> createCalculationDetail2SP(Id asiaProfitCalculationId){
        List<AsiaProfitCalculationDetail2SP__c> detail2SPList = new List<AsiaProfitCalculationDetail2SP__c>();
        
        try{
            List<AsiaProfitCalculationDetail__c> detailList = createCalculationDetailData(asiaProfitCalculationId);
            
            AsiaProfitCalculationDetail2SP__c detail2SP = new AsiaProfitCalculationDetail2SP__c();
            integer count= detailList.size();
            Id parentId;
            
            for(Integer i = 0; i <count; i++){
                parentId=detailList[i].Id;               
                detail2SP = new AsiaProfitCalculationDetail2SP__c();
                detail2SP.CurrencyIsoCode = 'JPY';
                detail2SP.ProfitCalculationDetail__c = parentId;
                detail2SP.IsSelected__c=true;
                detail2SP.CostPriceJPY__c=17000;
                detail2SPList.add(detail2SP);
            }
            
            insert detail2SPList;
            
            
        }catch(Exception e){
            system.debug('★★★★★★★★★★★★★ AsiaProfitCalculationDetail2SP Insert Error  start ★★★★★★★★');
            system.debug('★★ LineNo' + e.getLineNumber() + ': ' + e.getMessage() + ' ★★');
            system.debug('★★★★★★★★★★★★★ AsiaProfitCalculationDetail2SP Insert Error  end ★★★★★★★★');
        }
        return detail2SPList;
    }
}