objects/AsiaCustomerInformations__c.object
<CustomObject>
    <fields>
        <fullName>CustomerField__c</fullName>
        <label>Field of Customer</label>
        <picklist>
            <picklistValues>
                <fullName>a. Military/Defense</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>b. Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c. Atomic Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>d. Semiconductor (IC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e. Physics/Material</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>f. Chemistry/Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>g. Biology/Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>h. Manufacturing of deuterium oxide(heavy water)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>i. Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ResponsibleUser2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ResponsibleUser2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Informations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponsibleUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ResponsibleUser</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Informations</label>
    <nameField>
        <label>Customer Informations</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_CustomerInformationsCtrlTest.cls
@isTest
private class JEOLAsia_CustomerInformationsCtrlTest {

	private static User testUser = JEOLAsia_TestDataFactory.createTestUser();

	private static testMethod void test01()
	{
		System.runAs (testUser) 
		{
			Test.startTest();

			AsiaCustomerInformations__c rec = new AsiaCustomerInformations__c();
			rec.Name = 'testName';
			rec.ResponsibleUser__c = testUser.Id;
			rec.ResponsibleUser2__c = testUser.Id;
			insert rec;

			AsiaCustomerInformations__c baseRec = new AsiaCustomerInformations__c();

			PageReference pageRef = Page.JEOLAsia_CustomerInformations;
			Test.setCurrentPage(pageRef);
			pageRef.getParameters().put('pcid', String.valueOf(rec.Id));

            JEOLAsia_CustomerInformationsCtrl ctrl = new JEOLAsia_CustomerInformationsCtrl(new ApexPages.StandardController(rec));

			ctrl.getPicklist('AsiaCustomerInformations__c','CustomerField__c');
			ctrl.getCustomerStatusItems();
			ctrl.getFacilityTypeItems();
			ctrl.getCustomerFieldItems();
			ctrl.getCapitalOrExecSomeCountryItems();
			ctrl.getCustomerPastTransactionItems();
			ctrl.getIsResearchEntrustedMilitaryItems();
			ctrl.getABCMWeaponRelatedItems();
			ctrl.getConventionalWeaponRelatedItems();
			ctrl.getEndUseCertificateAvailableItems();
			ctrl.getAssuranceStatementAvailableItems();
			ctrl.getEndUseInspectionPossibilityItems();
			ctrl.getCustomerDeniedPersonItems();
			ctrl.getResponsibleUserTitle();
			ctrl.getResponsibleUser2Title();
			ctrl.getPreviewUrl();
			ctrl.ajaxSaveAction();

			PageReference ret = ctrl.saveAction();

            Test.stopTest();
		}
	}

	private static testMethod void test02()
	{
		System.runAs (testUser) 
		{
			Test.startTest();

			AsiaCustomerInformations__c rec = new AsiaCustomerInformations__c();
			rec.Name = 'testName';
			rec.ResponsibleUser__c = testUser.Id;
			rec.ResponsibleUser2__c = testUser.Id;
			insert rec;

			AsiaCustomerInformations__c baseRec = new AsiaCustomerInformations__c();

			PageReference pageRef = Page.JEOLAsia_CustomerInformations;
			Test.setCurrentPage(pageRef);
			pageRef.getParameters().put('id', String.valueOf(rec.Id));

            JEOLAsia_CustomerInformationsCtrl ctrl = new JEOLAsia_CustomerInformationsCtrl(new ApexPages.StandardController(rec));

			ctrl.getPicklist('AsiaCustomerInformations__c','CustomerField__c');
			ctrl.getCustomerStatusItems();
			ctrl.getFacilityTypeItems();
			ctrl.getCustomerFieldItems();
			ctrl.getCapitalOrExecSomeCountryItems();
			ctrl.getCustomerPastTransactionItems();
			ctrl.getIsResearchEntrustedMilitaryItems();
			ctrl.getABCMWeaponRelatedItems();
			ctrl.getConventionalWeaponRelatedItems();
			ctrl.getEndUseCertificateAvailableItems();
			ctrl.getAssuranceStatementAvailableItems();
			ctrl.getEndUseInspectionPossibilityItems();
			ctrl.getCustomerDeniedPersonItems();
			ctrl.getResponsibleUserTitle();
			ctrl.getResponsibleUser2Title();
			ctrl.getPreviewUrl();
			ctrl.ajaxSaveAction();

			PageReference ret = ctrl.saveAction();

            Test.stopTest();
		}
	}
}