objects/AsiaCustomerInformations__c.object
<CustomObject>
    <fields>
        <fullName>CustomerStatus__c</fullName>
        <label>Customer&apos;s Status</label>
        <picklist>
            <picklistValues>
                <fullName>a. Public</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>b. Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c. Military/Defense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>d. Organization related to [ c ].</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e. Organization similar to [ c &amp; d ].</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ResponsibleUser2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ResponsibleUser2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Informations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponsibleUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ResponsibleUser</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Customer Informations</label>
    <nameField>
        <label>Customer Informations</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_CustomerInfoPrintPageCtrlTest.cls
@isTest
private class JEOLAsia_CustomerInfoPrintPageCtrlTest {

	private static User testUser = JEOLAsia_TestDataFactory.createTestUser();
	public static final String PARAM_ID = 'id';
    public static final String CUSTINFO_OBJ = 'AsiaCustomerInformations__c';
    public static final String EORR_MESSAGE = 'An unexpected error occured.';

    private static testMethod void test01()
    {
    	System.runAs (testUser)
    	{
    		Test.startTest();

    		AsiaCustomerInformations__c rec = new AsiaCustomerInformations__c();
    		rec.Name = 'testName';
			rec.ResponsibleUser__c = testUser.Id;
			rec.ResponsibleUser2__c = testUser.Id;
			insert rec;

			PageReference pageRef = Page.JEOLAsia_CustomerInformationsPrintPage;
			Test.setCurrentPage(pageRef);
			pageRef.getParameters().put('id', String.valueOf(rec.Id));

	        JEOLAsia_CustomerInfoPrintPageCtrl ctrl = new JEOLAsia_CustomerInfoPrintPageCtrl();
	        ctrl.getPicklist('AsiaCustomerInformations__c', 'CustomerStatus__c');
	        ctrl.getCustomerStatusItems();
	        ctrl.getFacilityTypeItems();
	        ctrl.getCustomerFieldItems();
	        ctrl.getCapitalOrExecSomeCountryItems();
	        ctrl.getCustomerPastTransactionItems();
			ctrl.getIsResearchEntrustedMilitaryItems();
			ctrl.getABCMWeaponRelatedItems();
			ctrl.getConventionalWeaponRelatedItems();
			ctrl.getEndUseCertificateAvailableItems();
			ctrl.getAssuranceStatementAvailableItems();
			ctrl.getEndUseInspectionPossibilityItems();
			ctrl.getCustomerDeniedPersonItems();
			ctrl.getResponsibleUserTitle();
		    ctrl.getResponsibleUser2Title();
            String ret = ctrl.dispUrl;
        	Test.stopTest();
    	}
    }

    private static testMethod void test02()
    {
        System.runAs (testUser)
        {
            Test.startTest();

            AsiaCustomerInformations__c rec = new AsiaCustomerInformations__c();
            rec.Name = 'testName';
            rec.ResponsibleUser__c = testUser.Id;
            rec.ResponsibleUser2__c = testUser.Id;
            rec.URL__C = '™©  aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ1234567890!"#$%&(-=^~\\\'|@`[{;+:*]},<.>/?_';
            insert rec;

            PageReference pageRef = Page.JEOLAsia_CustomerInformationsPrintPage;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('id', String.valueOf(rec.Id));

            JEOLAsia_CustomerInfoPrintPageCtrl ctrl = new JEOLAsia_CustomerInfoPrintPageCtrl();
            String ret2 = ctrl.dispUrl;

            Test.stopTest();
        }
    }
}