objects/AsiaMaintenanceAccountBook__c.object
<CustomObject>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <label>Maintenance Contract Management</label>
        <referenceTo>AsiaMaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>Maintenance Account Book (MaintenanceContractManagement)</relationshipLabel>
        <relationshipName>MaintenanceAccountBook</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Maintenance Account Book</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AsiaMaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Maintenance Contract Management</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Maintenance Contract Management No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>系列</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOLAsia_MaintenanceAccountBookRedTest.cls
@isTest
private class JEOLAsia_MaintenanceAccountBookRedTest {

	private static User testUser = JEOLAsia_TestDataFactory.createTestUser();

	private static testMethod void test01()
	{
		System.runAs (testUser)
		{
			Test.startTest();

			AsiaMaintenanceContractManagement__c contMan = new AsiaMaintenanceContractManagement__c();
			contMan.NewOdrSeries__c = 'testAP';
			contMan.NewOdrSalesStaff__c = testUser.Id;
			insert contMan;

			AsiaMaintenanceAccountBook__c accBk = new AsiaMaintenanceAccountBook__c();
			accBk.Name = 'testAMABName';
			accBk.MaintenanceContractManagement__r = contMan;
			accBk.MaintenanceContractManagement__c = contMan.id;
			insert accBk;

	        Pagereference ref = Page.JEOLAsia_MaintenanceAccountBookRedirect;
	        Map<String, String> params = new Map<String, String>();
	        params.put('id', contMan.id);
	        ref.getParameters().putAll(params);
	                               
	        Test.setCurrentPage(ref);

			JEOLAsia_MaintenanceAccountBookRed_ctrl ctrl = new JEOLAsia_MaintenanceAccountBookRed_ctrl(new ApexPages.StandardController(accBk));

			PageReference ret = ctrl.redirect();

			Test.stopTest();
		}
	}
}