objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>取引先カテゴリコード</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>取引先カテゴリ</label>
    <nameField>
        <label>取引先カテゴリ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CategoryJunction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>取引先カテゴリジャンクション</relationshipLabel>
        <relationshipName>AccJunctionLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CategoryName__c</fullName>
        <description>API参照名に注意</description>
        <label>取引先カテゴリコード</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>取引先カテゴリジャンクション</relationshipLabel>
        <relationshipName>JunctionLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>取引先カテゴリジャンクション</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>取引先カテゴリジャンクション</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_AccountCategoryRelatedListCtrl.cls
public with sharing class JEOL_AccountCategoryRelatedListCtrl {

	private CustomRelatedListCtrl relatedListCtrl = null;
	public String parentId{get; set;}
	public String title{get; set;}
	public Boolean isEdit{get; set;}
	public Boolean isSuccess{get; set;}

	public String[] SobjectFields = new String[]{'name','Code__c'};

	public JEOL_AccountCategoryRelatedListCtrl() {
		this.isSuccess = true;
	}

	public CustomRelatedListCtrl getRelatedListCtrl() {
		if (this.relatedListCtrl == null) {
			try {
				this.relatedListCtrl = new CustomRelatedListCtrl(this.SobjectFields, this.parentId);
				this.relatedListCtrl.title = this.title;
			} catch (System.QueryException e) {
				this.isSuccess = false;
				Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage()));//'情報取得エラー'));
			}
		}
		
		return this.relatedListCtrl;
	}

	public class CustomRelatedListCtrl {
		public ApexPages.StandardSetController ssc{get; set;}
		public List<String> fieldNames{get; set;}
		public String sobjectName{get; set;}
		public String viewId{get; set;}
		public String title{get; set;}
		public String targetId{get; set;}
		public String relationshipName{get; set;}
		public String test{get; set;}
		public CustomRelatedListCtrl(List<String> fieldNames, String targetId) {
			if (fieldNames != null && fieldNames.size() > 0) {
				this.fieldNames = fieldNames;
				this.targetId = targetId;
				List<CategoryJunction__c> junctions = [SELECT id, CategoryName__c FROM CategoryJunction__c WHERE Account__c =: targetId];
				if (junctions != null) {
					this.test = String.valueOf(junctions.size());
				}
				Set<String> ids = new Set<String>();
				for (CategoryJunction__c junction: junctions) {
					if (String.isNotBlank(junction.CategoryName__c)) {
						ids.add(junction.CategoryName__c);
					}
				}
				
				String queryStr = ' SELECT ' + String.join(fieldNames,',') + ' FROM Category__c ';
				queryStr += ' WHERE id IN (\'' +  String.join((new List<String>(ids)), '\',\'') + '\')';
				Database.QueryLocator locator = Database.getQueryLocator(queryStr);
				if (locator != null) {
					this.ssc = new ApexPages.StandardSetController(locator);
					this.ssc.setPageSize(5);
					this.ssc.setPageNumber(1);
				}
			}
		}
		
		public List<Sobject> getRecords() {
			List<Sobject> recs;
			if (this.ssc != null) {
				recs = this.ssc.getRecords();
			} else {
				recs = new List<Sobject>();
			}
			return recs;
		}
		
		public Integer getResultSize() {
			Integer resultSize = 0;
			if (this.ssc != null) {
				resultSize = this.ssc.getResultSize();
			}
			return resultSize;
		}
		
		public void AddViewSize() {
			Integer viewSize = 0;
			if (this.ssc != null) {
				Integer currentViewSize = this.ssc.getPageSize();
				viewSize = currentViewSize*2;
				if (80 < viewSize) {
					viewSize = 125;
				}
			}
			this.ssc.setPageSize(viewSize);
		}
		public Integer getCurrentViewSize() {
			Integer viewSize = 0;
			if (this.ssc != null) {
				viewSize = this.ssc.getPageSize();
			}
			return viewSize;
		}
		
		/*public Pagereference getAllRecordViewUrl() {
			Pagereference ref = Page.JEOL_CustomRelatedListAllRecordViewPage;
			Map<String, String> params = new Map<String, String>();
			params.put(JEOL_CustomRelatedListAllRecordViewCtrl.URL_PARAM_SOBJECT, this.sobjectName);
			params.put(JEOL_CustomRelatedListAllRecordViewCtrl.URL_PARAM_FIELD, String.join(this.fieldNames,','));
			params.put(JEOL_CustomRelatedListAllRecordViewCtrl.URL_PARAM_ID, this.targetId);
			params.put(JEOL_CustomRelatedListAllRecordViewCtrl.URL_PARAM_RELATIONSHIP, this.relationshipName);
			ref.getParameters().putAll(params);
			return ref;
		}*/
	}
}