objects/Component__c.object
<CustomObject>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>構成品</relationshipLabel>
        <relationshipName>ItemLink_Component</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <label>シリアル番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>構成品</relationshipLabel>
        <relationshipName>Component</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>構成品</label>
    <nameField>
        <label>構成品</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductItem__c.object
<CustomObject>
    <label>品目</label>
    <nameField>
        <label>品目</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>UnitBodyLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <formula>UnitBodyLink__r.UnitBody__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体号機</label>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitBody__c.object
<CustomObject>
    <fields>
        <fullName>ItemLink__c</fullName>
        <label>品目</label>
        <referenceTo>ProductItem__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>ItemLink</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>本体号機</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SerialNo__c</fullName>
        <label>シリアル番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBody__c</fullName>
        <externalId>true</externalId>
        <label>本体号機</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>本体号機</label>
    <nameField>
        <label>本体号機</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JEOL_NonyusakiShokai_ctrlTest.cls
@IsTest
private class JEOL_NonyusakiShokai_ctrlTest {

    // 販売オーダ指定なし
    private static testMethod void test01() {
        Test.starttest();
        PageReference testPage = Page.JEOL_NonyusakiShokaiPage;
        testPage.getParameters().put('id', '');
        Test.setCurrentPage(testPage);
        
        Apexpages.Standardcontroller stdCtrl = new Apexpages.Standardcontroller(new UnitBody__c());
        JEOL_NonyusakiShokai_ctrl ctrl = new JEOL_NonyusakiShokai_ctrl(stdCtrl);
        Test.stoptest();
    }

    // 販売オーダ該当なし
    private static testMethod void test02() {
        Test.starttest();

        PageReference testPage = Page.JEOL_NonyusakiShokaiPage;
        testPage.getParameters().put('id', '');
        Test.setCurrentPage(testPage);

        Apexpages.Standardcontroller stdCtrl = new Apexpages.Standardcontroller(new UnitBody__c());
        JEOL_NonyusakiShokai_ctrl ctrl = new JEOL_NonyusakiShokai_ctrl(stdCtrl);
        Test.stoptest();
    }

    // 販売オーダ該当あり
    private static testMethod void test03() {
        Test.starttest();

        String salesOrderId = testData();

        PageReference testPage = Page.JEOL_NonyusakiShokaiPage;
        testPage.getParameters().put('id', salesOrderId);
        Test.setCurrentPage(testPage);

        Apexpages.Standardcontroller stdCtrl = new Apexpages.Standardcontroller(new UnitBody__c());
        JEOL_NonyusakiShokai_ctrl ctrl = new JEOL_NonyusakiShokai_ctrl(stdCtrl);
//        ctrl.getSalesOrderNo();
        List<JEOL_NonyusakiShokai_ctrl.PartsItem> parts = ctrl.getPartsItems();
        if (parts.size() > 0) {
            parts.get(0).getModelText();
        }
        Test.stoptest();
    }

    //テストデータ作成
    private static String testData() {

        // 品目
        ProductItem__c pi = new ProductItem__c();
        pi.Name = 'K999999';
        insert pi;

        // シリアル番号付品目
        UnitBody__c ub = new UnitBody__c();
        ub.ItemLink__c = pi.Id;
        ub.Name = 'testSNPIname';
        ub.SerialNo__c = 'testシリアル番号_00001';
        ub.UnitBody__c = 'test本体号機';
        insert ub;
        
        Component__c comp = new Component__c();
        comp.UnitBody__c = ub.id;
        comp.ItemLink__c = pi.id;
        insert comp;

        // 販売オーダ（メイン情報）
        SalesOrder__c so = new SalesOrder__c();
        so.UnitBodyLink__c = ub.Id;
        so.Name = 'testSO';
        insert so;

        return ub.Id;
    }

}