objects/JapaneseEraNameMaster__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>JapaneseCalendarStartDate__c</fullName>
        <label>和暦始期</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>和暦マスタ</label>
</CustomObject>

objects/QuotationDetailInformation__c.object
<CustomObject>
    <fields>
        <fullName>AccompanyingPaperOutput__c</fullName>
        <defaultValue>false</defaultValue>
        <label>別紙出力</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>内容</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Depth__c</fullName>
        <label>Depth</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsDisplayDecimal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gets its value from UserSetting__c&apos;s IsDisplayDecimal__c field.</description>
        <label>isDisplayDecimal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>見積書情報</label>
        <referenceTo>QuotationInformation__c</referenceTo>
        <relationshipLabel>見積書詳細情報</relationshipLabel>
        <relationshipName>QuotationDetailInformations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <label>品目コード</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuantityUnit__c</fullName>
        <label>単位</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>数量</label>
        <precision>8</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuoteNo__c</fullName>
        <formula>LEFT(QuoteNo_BranchNo_SEQ_Sync__c,  FIND(&quot;_&quot;, QuoteNo_BranchNo_SEQ_Sync__c) - 1 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>見積No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>ソート番号</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>単価</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>見積書詳細情報</label>
    <nameField>
        <displayFormat>QT{00000000}</displayFormat>
        <label>見積書詳細</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuotationInformation__c.object
<CustomObject>
    <fields>
        <fullName>CalendarExpress__c</fullName>
        <description>和暦、西暦の表示選択</description>
        <label>暦表示</label>
        <picklist>
            <picklistValues>
                <fullName>和暦</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>西暦</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ContractCode__c</fullName>
        <label>契約先コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractName__c</fullName>
        <label>契約先名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>カスタム値引金額１</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount2__c</fullName>
        <label>カスタム値引金額２</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomReductionAmount3__c</fullName>
        <label>カスタム値引金額３</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomerQuotationRequestedNo__c</fullName>
        <label>客先見積依頼No</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryDate_Arbitrarily__c</fullName>
        <label>納入期日(適宜)</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryDeadline__c</fullName>
        <label>納入期限</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DeliveryLocationText__c</fullName>
        <description>受渡場所区分の入力欄</description>
        <label>受渡場所テキスト</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryPeriod__c</fullName>
        <defaultValue>0</defaultValue>
        <description>御下命後、納入までの月数</description>
        <label>納入期日(月数)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IssueDate__c</fullName>
        <label>発行日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>備考</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OutputConsumptionTaxAmount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>消費税額表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputSubtitle__c</fullName>
        <defaultValue>true</defaultValue>
        <label>小計表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputTotalAmount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>合計金額表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutputTotalTaxAmount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>総合計金額表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PaymentConditionText__c</fullName>
        <description>支払条件区分の入力欄</description>
        <label>支払条件テキスト</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuotationRequestedDate__c</fullName>
        <label>見積依頼日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QuotationType__c</fullName>
        <label>見積種別</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteExpirationDate__c</fullName>
        <label>見積書有効期限</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QuoteNo__c</fullName>
        <description>自社内管理の見積番号</description>
        <label>見積No.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteValidityPeriod__c</fullName>
        <defaultValue>0</defaultValue>
        <label>見積書有効期間</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesArea__c</fullName>
        <label>地域</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当者</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsJapanUser__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>QuotationInformations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentCode__c</fullName>
        <label>納入先コード</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentName__c</fullName>
        <label>納入先名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxExemptionTextOutput__c</fullName>
        <defaultValue>false</defaultValue>
        <label>非課税文言表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isDisplayDecimal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gets its value from UserSetting__c&apos;s IsD</description>
        <label>整数表示フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>見積書情報</label>
    <nameField>
        <label>見積名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/salesperson__c.object
<CustomObject>
    <description>取引先に対して、年度と部門毎の担当者</description>
    <label>営業担当者</label>
    <nameField>
        <displayFormat>sp-{00000000}</displayFormat>
        <label>営業担当者_name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>SalesArea__c</fullName>
        <label>地域</label>
        <picklist>
            <picklistValues>
                <fullName>010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>024</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>026</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>027</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>028</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>029</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>031</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>034</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>045</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>049</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0Z1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>111</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/JEOL_QuotationPrintPageTest.cls
@IsTest
private class JEOL_QuotationPrintPageTest {

    //メソッド呼び出し
    public static testMethod void Test01() {
        // テストデータ生成
        String targetId = testData();
        
        PageReference testPage = Page.JEOL_QuotationPrintPage;//ページ参照型クラス返す(URL情報あり)
        Map<String, String> params = testPage.getParameters();
        params.put('id', targetId);//ID指定
        params.put('print', 'true');
        Test.setCurrentPage(testPage);//コントローラ現在のPageReferenceオブジェクトを設定

        JEOL_QuotationPrintPageCtrl ctrl = new JEOL_QuotationPrintPageCtrl();
        JEOL_QuotationPrintPageCtrl.PageBlock PrintPageCtrl_PageBlock = ctrl.pdfPages.get(0);

        //JEOL_QuotationPrintPageCtrlクラスメソッド
        ctrl.getDetails(targetId);
        
        //PageBlockクラスメソッド
        PrintPageCtrl_PageBlock.getDetailSize();
        PrintPageCtrl_PageBlock.getNoteTextLineSize();
        
        //QuotationHeaderクラスメソッド
        PrintPageCtrl_PageBlock.head.getAmountTotalLineSize();
        PrintPageCtrl_PageBlock.head.getDeliveryLocation();
        PrintPageCtrl_PageBlock.head.getDeliveryPeriod();
        PrintPageCtrl_PageBlock.head.getPaymentCondition();
    }

    //accompanyingPaperDetailRecs処理
    static testMethod void Test02() {
        
        // テストデータ生成
        String targetId = testData2();
        
        //JEOLUtil util = new JEOLUtil();
        //QuotationDetailInformation__c qdi = new QuotationDetailInformation__c();
        //qdi.AccompanyingPaperOutput__c = true;
        
        PageReference testPage = Page.JEOL_QuotationPrintPage;//ページ参照型クラス返す(URL情報あり)
        Map<String, String> params = testPage.getParameters();
        params.put('id', targetId);//ID指定
        params.put('preview', 'true');
        Test.setCurrentPage(testPage);//コントローラ現在のPageReferenceオブジェクトを設定
        
        JEOL_QuotationPrintPageCtrl ctrl = new JEOL_QuotationPrintPageCtrl();
        
    }
    
    //品名0個処理
    static testMethod void Test03() {
        // テストデータ生成
        String targetId = testData3();
        
        PageReference testPage = Page.JEOL_QuotationPrintPage;//ページ参照型クラス返す(URL情報あり)
        Map<String, String> params = testPage.getParameters();
        params.put('id', targetId);//ID指定
        params.put('print', 'true');
        Test.setCurrentPage(testPage);//コントローラ現在のPageReferenceオブジェクトを設定

        JEOL_QuotationPrintPageCtrl ctrl = new JEOL_QuotationPrintPageCtrl();
    }
    //和暦表示テスト
    static testMethod void Test04() {
        // テストデータ生成
        String targetId = testData4();
        PageReference testPage = Page.JEOL_QuotationPrintPage;//ページ参照型クラス返す(URL情報あり)
        Map<String, String> params = testPage.getParameters();
        params.put('id', targetId);//ID指定
        params.put('print', 'true');
        params.put('name', 'testtesttest');
        params.put('year', '2010');
        Test.setCurrentPage(testPage);//コントローラ現在のPageReferenceオブジェクトを設定

        JEOL_QuotationPrintPageCtrl ctrl = new JEOL_QuotationPrintPageCtrl();
        JEOL_QuotationPrintPageCtrl.PageBlock PrintPageCtrl_PageBlock = ctrl.pdfPages.get(0);
        
        //QuotationHeaderクラスメソッド
        PrintPageCtrl_PageBlock.head.getQuotationVlidityPeriod();//JEOL_QuotationPrintPageCtrlクラス→PageBlockクラス→QuotationHeader型head変数のgetQuotationVlidityPeriodメソッドコール
        PrintPageCtrl_PageBlock.head.getQuotationRequestDate();
        PrintPageCtrl_PageBlock.head.getIssueDate();
        PrintPageCtrl_PageBlock.head.getColspan();
    }
    //西暦表示テスト
    static testMethod void Test05() {
        // テストデータ生成
        String targetId = testData5();
        PageReference testPage = Page.JEOL_QuotationPrintPage;//ページ参照型クラス返す(URL情報あり)
        Map<String, String> params = testPage.getParameters();
        params.put('id', targetId);//ID指定
        params.put('print', 'true');
        params.put('name', 'testtesttest');
        params.put('year', '2010');
        Test.setCurrentPage(testPage);//コントローラ現在のPageReferenceオブジェクトを設定

        JEOL_QuotationPrintPageCtrl ctrl = new JEOL_QuotationPrintPageCtrl();
        JEOL_QuotationPrintPageCtrl.PageBlock PrintPageCtrl_PageBlock = ctrl.pdfPages.get(0);
        
        //QuotationHeaderクラスメソッド
        PrintPageCtrl_PageBlock.head.getQuotationVlidityPeriod();//JEOL_QuotationPrintPageCtrlクラス→PageBlockクラス→QuotationHeader型head変数のgetQuotationVlidityPeriodメソッドコール
        PrintPageCtrl_PageBlock.head.getQuotationRequestDate();
        PrintPageCtrl_PageBlock.head.getIssueDate();
        PrintPageCtrl_PageBlock.head.getColspan();
    }
    //MODIFICATION-VAIB-MAY-28-2015
    /*static testMethod void Test06() {
        // テストデータ生成
        String targetId = testData5();
        PageReference testPage = Page.JEOL_QuotationPrintPage;//ページ参照型クラス返す(URL情報あり)
        Map<String, String> params = testPage.getParameters();
        params.put('print', 'true');
        params.put('name', 'testtesttest');
        params.put('year', '2010');
        Test.setCurrentPage(testPage);//コントローラ現在のPageReferenceオブジェクトを設定

        JEOL_QuotationPrintPageCtrl ctrl = new JEOL_QuotationPrintPageCtrl();
        JEOL_QuotationPrintPageCtrl.PageBlock PrintPageCtrl_PageBlock = ctrl.pdfPages.get(0);
        
        //QuotationHeaderクラスメソッド
        PrintPageCtrl_PageBlock.head.getQuotationVlidityPeriod();//JEOL_QuotationPrintPageCtrlクラス→PageBlockクラス→QuotationHeader型head変数のgetQuotationVlidityPeriodメソッドコール
        PrintPageCtrl_PageBlock.head.getQuotationRequestDate();
        PrintPageCtrl_PageBlock.head.getIssueDate();
        PrintPageCtrl_PageBlock.head.getColspan();
    } */

    // テストデータ作成
    private static String testData(){
        QuotationInformation__c rec = new QuotationInformation__c();
        QuotationDetailInformation__c qdi = new QuotationDetailInformation__c();
        
        rec.QuoteNo__c = '11111';
        rec.Name = 'mitumori01';
        rec.CustomerQuotationRequestedNo__c = '22222';
        //rec.SalesPerson__c = 'Admin User';
        rec.ContractCode__c = '44444';
        rec.ContractName__c = 'abc';
        rec.ShipmentCode__c = '55555';
        rec.ShipmentName__c = 'def';
        rec.Series__c = 'EM';
        rec.SalesArea__c = '東京支店';
        rec.QuotationType__c = '保守契';
        rec.TaxExemptionTextOutput__c = true;
        rec.DeliveryPeriod__c = 5807;
        rec.DeliveryDeadline__c = Date.parse('1999/01/01');
        rec.DeliveryDate_Arbitrarily__c = 'DeliveryDate_Arbitrarily';
        rec.QuoteExpirationDate__c = Date.parse('2000/01/01');
        rec.DeliveryLocationText__c = 'DeliveryLocationText';
        rec.PaymentConditionText__c = 'PaymentConditionText';
        rec.QuoteValidityPeriod__c = 100;
        rec.QuotationRequestedDate__c = Date.parse('2001/01/01');
        rec.IssueDate__c = Date.parse('2002/01/01');
        rec.OutputSubtitle__c = true;               //小計表示
        rec.CustomReductionAmount1__c = 500;        //カスタム値引金額１
        rec.CustomReductionAmount2__c = 300;        //カスタム値引金額2
        rec.CustomReductionAmount3__c = 200;        //カスタム値引金額3
        rec.OutputTotalAmount__c = true;            //合計金額表示
        rec.OutputConsumptionTaxAmount__c = true;   //消費税額表示
        rec.OutputTotalTaxAmount__c = true;         //総合計金額表示
        insert rec;

        qdi.Body__c = 'T\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\n';
        qdi.ProductCode__c = '99999';
        qdi.Quantity__c = 9999.0;
        qdi.QuantityUnit__c = '式';
        qdi.UnitPrice__c = 1234567890;
        qdi.Parent__c = rec.id;
        qdi.SortNo__c = 1;
        qdi.Depth__c = 1;
        insert qdi;
        
        return rec.id;
    }

    private static String testData2(){
        QuotationInformation__c rec = new QuotationInformation__c();
        QuotationDetailInformation__c qdi = new QuotationDetailInformation__c();
        
        rec.QuoteNo__c = '11111';
        rec.Name = 'mitumori01';
        rec.CustomerQuotationRequestedNo__c = '22222';
        rec.ContractCode__c = '44444';
        rec.ContractName__c = 'abc';
        rec.ShipmentCode__c = '55555';
        rec.ShipmentName__c = 'def';
        rec.Series__c = 'EM';
        rec.SalesArea__c = '東京支店';
        rec.QuotationType__c = '保守契';
        rec.TaxExemptionTextOutput__c = true;
        rec.DeliveryPeriod__c = 5807;
        rec.DeliveryDeadline__c = Date.parse('1999/01/01');
        rec.DeliveryDate_Arbitrarily__c = 'DeliveryDate_Arbitrarily';
        rec.QuoteExpirationDate__c = Date.parse('2000/01/01');
        rec.DeliveryLocationText__c = 'DeliveryLocationText';
        rec.PaymentConditionText__c = 'PaymentConditionText';
        rec.QuoteValidityPeriod__c = 100;
        rec.QuotationRequestedDate__c = Date.parse('2001/01/01');
        rec.IssueDate__c = Date.parse('2002/01/01');
        rec.OutputSubtitle__c = true;               //小計表示
        rec.CustomReductionAmount1__c = 500;        //カスタム値引金額１
        rec.CustomReductionAmount2__c = 300;        //カスタム値引金額2
        rec.CustomReductionAmount3__c = 200;        //カスタム値引金額3
        rec.OutputTotalAmount__c = true;            //合計金額表示
        rec.OutputConsumptionTaxAmount__c = true;   //消費税額表示
        rec.OutputTotalTaxAmount__c = true;         //総合計金額表示
        insert rec;

        qdi.Body__c = 'T\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\n';
        qdi.ProductCode__c = '99999';
        qdi.Quantity__c = 9999.0;
        qdi.QuantityUnit__c = '式';
        qdi.UnitPrice__c = 1234567890;
        qdi.Parent__c = rec.id;
        qdi.SortNo__c = 1;
        qdi.Depth__c = 1;
        qdi.AccompanyingPaperOutput__c = true;
        insert qdi;
        
        return rec.id;
    }
    
    private static String testData3(){
        QuotationInformation__c rec = new QuotationInformation__c();
        QuotationDetailInformation__c qdi = new QuotationDetailInformation__c();
        
        rec.QuoteNo__c = '11111';
        rec.Name = 'mitumori01';
        rec.CustomerQuotationRequestedNo__c = '22222';
        rec.ContractCode__c = '44444';
        rec.ContractName__c = 'abc';
        rec.ShipmentCode__c = '55555';
        rec.ShipmentName__c = 'def';
        rec.Series__c = 'EM';
        rec.SalesArea__c = '東京支店';
        rec.QuotationType__c = '保守契';
        rec.TaxExemptionTextOutput__c = true;
        rec.DeliveryPeriod__c = 5807;
        rec.DeliveryDeadline__c = Date.parse('1999/01/01');
        rec.DeliveryDate_Arbitrarily__c = 'DeliveryDate_Arbitrarily';
        rec.QuoteExpirationDate__c = Date.parse('2000/01/01');
        rec.DeliveryLocationText__c = 'DeliveryLocationText';
        rec.PaymentConditionText__c = 'PaymentConditionText';
        rec.QuoteValidityPeriod__c = 100;
        rec.QuotationRequestedDate__c = Date.parse('2001/01/01');
        rec.IssueDate__c = Date.parse('2002/01/01');
        rec.OutputSubtitle__c = true;               //小計表示
        rec.CustomReductionAmount1__c = 500;        //カスタム値引金額１
        rec.CustomReductionAmount2__c = 300;        //カスタム値引金額2
        rec.CustomReductionAmount3__c = 200;        //カスタム値引金額3
        rec.OutputTotalAmount__c = true;            //合計金額表示
        rec.OutputConsumptionTaxAmount__c = true;   //消費税額表示
        rec.OutputTotalTaxAmount__c = true;         //総合計金額表示
        insert rec;

        qdi.Body__c = '';
        qdi.ProductCode__c = '99999';
        qdi.Quantity__c = 9999.0;
        qdi.QuantityUnit__c = '式';
        qdi.UnitPrice__c = 1234567890;
        qdi.Parent__c = rec.id;
        qdi.SortNo__c = 1;
        qdi.Depth__c = 1;
        insert qdi;
        
        return rec.id;
    }
    // 
    private static String testData4(){
        QuotationInformation__c rec = new QuotationInformation__c();
        QuotationDetailInformation__c qdi = new QuotationDetailInformation__c();
        JEOL_QuotationListPageCtrl qtiRec = new JEOL_QuotationListPageCtrl();
        JapaneseEraNameMaster__c jenm = new JapaneseEraNameMaster__c();
        
        jenm.JapaneseCalendarStartDate__c = Date.parse('2000/01/01');
        jenm.Name = '平成';//JapaneseEraNameMaster__cがカスタム設定のため値必須
        insert jenm;
        
        rec.QuoteNo__c = '11111';
        rec.Name = 'mitumori01';
        rec.CustomerQuotationRequestedNo__c = '22222';
        //rec.SalesPerson__c = 'Admin User';
        rec.ContractCode__c = '44444';
        rec.ContractName__c = 'abc';
        rec.ShipmentCode__c = '55555';
        rec.ShipmentName__c = 'def';
        rec.Series__c = 'EM';
        rec.SalesArea__c = '東京支店';
        rec.QuotationType__c = '保守契';
        rec.TaxExemptionTextOutput__c = true;
        rec.DeliveryPeriod__c = 5807;
        rec.DeliveryDeadline__c = Date.parse('1999/01/01');
        rec.DeliveryDate_Arbitrarily__c = 'DeliveryDate_Arbitrarily';
        rec.QuoteExpirationDate__c = Date.parse('2000/01/01');
        rec.DeliveryLocationText__c = 'DeliveryLocationText';
        rec.PaymentConditionText__c = 'PaymentConditionText';
        rec.QuoteValidityPeriod__c = 100;
        rec.QuotationRequestedDate__c = Date.parse('2001/01/01');
        rec.IssueDate__c = Date.parse('2002/01/01');
        rec.OutputSubtitle__c = true;               //小計表示
        rec.CustomReductionAmount1__c = 500;        //カスタム値引金額１
        rec.CustomReductionAmount2__c = 300;        //カスタム値引金額2
        rec.CustomReductionAmount3__c = 200;        //カスタム値引金額3
        rec.OutputTotalAmount__c = true;            //合計金額表示
        rec.OutputConsumptionTaxAmount__c = true;   //消費税額表示
        rec.OutputTotalTaxAmount__c = true;         //総合計金額表示
        insert rec;

        qdi.Body__c = 'T\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\n';
        qdi.ProductCode__c = '99999';
        qdi.Quantity__c = 9999.0;
        qdi.QuantityUnit__c = '式';
        qdi.UnitPrice__c = 1234567890;
        qdi.Parent__c = rec.id;
        qdi.SortNo__c = 1;
        qdi.Depth__c = 1;
        insert qdi;
        
        return rec.id;
    }

    private static String testData5(){
        QuotationInformation__c rec = new QuotationInformation__c();
        QuotationDetailInformation__c qdi = new QuotationDetailInformation__c();
        JEOL_QuotationListPageCtrl qtiRec = new JEOL_QuotationListPageCtrl();
        JapaneseEraNameMaster__c jenm = new JapaneseEraNameMaster__c();
        
        jenm.JapaneseCalendarStartDate__c = Date.parse('2000/01/01');
        jenm.Name = '平成';//JapaneseEraNameMaster__cがカスタム設定のため値必須
        insert jenm;
        
        rec.QuoteNo__c = '11111';
        rec.Name = 'mitumori01';
        rec.CustomerQuotationRequestedNo__c = '22222';
        //rec.SalesPerson__c = 'Admin User';
        rec.ContractCode__c = '44444';
        rec.ContractName__c = 'abc';
        rec.ShipmentCode__c = '55555';
        rec.ShipmentName__c = 'def';
        rec.Series__c = 'EM';
        rec.SalesArea__c = '東京支店';
        rec.QuotationType__c = '保守契';
        rec.TaxExemptionTextOutput__c = true;
        rec.DeliveryPeriod__c = 5807;
        rec.DeliveryDeadline__c = Date.parse('1999/01/01');
        rec.DeliveryDate_Arbitrarily__c = 'DeliveryDate_Arbitrarily';
        rec.QuoteExpirationDate__c = Date.parse('2000/01/01');
        rec.DeliveryLocationText__c = 'DeliveryLocationText';
        rec.PaymentConditionText__c = 'PaymentConditionText';
        rec.QuoteValidityPeriod__c = 100;
        rec.QuotationRequestedDate__c = Date.parse('2001/01/01');
        rec.IssueDate__c = Date.parse('2002/01/01');
        rec.CalendarExpress__c = '西暦';
        rec.OutputSubtitle__c = true;               //小計表示
        rec.CustomReductionAmount1__c = 500;        //カスタム値引金額１
        rec.CustomReductionAmount2__c = 300;        //カスタム値引金額2
        rec.CustomReductionAmount3__c = 200;        //カスタム値引金額3
        rec.OutputTotalAmount__c = true;            //合計金額表示
        rec.OutputConsumptionTaxAmount__c = true;   //消費税額表示
        rec.OutputTotalTaxAmount__c = true;         //総合計金額表示
        rec.Note__c = 'No\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\nNo\n';
        rec.IsDisplayDecimal__c = false;
        insert rec;

        qdi.Body__c = 'T\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\nT\n';
        qdi.ProductCode__c = '99999';
        qdi.Quantity__c = 9999.0;
        qdi.QuantityUnit__c = '式';
        qdi.UnitPrice__c = 1234567890;
        qdi.Parent__c = rec.id;
        qdi.SortNo__c = 1;
        qdi.Depth__c = 1;
        insert qdi;
        
        return rec.id;
    }
}