objects/MaintenanceAccountBook__c.object
<CustomObject>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <label>保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>管理台帳</relationshipLabel>
        <relationshipName>MaintenanceAccountBook</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>保守管理台帳</label>
    <nameField>
        <label>月</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOL_MaintenanceAccountBookRedirect_ctrl.cls
public with sharing class JEOL_MaintenanceAccountBookRedirect_ctrl {

    String sParentID = null;
    String sType = null;
    
    public JEOL_MaintenanceAccountBookRedirect_ctrl(ApexPages.StandardController stdController) {
    
        if(!Test.isRunningTest()) {
            stdController.addFields(new List<String>{'MaintenanceContractManagement__r'});
            stdController.addFields(new List<String>{'Type__c'});
        }
        MaintenanceAccountBook__c accBk = (MaintenanceAccountBook__c) stdController.getRecord();
        If (accBk != null && accBk.id != null && accBk.MaintenanceContractManagement__r != null) {
            sParentID = '' + accBk.MaintenanceContractManagement__r.id;
        }
        If (accBk != null && accBk.id != null && accBk.Type__c != null) {
            sType = '' + accBk.Type__c;
        }
    
    }
    
    public PageReference redirect(){
        if(sParentID != null){
            PageReference pageRef = new PageReference('/apex/JEOL_MaintenanceAccountBook');
            pageRef.getParameters().put('id', sParentID);
            if (sType != null) {
                pageRef.getParameters().put('type', sType);            
            }
            return pageRef;
            
        } else {
            return null;
        }
    }
    
}