objects/MaintenanceAccountBook__c.object
<CustomObject>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <label>保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>管理台帳</relationshipLabel>
        <relationshipName>MaintenanceAccountBook</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>保守管理台帳</label>
    <nameField>
        <label>月</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>BillingMethodHelium__c</fullName>
        <label>請求方法（ヘリウム）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingMethodHontai__c</fullName>
        <label>請求方法（本体）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrMaintenanceEndDate__c</fullName>
        <label>保守契約終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrMaintenanceStartDate__c</fullName>
        <label>保守契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrNetMaintenance__c</fullName>
        <label>NET保守区分</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrRegion__c</fullName>
        <label>地域</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.SalesAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.SalesAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (販売先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>系列</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ShipmentAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ShipmentAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (出荷先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuotationSentDate__c</fullName>
        <label>見積書送付日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubAmountHelium__c</fullName>
        <label>台帳金額（ヘリウム）</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubAmountHontaiNoInspec__c</fullName>
        <label>台帳金額（本体、点検無し）</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JEOL_MaintenanceAccountBookRed_ctrlTest.cls
@isTest
private class JEOL_MaintenanceAccountBookRed_ctrlTest {
    private static Date startDate = Date.newInstance(2015, 5, 1);
    private static Date endDate = Date.newInstance(2015, 5, 30);
    // User
    private static User testUser = JEOL_TestDataFactory.createTestUser();
    // Account
    private static Account testAccount = JEOL_TestDataFactory.createAccountTestObject('TestAccountName01', '000000001', false, '有効', false, '有効');
    /*
     * Description: Test Constructor(コンストラクターテスト)
     * MethodName : JEOL_MaintenanceAccountBookRed_ctrl_Test01
     */
    private static testMethod void  JEOL_MaintenanceAccountBookRed_ctrl_Test01() {
        // preparation
        MaintenanceAccountBook__c testMab = createTestData();
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAccountBookRedirect;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('type', '2');
        ApexPages.StandardController sc = new ApexPages.StandardController(testMab);

        //Test Start
        Test.startTest();
        JEOL_MaintenanceAccountBookRedirect_ctrl ctrl = new JEOL_MaintenanceAccountBookRedirect_ctrl(sc);
        //Test Stop
        Test.stopTest();
	}

    /*
     * Description: Test Constructor(コンストラクターテスト)
     * MethodName : JEOL_MaintenanceAccountBookRed_ctrl_Test02
     */
    private static testMethod void  JEOL_MaintenanceAccountBookRed_ctrl_Test02() {
        // preparation
        MaintenanceAccountBook__c testMab = createTestData();
        MaintenanceAccountBook__c testMab2 = [SELECT Id, Name, Type__c,MaintenanceContractManagement__r.Id
                                              FROM MaintenanceAccountBook__c
                                              WHERE Id =:testMab.Id];
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAccountBookRedirect;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('type', '2');
        ApexPages.StandardController sc = new ApexPages.StandardController(testMab2);

        //Test Start
        Test.startTest();
        JEOL_MaintenanceAccountBookRedirect_ctrl ctrl = new JEOL_MaintenanceAccountBookRedirect_ctrl(sc);
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test redirect Method
     * MethodName : redirect_Test01
     */
    private static testMethod void  redirect_Test01() {
        // preparation
        MaintenanceAccountBook__c testMab = createTestData();
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAccountBookRedirect;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('type', '2');
        ApexPages.StandardController sc = new ApexPages.StandardController(testMab);

        //Test Start
        Test.startTest();
        JEOL_MaintenanceAccountBookRedirect_ctrl ctrl = new JEOL_MaintenanceAccountBookRedirect_ctrl(sc);
        ctrl.redirect();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test redirect Method
     * MethodName : redirect_Test02
     */
    private static testMethod void  redirect_Test02() {
        // preparation
        MaintenanceAccountBook__c testMab = createTestData();
        MaintenanceAccountBook__c testMab2 = [SELECT Id, Name, Type__c,MaintenanceContractManagement__r.Id
                                              FROM MaintenanceAccountBook__c
                                              WHERE Id =:testMab.Id];
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAccountBookRedirect;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('type', '2');
        ApexPages.StandardController sc = new ApexPages.StandardController(testMab2);

        //Test Start
        Test.startTest();
        JEOL_MaintenanceAccountBookRedirect_ctrl ctrl = new JEOL_MaintenanceAccountBookRedirect_ctrl(sc);
        ctrl.redirect();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Create Test Data (テストデータ作成)
     * MethodName: createTestData
     * @ return MaintenanceAccountBook__c(保守台帳管理)
     */
    private static MaintenanceAccountBook__c createTestData(){
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate);
        MaintenanceAccountBook__c mab = new MaintenanceAccountBook__c();
        mab.Type__c = '2';
        mab.MaintenanceContractManagement__c = testMcm.Id;
        System.runAs (testUser) {
            insert mab;
        }
        //insert mab;
        return mab;
    }

    /*
     * Create MaintenanceContractManagement TestData(保守契約管理テストデータ作成)
     * @ parameter Date startDay (保守契約管理.保守契約開始日)
     * @ parameter Date endDay (保守契約管理.保守契約終了日)
     * @ return 保守契約管理
     */
    private static MaintenanceContractManagement__c createTestData01(Date startDay, Date endDay){
        //MaintenanceContractManagement(保守契約管理レコード作成)
        MaintenanceContractManagement__c mcm = new MaintenanceContractManagement__c();
        mcm.NewOdrSalesAccount__c = testAccount.Id;
        mcm.NewOdrShipmentAccount__c = testAccount.Id;
        mcm.NewOdrSalesStaff__c = testUser.Id;
        mcm.NewOdrNetMaintenance__c = 'No';
        mcm.NewOdrSeries__c = 'CA';
        mcm.NewOdrRegion__c = '東京支店';
        mcm.QuotationSentDate__c = startDay;
        mcm.NewOdrMaintenanceStartDate__c = startDay;
        mcm.NewOdrMaintenanceEndDate__c = endDay;
        mcm.BillingMethodHontai__c = '請求方法';
        mcm.BillingMethodHelium__c = '請求方法';
        mcm.SubAmountHontaiNoInspec__c = 3000;
        mcm.SubAmountHelium__c = 2000;
        System.runAs (testUser) {
            insert mcm;
        }
        //insert mcm;
        return mcm;
    }
}