objects/MaintenanceContractManagement__c.object
<CustomObject>
    <fields>
        <fullName>BillingMethodHelium__c</fullName>
        <label>請求方法（ヘリウム）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingMethodHontai__c</fullName>
        <label>請求方法（本体）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewContractEndDate__c</fullName>
        <label>契約完了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewContractStartDate__c</fullName>
        <label>契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrMaintenanceEndDate__c</fullName>
        <label>保守契約終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrMaintenanceStartDate__c</fullName>
        <label>保守契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewOdrNetMaintenance__c</fullName>
        <label>NET保守区分</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrRegion__c</fullName>
        <label>地域</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.SalesAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.SalesAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (販売先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSalesStaff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>営業担当</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MDM_SalesStaff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewOdrSeries__c</fullName>
        <label>系列</label>
        <picklist>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewOdrShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ShipmentAccountFlag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.ShipmentAccountSituation__c</field>
                <operation>notEqual</operation>
                <value>無効</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保守契約管理 (出荷先取引先)</relationshipLabel>
        <relationshipName>SalesOdr_Pipeline_Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreviousYearOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>前年オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipName>PreviousYearOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuotationSentDate__c</fullName>
        <label>見積書送付日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RenewalAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客先名</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RenewalAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RenewalOptionDateFormat__c</fullName>
        <label>西暦/和暦</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubAmountHelium__c</fullName>
        <label>台帳金額（ヘリウム）</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubAmountHontaiNoInspec__c</fullName>
        <label>台帳金額（本体、点検無し）</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>保守契約管理</label>
    <nameField>
        <displayFormat>PLM-{00000000}</displayFormat>
        <label>Pipeline No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>MaintenanceContractManagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>保守契約管理</label>
        <referenceTo>MaintenanceContractManagement__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder_MaintenancePL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaintenanceEndDate__c</fullName>
        <label>保守契約終了日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MaintenanceStartDate__c</fullName>
        <label>保守契約開始日（旧）</label>
        <type>DateTime</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <recordTypes>
        <fullName>SalesOrder</fullName>
        <active>true</active>
        <label>販売オーダ</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_MaintenanceAnnaiPrintPageCtrlTest.cls
@isTest
private class JEOL_MaintenanceAnnaiPrintPageCtrlTest {
	private static Date startDate = Date.newInstance(2015, 5, 1);
    private static Date endDate = Date.newInstance(2015, 5, 30);
    //User(ユーザ)
    private static  User testUser = JEOL_TestDataFactory.createTestUser();
    // Account
    private static Account testAccount = JEOL_TestDataFactory.createAccountTestObject('TestAccountName01', '000000001', false, '有効', false, '有効');
    /*
     * Description: Test Constructor(コンストラクターテスト)
     * MethodName : JEOL_MaintenanceAnnaiPrintPageCtrl_Test01
     */
    private static testMethod void JEOL_MaintenanceAnnaiPrintPageCtrl_Test01() {
        // prepration
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate, true, true);
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAnnaiPrintPage_1Page;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', testMcm.Id);
        testPage.getParameters().put('preview', 'preview');
        testPage.getParameters().put('print', 'print');
        //Test Start
        Test.startTest();
        JEOL_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOL_MaintenanceAnnaiPrintPageCtrl();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test Constructor(コンストラクターテスト)
     * MethodName : JEOL_MaintenanceAnnaiPrintPageCtrl_Test02
     */
    private static testMethod void JEOL_MaintenanceAnnaiPrintPageCtrl_Test02() {
        // prepration
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate, false, false);
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAnnaiPrintPage_1Page;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', testMcm.Id);
        testPage.getParameters().put('preview', 'preview');
        testPage.getParameters().put('print', 'print');
        //Test Start
        Test.startTest();
        JEOL_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOL_MaintenanceAnnaiPrintPageCtrl();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test getPageSize Method
     * MethodName : getPageSize_Test
     */
    private static testMethod void getPageSize_Test() {
        // prepration
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate, true, true);
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAnnaiPrintPage_1Page;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', testMcm.Id);
        testPage.getParameters().put('preview', 'preview');
        testPage.getParameters().put('print', 'print');
        //Test Start
        Test.startTest();
        JEOL_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOL_MaintenanceAnnaiPrintPageCtrl();
        ctrl.getPageSize();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test getPrintDate Method
     * MethodName : getPrintDate_Test
     */
    private static testMethod void getPrintDate_Test() {
        // prepration
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate, true, true);
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAnnaiPrintPage_1Page;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', testMcm.Id);
        testPage.getParameters().put('preview', 'preview');
        testPage.getParameters().put('print', 'print');
        //Test Start
        Test.startTest();
        JEOL_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOL_MaintenanceAnnaiPrintPageCtrl();
        ctrl.getPrintDate();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test getNewContractStartDate Method
     * MethodName : getNewContractStartDate_Test
     */
    private static testMethod void getNewContractStartDate_Test() {
        // prepration
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate, true, true);
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAnnaiPrintPage_1Page;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', testMcm.Id);
        testPage.getParameters().put('preview', 'preview');
        testPage.getParameters().put('print', 'print');
        //Test Start
        Test.startTest();
        JEOL_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOL_MaintenanceAnnaiPrintPageCtrl();
        ctrl.getNewContractStartDate();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test getNewContractEndDate Method
     * MethodName : getNewContractEndDate_Test
     */
    private static testMethod void getNewContractEndDate_Test() {
        // prepration
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate, true, true);
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAnnaiPrintPage_1Page;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', testMcm.Id);
        testPage.getParameters().put('preview', 'preview');
        testPage.getParameters().put('print', 'print');
        //Test Start
        Test.startTest();
        JEOL_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOL_MaintenanceAnnaiPrintPageCtrl();
        ctrl.getNewContractEndDate();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test getMaintenanceStartDateFormula Method
     * MethodName : getMaintenanceStartDateFormula_Test
     */
    private static testMethod void getMaintenanceStartDateFormula_Test() {
        // prepration
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate, true, true);
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAnnaiPrintPage_1Page;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', testMcm.Id);
        testPage.getParameters().put('preview', 'preview');
        testPage.getParameters().put('print', 'print');
        //Test Start
        Test.startTest();
        JEOL_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOL_MaintenanceAnnaiPrintPageCtrl();
        ctrl.getMaintenanceStartDateFormula();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description: Test getMaintenanceEndDateFormula Method
     * MethodName : getMaintenanceEndDateFormula_Test
     */
    private static testMethod void getMaintenanceEndDateFormula_Test() {
        // prepration
        //MaintenanceContractManagement(保守契約管理)
        MaintenanceContractManagement__c testMcm = createTestData01(startDate, endDate, false, true);
        // Set Page
        PageReference testPage = Page.JEOL_MaintenanceAnnaiPrintPage_1Page;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', testMcm.Id);
        testPage.getParameters().put('preview', 'preview');
        testPage.getParameters().put('print', 'print');
        //Test Start
        Test.startTest();
        JEOL_MaintenanceAnnaiPrintPageCtrl ctrl = new JEOL_MaintenanceAnnaiPrintPageCtrl();
        ctrl.getMaintenanceEndDateFormula();
        //Test Stop
        Test.stopTest();
    }

    /*
     * Description:Create MaintenanceContractManagement TestData(保守契約管理テストデータ作成)
     * MethodName :createTestData01
     * @ parameter Date startDay (保守契約管理.保守契約開始日)
     * @ parameter Date endDay (保守契約管理.保守契約終了日)
     * @ parameter Boolean existAccount (true:保守契約管理.客先名あり)
     * @ parameter Boolean existSalesOrder (true:保守契約管理.販売オーだあり)
     * @ return 保守契約管理
     */
    private static MaintenanceContractManagement__c createTestData01(Date startDay, Date endDay, Boolean existAccount, Boolean existSalesOrder){
        // SalesOrder (販売オーダ)
        RecordType salesOrderRecTypes = JEOL_TestDataFactory.getRecordType('SalesOrder__c');
        Datetime startDt = Datetime.newInstance(2014, 5, 1, 19, 30, 30);
        Datetime endDt = Datetime.newInstance(2015, 5, 1, 19, 30, 30);
        //SalesOrder
        SalesOrder__c salesOrder = new SalesOrder__c();
        salesOrder.RecordTypeId = salesOrderRecTypes.Id;
        salesOrder.Name = 'TestSalesOrderNo.0001';
        salesOrder.MaintenanceStartDate__c = startDt;
        salesOrder.MaintenanceEndDate__c = endDt;
        System.runAs (testUser) {
            insert salesOrder;
        }
        //insert salesOrder;

        //MaintenanceContractManagement(保守契約管理レコード作成)
        MaintenanceContractManagement__c mcm = new MaintenanceContractManagement__c();
        mcm.NewOdrSalesAccount__c = testAccount.Id;
        mcm.NewOdrShipmentAccount__c = testAccount.Id;
        mcm.NewOdrSalesStaff__c = testUser.Id;
        mcm.NewOdrNetMaintenance__c = 'No';
        mcm.NewOdrSeries__c = 'CA';
        mcm.NewOdrRegion__c = '東京支店';
        mcm.QuotationSentDate__c = startDay;
        mcm.NewOdrMaintenanceStartDate__c = startDay;
        mcm.NewContractStartDate__c = startDay;
        mcm.NewContractEndDate__c = endDay;
        if(existAccount){
            mcm.RenewalOptionDateFormat__c = '1';
        }else{
            mcm.RenewalOptionDateFormat__c = '2';
        }

        mcm.NewOdrMaintenanceEndDate__c = endDay;
        mcm.BillingMethodHontai__c = '請求方法';
        mcm.BillingMethodHelium__c = '請求方法';
        mcm.SubAmountHontaiNoInspec__c = 3000;
        mcm.SubAmountHelium__c = 2000;
        if(existAccount){
            mcm.RenewalAccount__c = testAccount.Id;
        }
        if(existSalesOrder){
            mcm.PreviousYearOrder__c = salesOrder.Id;
        }
        System.runAs (testUser) {
            insert mcm;
        }
        //insert mcm;
        return mcm;
    }
}