objects/MaintenancePurchaseManagement__c.object
<CustomObject>
    <description>購買管理</description>
    <fields>
        <fullName>HeliumFillingImplementationDate__c</fullName>
        <label>ヘリウム充填実施日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsAcceptanceSettled__c</fullName>
        <label>検収済</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractPeriodEnd__c</fullName>
        <formula>MaintenanceContractManagement__r.NewOdrMaintenanceEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約期間(終了)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractPeriodStart__c</fullName>
        <formula>MaintenanceContractManagement__r.NewOdrMaintenanceStartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約期間(開始)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaintenanceContractPeriod__c</fullName>
        <formula>IF( NOT(ISNULL(MaintenanceContractPeriodStart__c)) || NOT(ISNULL(MaintenanceContractPeriodEnd__c)), (TEXT(MaintenanceContractPeriodStart__c) &amp; &apos; - &apos;  &amp; TEXT(MaintenanceContractPeriodEnd__c)),&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約期間</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSNRInspectionImplementationDate__c</fullName>
        <label>NSNR点検実施日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NSRegularInspectionImplementationDate__c</fullName>
        <label>NS定期自主検査実施日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>支払タイプ</label>
        <picklist>
            <picklistValues>
                <fullName>HELIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <formula>MaintenanceContractManagement__r.ProductNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>製番</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchasingOffice__c</fullName>
        <label>購買オフィス</label>
        <picklist>
            <picklistValues>
                <fullName>PR033</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR034</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR035</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR036</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR037</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR038</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR039</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR041</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR042</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR043</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PJ049</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PurchasingOrder__c</fullName>
        <label>購買オーダ</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionName__c</fullName>
        <formula>MaintenanceContractManagement__r.NewOdrRegion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>地域</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentCustomerAccount__c</fullName>
        <formula>MaintenanceContractManagement__r.NewOdrShipmentAccount__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>出荷先取引先</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupplierCustomerCode__c</fullName>
        <label>購買先取引先</label>
        <picklist>
            <picklistValues>
                <fullName>0294</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0330</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0347</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0461</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0471</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0579</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0593</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0596</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0599</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0764</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1256</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1408</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1793</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1794</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1885</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1902</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2385</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2391</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3207</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3209</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3256</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3261</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3262</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3264</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3266</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3267</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3268</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3273</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3295</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3315</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UnitBodyNumber__c</fullName>
        <formula>MaintenanceContractManagement__r.UnitBody__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>本体番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WarehousePlanningDate__c</fullName>
        <label>計画入庫日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WarehousePlanningMonth__c</fullName>
        <formula>LPAD(TEXT(YEAR(WarehousePlanningDate__c)), 4, &apos;0&apos;) + LPAD(TEXT(MONTH(WarehousePlanningDate__c)), 2, &apos;0&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WarehousePlanningMonth</label>
        <type>Text</type>
    </fields>
    <label>保守購買管理</label>
    <nameField>
        <label>保守購買管理名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SelectListManage__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>表示名称</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceName__c</fullName>
        <label>選択リスト参照名</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>値</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>選択リスト管理</label>
    <nameField>
        <label>選択リストグループ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/JEOL_MaintenancePurchaseSearchListCtrl.cls
public with sharing class JEOL_MaintenancePurchaseSearchListCtrl extends JEOL_SearchBase_ctrl  {
    
    //VFPage binded properties
    public String purchasingOffice {get;set;}
    public String supplierCustomerCode{get;set;}
    public String paymentType {get;set;}
    public String unitBodyNumber {get;set;}
    public String scheduledDeliverDate{get;set;}
    public Date contractStartDateFrom {get;set;}
    public Date contractStartDateTo {get;set;}
    public Date contractEndDateFrom {get;set;}
    public Date contractEndDateTo {get;set;}
    public String shippingCustomerName {get;set;}
    public String isAcceptanceSettled {get;set;}

    private List<String> targetRegions;
    public List<OptionDetail> RegionsOptions{get; set;}

    public Map<String, String> mapRegionName { get; set; }

    //For storing paging-preference of the user in cookies, for searched table
    private static final String COOKIE_LABEL_PAGE_NUMBER = 'PageNumber';
    private static final String COOKIE_LABEL_PAGE_SIZE = 'PageSize';
    private static final String COOKIE_PATH = '/apex/JEOL_MaintenancePurchaseSearchListPage';
    private static final String COOKIE_LABEL_INIT_SEARCH_FLG = 'initSearchFlg';  // 画面起動時検索フラグ

    //For storing user-entered values in cookies
    private static final String COOKIE_VALUE_PURCHASING_OFFICE = 'PurchasingOfficeVal';
    private static final String COOKIE_VALUE_SHIPTO_CUSTOMER = 'ShipToCustomerVal';
    private static final String COOKIE_VALUE_SUPPLIERCUSTOMER_CODE = 'SupplierCustomerCodeVal';
    private static final String COOKIE_VALUE_PAYMENT_TYPE = 'PaymentTypeVal';
    private static final String COOKIE_VALUE_UNITBODY_NUMBER = 'UnitBodyNumberVal';
    private static final String COOKIE_VALUE_MAINTENANCE_CONTRACTSTARTDATE_FROM = 'MaintenanceContractStartDateFromVal';
    private static final String COOKIE_VALUE_MAINTENANCE_CONTRACTSTARTDATE_TO = 'MaintenanceContractStartDateToVal';
    private static final String COOKIE_VALUE_MAINTENANCE_CONTRACTENDDATE_FROM = 'MaintenanceContractEndDateFromVal';
    private static final String COOKIE_VALUE_MAINTENANCE_CONTRACTENDDATE_TO = 'MaintenanceContractEndDateToVal';
    private static final String COOKIE_VALUE_SCHEDULED_DELIVERYDATE  = 'ScheduledDeliveryDateVal';
    private static final String COOKIE_VALUE_ISACCEPTANCESETTLED = 'IsAcceptanceSettled';
    private static final String COOKIE_LABEL_TARGETREGIONS = 'JEOL_MaintenanceInspectionList_TargetRegions';

    private List<SelectListManage__c> lsRegion;

    //Payment types
    public String paymentTypeBLANK {
        get{return JEOL_MaintenancePurchaseSearchList_Utils.paymentTypeBLANK;}
    }
    public String paymentTypeNR {
        get{return JEOL_MaintenancePurchaseSearchList_Utils.paymentTypeNR;}
    }
    public String paymentTypeNS {
        get{return JEOL_MaintenancePurchaseSearchList_Utils.paymentTypeNS;}
    }
    public String paymentTypeHELIUM {
        get{return JEOL_MaintenancePurchaseSearchList_Utils.paymentTypeHELIUM;}
    }
    //

    public List<SelectOption> getIsAcceptanceSettledOptions() {
        list<SelectOption> options = new list<SelectOption>();
        options.add(new SelectOption('', ''));
        options.add(new SelectOption('Yes', '検収済'));
        options.add(new SelectOption('No', '未検収'));    
        return options;
    }

    public void regionsSelectCancel() {
        List<OptionDetail> regionsOptions = this.RegionsOptions;
        for (OptionDetail detail: RegionsOptions) {
            detail.cancel();
        }
    }

    public void RegionsSelectApply() {
        Set<String> regions = new Set<String>();
        List<OptionDetail> regionsOptions = this.RegionsOptions;
        for (OptionDetail detail: regionsOptions) {
            detail.apply();
            if (detail.isSelected) {
                regions.add(detail.option.getValue());
            }
        }
        targetRegions = new List<String>(regions);
    }

    public void regionsSelectAllSelect() {
        List<OptionDetail> regionsOptions = this.RegionsOptions;
        for (OptionDetail detail: regionsOptions) {
            detail.isSelected = true;
        }
    }

    public void regionsSelectAllDeselect() {
        List<OptionDetail> regionsOptions = this.RegionsOptions;
        for (OptionDetail detail: regionsOptions) {
            detail.isSelected = false;
        }
    }
    
    public String getSelectedRegions() {
        String value = 'なし';
        Integer selectedCount = 0;
        Set<String> regions = new Set<String>();
        for (OptionDetail detail: this.RegionsOptions) {
            if (detail.isSelected) {
                regions.add(detail.option.getLabel());
                selectedCount++;
            }
        }
        if (selectedCount == this.RegionsOptions.size()) {
            value = 'すべて';
        } else if (regions.size() > 0) {
            value = String.join(new List<String>(regions), ', ');
        }
        return value;
    }


    private String initSearchFlg = '';
    //
    public class appException extends Exception {}

    public JEOL_MaintenancePurchaseSearchListCtrl() {

        lsRegion = [SELECT id, Value__c, Label__c from SelectListManage__c where ReferenceName__c = :JEOLUtil.REFERENCE_NAME_MAINTENANCE_AREA];

        //mpm = new MaintenancePurchaseManagement__c();
        initSortingOrderVars();
        //Read and Parse values in Cookies
        initFieldFromCookie();


        List<optionDetail> regionsOptions = new List<optionDetail>();
        Set<String> regions;
        if (this.targetRegions != null) {
            regions = new Set<String>(this.targetRegions);
        }
        for (SelectOption option: JEOLUtil.getSelectList(false, JEOLUtil.REFERENCE_NAME_MAINTENANCE_AREA)) {
            Boolean isSelected = false;
            if (regions != null) {
                isSelected = regions.contains(option.getValue());
            }
            regionsOptions.add(new OptionDetail(option, isSelected)); 
        }
        this.regionsOptions = regionsOptions;


        Boolean hasSearchValues = (this.initSearchFlg == 'true') ? true : false;
        if(hasSearchValues) //should search if cookies are present or params are passed
            setStandardSetController();
    }

    //When Search button is pressed on VFPage
    public void doSearch() {
        this.initSearchFlg = 'true';

        setStandardSetController();
        saveInputValuesInCookies();    }

    //When Clear button is pressed on VFPage
    public void doClear() {

        //clear properties
        this.initSearchFlg = '';
        this.contractStartDateFrom = null;
        this.contractStartDateTo = null;
        this.contractEndDateFrom = null;
        this.contractEndDateTo = null;
        this.scheduledDeliverDate = null;

        this.purchasingOffice = null;
        this.paymentType = null;
        this.purchasingOffice = null;
        this.shippingCustomerName = null;
        //this.mpm.ShipmentCustomerAccount__c = null;

        this.targetRegions = null;
        for (OptionDetail detail: this.RegionsOptions) {
            detail.setSelected(false);
        }

        ssc = null;
        // 画面起動時検索フラグOFF
        this.initSearchFlg = '';
        //ページ初期化
        pageNo = 1;
        pageSize = 50;
        saveInputValuesInCookies();
    }


    private String addWhereClauses(String soql){
        Boolean useAnd = false;

        //Purchasing office
        if((purchasingOffice != null) && (purchasingOffice != '')){
            if(!useAnd) soql += ' WHERE ';
            soql += JEOLUtil.appendAfterLikeText(' PurchasingOffice__c', purchasingOffice);
            useAnd = true;
        }

        //Supplier code
        if((supplierCustomerCode != null) && (supplierCustomerCode != '')){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += JEOLUtil.appendAfterLikeText(' SupplierCustomerCode__c', supplierCustomerCode);
            useAnd = true;
        }

        //Payment type
        if((paymentType != null) && (paymentType != paymentTypeBLANK)){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += JEOLUtil.appendEqualText(' PaymentType__c', paymentType);
            useAnd = true;
        }

        //UnitBody
        if((unitBodyNumber != null) && (unitBodyNumber != '')){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += JEOLUtil.appendAfterLikeText(' UnitBodyNumber__c', unitBodyNumber);
            useAnd = true;
        }

        //Region name
        if (this.targetRegions != null && this.targetRegions.size() > 0) {
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += JEOLUtil.appendInText('RegionName__c', this.targetRegions);
            useAnd = true;
        }

        //Customer name
        if((shippingCustomerName != null) && (shippingCustomerName != '')){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += JEOLUtil.appendLikeText(' ShipmentCustomerAccount__c', shippingCustomerName);
            useAnd = true;
        }

        //isAcceptanceSettled
        if((isAcceptanceSettled != null) && (isAcceptanceSettled != '')){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += JEOLUtil.appendAfterLikeText('isAcceptanceSettled__c', isAcceptanceSettled);
            useAnd = true;
        }

        //Delivery date
        if((scheduledDeliverDate != null) && (scheduledDeliverDate != '')){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += '(WarehousePlanningMonth__c != null AND WarehousePlanningMonth__c <= \'' + (String.escapeSingleQuotes(scheduledDeliverDate) + '999999').substring(0, 6) + '\')';
            useAnd = true;
        }

        //Contract Start Date
        if(contractStartDateFrom != null){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += ' MaintenanceContractPeriodStart__c >= ' + String.valueOf(contractStartDateFrom) ;
            useAnd = true;
        }
        if(contractStartDateTo != null){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += ' MaintenanceContractPeriodStart__c <= ' + String.valueOf(contractStartDateTo); 
            useAnd = true;
        }

        //Contract End Date
        if(contractEndDateFrom != null){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += ' MaintenanceContractPeriodEnd__c >= ' + String.valueOf(contractEndDateFrom) ;
            useAnd = true;
        }
        if(contractEndDateTo != null){
            if(!useAnd) soql += ' WHERE '; else soql += ' AND ';
            soql += ' MaintenanceContractPeriodEnd__c <= ' + String.valueOf(contractEndDateTo); 
            useAnd = true;
        }

        return soql;
    }

    //
    protected override void setStandardSetController() {

        //basic query string
        String soql = ' SELECT ' 
                    + '   Id,Name,PurchasingOffice__c,ShipmentCustomerAccount__c,SupplierCustomerCode__c,PaymentType__c,UnitBodyNumber__c'
                    + '   ,RegionName__c,MaintenanceContractPeriod__c,PurchasingOrder__c,WarehousePlanningDate__c '
                    + '   ,HeliumFillingImplementationDate__c,NSNRInspectionImplementationDate__c,NSRegularInspectionImplementationDate__c,ProductNumber__c'
                    + ' FROM '
                    + '   MaintenancePurchaseManagement__c ';

        //where
        soql = addWhereClauses(soql);

        //order by
        soql += ' ORDER BY ' + this.orderBy;
        if (this.orderDesc) {
            soql += ' DESC NULLS LAST';
        }

        //limit
        soql += ' LIMIT 10000 ';

        //Validate extracted records
        System.debug('soql: ' + soql);
        ssc = new ApexPages.StandardSetController(Database.getQueryLocator(soql));
        if (ssc.getResultSize() >= 10000 ) {
            ssc = null;
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, Label.JEOL_MaintSVCHistory_Message_TooMuchData));
            return;
        }
        else if(ssc.getResultSize() == 0){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.JEOL_MaintSVCHistory_Message_NoData));
                return;
        } else{
            ssc.setPageSize(pageSize);
            ssc.setPageNumber(pageNo);
        }


        mapRegionName = new Map<String, String>();
        
        if(ssc != null) {
            for (MaintenancePurchaseManagement__c row : (List<MaintenancePurchaseManagement__c>)ssc.getRecords()) {
                mapRegionName.put(row.RegionName__c, row.RegionName__c);
            }
        }
        
        for (SelectListManage__c reg : lsRegion) {
            mapRegionName.put(reg.Value__c, reg.Label__c);        
        }


    }

    //returns filtered search-records to VF-page
    public List<MaintenancePurchaseManagement__c> getSearchedRecords()
    {
        if(ssc != null) {
            List<MaintenancePurchaseManagement__c> searchedSupportCases = (List<MaintenancePurchaseManagement__c>)ssc.getRecords();
            return searchedSupportCases;
        }
        else {
            return new List<MaintenancePurchaseManagement__c>();
        }
    }
  
    //Initializes variables for deciding sorting order
    private void initSortingOrderVars(){
      //orderBy= 'ReceptionDate__c';
      //currentOrder = 'ReceptionDate__c';
      orderBy= 'Name';
      currentOrder = 'Name';
      orderDesc = false;
    }

    //For paging of table
     private void saveInputValuesInCookies() {
        List<Cookie> cookies = new List<Cookie>();

        addToCookie(pageNo, COOKIE_LABEL_PAGE_NUMBER, cookies);
        addToCookie(pageSize, COOKIE_LABEL_PAGE_NUMBER, cookies);
        addToCookie(this.initSearchFlg, COOKIE_LABEL_INIT_SEARCH_FLG, cookies);

        addToCookie(this.purchasingOffice, COOKIE_VALUE_PURCHASING_OFFICE, cookies);
        addToCookie(this.shippingCustomerName, COOKIE_VALUE_SHIPTO_CUSTOMER, cookies);
        addToCookie(this.paymentType, COOKIE_VALUE_PAYMENT_TYPE, cookies);
        addToCookie(this.unitBodyNumber, COOKIE_VALUE_UNITBODY_NUMBER, cookies);
        addToCookie(this.contractStartDateFrom, COOKIE_VALUE_MAINTENANCE_CONTRACTSTARTDATE_FROM, cookies);
        addToCookie(this.contractStartDateTo, COOKIE_VALUE_MAINTENANCE_CONTRACTSTARTDATE_TO, cookies);
        addToCookie(this.contractEndDateFrom, COOKIE_VALUE_MAINTENANCE_CONTRACTENDDATE_FROM, cookies);
        addToCookie(this.contractEndDateTo, COOKIE_VALUE_MAINTENANCE_CONTRACTENDDATE_TO, cookies);
        addToCookie(this.scheduledDeliverDate, COOKIE_VALUE_SCHEDULED_DELIVERYDATE, cookies);
        addToCookie(this.isAcceptanceSettled, COOKIE_VALUE_ISACCEPTANCESETTLED, cookies);

        String targetRegionsText = '';
        if (this.targetRegions != null && this.targetRegions.size() > 0) {
            targetRegionsText = String.join(this.targetRegions, '&&');
        }
        cookies.add(new Cookie(COOKIE_LABEL_TARGETREGIONS, targetRegionsText, COOKIE_PATH, -1, true));

        Apexpages.currentPage().setCookies(cookies);
    }

     private Integer getIntegerValueFromCookie(Map<String, Cookie> cookies, String cookieLabel, Integer defaultValue){
        Integer returnValue = defaultValue;
        if(cookies.containsKey(cookieLabel) && cookies.get(cookieLabel).getValue().length() != 0){
            try{
                returnValue = Integer.valueOf(cookies.get(cookieLabel).getValue());
            }
            catch(Exception exp){
                System.debug(exp.getMessage());
                returnValue = defaultValue;
            }
        }
        System.debug('cookieLabel: ' + cookieLabel + ' returnValue ' + returnValue);
        return returnValue;
    }

    private Date getDateValueFromCookie(Map<String, Cookie> cookies, String cookieLabel){
        Date returnValue = null;
        if(cookies.containsKey(cookieLabel) && cookies.get(cookieLabel).getValue().length() != 0)
        {
            try{
                returnValue = Date.parse(cookies.get(cookieLabel).getValue());
            }
            catch(Exception exp){
                System.debug(exp.getMessage());
                 return returnValue;
            }
        }
        return returnValue;
    }

     private String getTextValueFromCookie(Map<String, Cookie> cookies, String cookieLabel){
        String returnValue = null;
        if(cookies.containsKey(cookieLabel) && cookies.get(cookieLabel).getValue().length() != 0){
            try{
                returnValue = cookies.get(cookieLabel).getValue();}
            catch(Exception exp){
                System.debug(exp.getMessage());
                returnValue = null;
            }
        }
        System.debug('cookieLabel: ' + cookieLabel + ' returnValue ' + returnValue);
        return returnValue;
    }

    private void initFieldFromCookie() {
        Map<String, Cookie> cookies = Apexpages.currentPage().getCookies();

        PageNo = getIntegerValueFromCookie(cookies,COOKIE_LABEL_PAGE_NUMBER, PageNo);
        PageSize = getIntegerValueFromCookie(cookies,COOKIE_LABEL_PAGE_SIZE, PageSize);

        this.initSearchFlg = getTextValueFromCookie(cookies, COOKIE_LABEL_INIT_SEARCH_FLG);

        this.contractStartDateFrom = getDateValueFromCookie(cookies, COOKIE_VALUE_MAINTENANCE_CONTRACTSTARTDATE_FROM);
        this.contractStartDateTo = getDateValueFromCookie(cookies, COOKIE_VALUE_MAINTENANCE_CONTRACTSTARTDATE_TO);
        this.contractEndDateFrom = getDateValueFromCookie(cookies, COOKIE_VALUE_MAINTENANCE_CONTRACTENDDATE_FROM);
        this.contractEndDateTo = getDateValueFromCookie(cookies, COOKIE_VALUE_MAINTENANCE_CONTRACTENDDATE_TO);
        this.scheduledDeliverDate = getTextValueFromCookie(cookies, COOKIE_VALUE_SCHEDULED_DELIVERYDATE);

        this.purchasingOffice = getTextValueFromCookie(cookies, COOKIE_VALUE_PURCHASING_OFFICE);
        this.paymentType = getTextValueFromCookie(cookies, COOKIE_VALUE_PAYMENT_TYPE);
        this.purchasingOffice = getTextValueFromCookie(cookies, COOKIE_VALUE_PURCHASING_OFFICE);
        this.shippingCustomerName = getTextValueFromCookie(cookies,COOKIE_VALUE_SHIPTO_CUSTOMER);
        //this.mpm.ShipmentCustomerAccount__c = getTextValueFromCookie(cookies,COOKIE_VALUE_SHIPTO_CUSTOMER);

        if (cookies.containsKey(COOKIE_LABEL_TARGETREGIONS)) {
            String targetRegionsText = cookies.get(COOKIE_LABEL_TARGETREGIONS).getValue();
            if (String.isNotBlank(targetRegionsText)) {
                this.targetRegions = targetRegionsText.split('&&');
            }
        }   

    }

    private void addToCookie(Integer value, String cookieLabel, List<Cookie> cookies){
        if(value != null)
            cookies.add(new Cookie(cookieLabel, String.valueOf(value), COOKIE_PATH, -1, true));
    }

    private void addToCookie(String value, String cookieLabel, List<Cookie> cookies){
        if(value != null)
            cookies.add(new Cookie(cookieLabel, value, COOKIE_PATH, -1, true));
        else
            cookies.add(new Cookie(cookieLabel, null, COOKIE_PATH, -1, true)); //added to nullify previous cookie value
    }

    private void addToCookie(Date value, String cookieLabel, List<Cookie> cookies){
        if(value != null)
            cookies.add(new Cookie(cookieLabel, value.format(), COOKIE_PATH, -1, true));
        else
            cookies.add(new Cookie(cookieLabel, null, COOKIE_PATH, -1, true)); //added to nullify previous cookie value
    }

     public void setSizeSaveCurrentPageSize() {
        changeSize();
        setCookieCurrentPageSize();
        setCookieCurrentPageNumber();
    }

    private void setCookieCurrentPageNumber() {
        if (ssc != null) {
            Apexpages.currentPage().setCookies(new List<Cookie>{new Cookie(COOKIE_LABEL_PAGE_NUMBER, String.valueOf(ssc.getPageNumber()), COOKIE_PATH, -1, true)});
        }
    }
    private void setCookieCurrentPageSize() {
        if (ssc != null) {
            Apexpages.currentPage().setCookies(new List<Cookie>{new Cookie(COOKIE_LABEL_PAGE_SIZE, String.valueOf(ssc.getPageSize()), COOKIE_PATH, -1, true)});
        }
    }

    public void nextAndSaveCurrentPageNumber() {
        next();
        setCookieCurrentPageNumber();
    }
    public void previousAndSaveCurrentPageNumber() {
        previous();
        setCookieCurrentPageNumber();
    }
    public void firstAndSaveCurrentPageNumber() {
        first();
        setCookieCurrentPageNumber();
    }
    public void lastAndSaveCurrentPageNumber() {
        last();
        setCookieCurrentPageNumber();
    }
    public void setJumpSaveCurrentPageSize() {
        jump();
        setCookieCurrentPageSize();
        setCookieCurrentPageNumber();
    }

    public class OptionDetail {
        public Boolean isSelected{get; set;}
        public Boolean beforeSelected{get; set;}
        public SelectOption option{get; set;}
        public String val{get; set;}
        public OptionDetail(SelectOption option, Boolean isSelected) {
            this.option = option;
            this.isSelected = isSelected;
            this.beforeSelected = this.isSelected;
        }
        
        public void cancel() {
            this.isSelected = this.beforeSelected;
        }

        public void apply() {
            this.beforeSelected = this.isSelected;
        }
        
        public void setSelected(Boolean isSelected) {
            this.isSelected = isSelected;
            this.beforeSelected = this.isSelected;
        }
    }
    
}