objects/MenuInfo__c.object
<CustomObject>
    <description>アイコンメニュー作成用
ユーザが使いやすいメニュー画面を、簡単に作成するためのコンポーネントです。</description>
    <fields>
        <fullName>Guide__c</fullName>
        <formula>MenuTitle__c &amp; MenuRefTitle__c &amp; SectionRefMenuTitle__c &amp; &quot;-&quot; &amp; LPAD(TEXT(IF( AND(LEN(MenuRefTitle__c)&gt;0, LEN(SectionRefMenuTitle__c)==0), SectionOrder__c, IF(AND(LEN(MenuRefTitle__c)==0, LEN(SectionRefMenuTitle__c)&gt;0), SectionRefOrder__c, 0))), 2, &quot;0&quot;) &amp; &quot;_&quot; &amp; SectionTitle__c &amp; SectionRefTitle__c&amp; &quot;-&quot; &amp; LPAD(text( ItemOrder__c ), 3, &quot;0&quot;) &amp; &quot;_&quot; &amp; ItemTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ガイド</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IconID__c</fullName>
        <label>アイコンID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemMenuStyle__c</fullName>
        <formula>CASE( TEXT(SectionRef__r.MenuRef__r.MenuStyle__c)
    , &quot;タイル（大）&quot;, &quot;vfMenuTileCss&quot;
    , &quot;タイル（大）（枠無し）&quot;, &quot;vfMenuTileNBCss&quot;
    , &quot;タイル（小）&quot;, &quot;vfMenuSmallTileCss&quot;
    , &quot;タイル（小）（枠無し）&quot;, &quot;vfMenuSmallTileNBCss&quot;
    , &quot;シンプル&quot;, &quot;vfMenuSimpleCss&quot;
    , &quot;カスタムスタイル&quot;, SectionRef__r.MenuRef__r.CustomMenuStyle__c 
    , &quot;vfMenuTileCss&quot;



)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>メニュースタイル表示</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemOrder__c</fullName>
        <label>アイテムの表示順序</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemShowHeader__c</fullName>
        <formula>CASE( text( SectionRef__r.MenuRef__r.Header__c )
, &quot;表示&quot;, &quot;true&quot;
, &quot;非表示&quot;, &quot;false&quot;
, &quot;true&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ヘッダ表示</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemSideBar__c</fullName>
        <formula>CASE( text(SectionRef__r.MenuRef__r.SideBar__c)
, &quot;表示&quot;, &quot;true&quot;
, &quot;非表示&quot;, &quot;false&quot;
, &quot;true&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>サイドバー表示</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemTitle__c</fullName>
        <label>アイテム名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>遷移先リンク</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectionFontSize__c</fullName>
        <formula>CASE(TEXT(SectionRef__r.MenuRef__r.MenuStyle__c), &apos;タイル（大）&apos;, &apos;大&apos;+TEXT(SectionRef__r.FontSize__c), &apos;タイル（大）（枠無し）&apos;, &apos;大&apos;+TEXT(SectionRef__r.FontSize__c), &apos;タイル（小）&apos;, &apos;小&apos;+TEXT(SectionRef__r.FontSize__c), &apos;タイル（小）（枠無し）&apos;, &apos;小&apos;+TEXT(SectionRef__r.FontSize__c),&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>セクションの文字のサイズ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectionMenuTabId__c</fullName>
        <formula>SectionRef__r.MenuTabId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>セクションメニュータブID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectionNumberOfCols__c</fullName>
        <formula>IF(TEXT(SectionRef__r.MenuRef__r.MenuStyle__c)==&apos;シンプル&apos;, TEXT(SectionRef__r.NumberOfCols__c), &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>セクションの列数</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectionRefMenuTitle__c</fullName>
        <formula>SectionRef__r.MenuRefTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>所属メニュー名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectionRefMenu__c</fullName>
        <formula>SectionRef__r.MenuRef__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>所属メニュー</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectionRefOrder__c</fullName>
        <formula>SectionRef__r.SectionOrder__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>所属セクションの表示順序</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SectionRefTitle__c</fullName>
        <formula>SectionRef__r.SectionTitle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>所属セクション名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectionRef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>所属セクション</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MenuInfo__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>セクション</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MenuInfo__c</referenceTo>
        <relationshipLabel>アイテム</relationshipLabel>
        <relationshipName>MenuInfoSectionRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShowChatter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Chatter表示ボタンを表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TabId__c</fullName>
        <label>タブID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TargetWindowName__c</fullName>
        <formula>CASE(TEXT( TargetWindow__c )
    , &quot;自ウィンドウ&quot;, &quot;_self&quot;
    , &quot;新規ウィンドウ&quot;, &quot;_blank&quot;
    , &quot;_self&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>遷移先ウィンドウ名</label>
        <type>Text</type>
    </fields>
    <label>メニュー情報</label>
    <nameField>
        <displayFormat>MNU-{00000000}</displayFormat>
        <label>管理ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/clsMenuControl.cls
public with sharing class clsMenuControl{

    static final String ITEM_RECORD_TYPE_NAME = 'アイテム';
    static final String DEFAULT_MENU_STYLE = 'vfMenuTileCss';

    String tabName = '';
    String itemRecordTypeId = '';

    public class MenuInfo {
        public String ItemTitle { get; private set; }
        public String IconID { get; private set; }
        public String Link { get; private set; }
        public String Target { get; private set; }
        public String NumberOfCols { get; private set; }
        public String FontSize { get; private set; }
        
        public MenuInfo(){
        }
        
        public MenuInfo(String pItemTitle, String pIconID, String pLink, String pTarget, String pNumberOfCols, String pFontSize){
            this.ItemTitle = pItemTitle;
            this.IconID = pIconID;
            this.Link = pLink;
            this.Target = pTarget;
            this.NumberOfCols = pNumberOfCols;
            this.FontSize = pFontSize;
        }
    }

    public MAP<String, LIST<MenuInfo>> MenuLists { get; private set; }
    public LIST<String> MenuKeys { get; private set; }
    public Boolean ShowSideBar { get; private set; }
    public Boolean ShowHeader { get; private set; }
    public String MenuStyle { get; private set; }
    public Boolean ShowChatter { private set; }
    private Map<String,Schema.RecordTypeInfo> rtMapByName;

    public clsMenuControl(){
        tabName = ApexPages.currentPage().getParameters().get('sfdc.tabName');

        Schema.DescribeSObjectResult d = Schema.SObjectType.MenuInfo__c; 
        rtMapByName = d.getRecordTypeInfosByName();

        itemRecordTypeId = rtMapByName.get(ITEM_RECORD_TYPE_NAME).getRecordTypeId();
        
        MenuLists = new MAP<String, LIST<MenuInfo>>();
        MenuKeys = new LIST<String>();
        
        ShowSideBar = true;
        ShowHeader = true;
        MenuStyle = DEFAULT_MENU_STYLE;
        
        setMenuList();
    }
    
    public Boolean getShowChatter(){
        List<MenuInfo__c> menuInfoList = [Select showChatter__c  From MenuInfo__c  Where TabId__c = :tabName AND RecordTypeId = :rtMapByName.get('メニュー').getRecordTypeId() Limit 1];
        if(menuInfoList.size()==0) return false;
        else return menuInfoList[0].showChatter__c;
    }
    
    private void setMenuList(){
        String key = '';
        LIST<MenuInfo> vals = new LIST<MenuInfo>();

        // added below 4 lines (2014/7/18)
        if(!isAccessibleForMenuInfoFields())
        {
            return;
        }
        
        try {
            LIST<MenuInfo__c> items = [
                Select
                       m.Id, m.ItemOrder__c, m.ItemTitle__c, m.Name, m.RecordTypeId, m.SectionMenuTabId__c
                     , m.SectionRef__c, m.SectionRefMenu__c, m.SectionRefMenuTitle__c
                     , m.SectionRefOrder__c, m.SectionRefTitle__c, m.IconID__c, m.Link__c
                     , m.ItemSideBar__c, m.ItemShowHeader__c, m.ItemMenuStyle__c, m.TargetWindowName__c
                     , m.SectionNumberOfCols__c, m.SectionFontSize__c 
                  from MenuInfo__c m
                 where m.RecordTypeId = :itemRecordTypeId
                   and m.SectionMenuTabId__c = :tabName 
                 order by m.Guide__c
            ];
            
            for(MenuInfo__c it: items){
                if(it.ItemMenuStyle__c != MenuStyle){
                    MenuStyle = it.ItemMenuStyle__c;
                }
                ShowHeader= (it.ItemShowHeader__c == 'true');
                ShowSideBar = (it.ItemSideBar__c == 'true');

                if(key == it.SectionRefTitle__c){
                    vals.add(new MenuInfo(it.ItemTitle__c, it.IconID__c, it.Link__c, it.TargetWindowName__c, it.SectionNumberOfCols__c, it.SectionFontSize__c));
                } else {
                    if(!vals.isEmpty() && key != ''){
                        MenuLists.put(key, vals);
                        MenuKeys.add(key);
                        vals = new LIST<MenuInfo>();
                    }
                    key = it.SectionRefTitle__c;
                    vals.add(new MenuInfo(it.ItemTitle__c, it.IconID__c, it.Link__c, it.TargetWindowName__c, it.SectionNumberOfCols__c, it.SectionFontSize__c));
                }
            }
            if(!vals.isEmpty() && key != ''){
                MenuLists.put(key, vals);
                MenuKeys.add(key);
            }
        } catch (Exception e) {
            System.Debug(e);
        }
    }

     // added below 28 lines (2014/7/18)
    private Boolean isAccessibleForMenuInfoFields() {
        Set<String> fields = new Set<String>{
            'Id','ItemOrder__c','ItemTitle__c','Name','RecordTypeId','SectionMenuTabId__c'
            ,'SectionRef__c','SectionRefMenu__c','SectionRefMenuTitle__c'
            ,'SectionRefOrder__c','SectionRefOrder__c','IconID__c','Link__c'
            ,'ItemSideBar__c','ItemShowHeader__c','ItemMenuStyle__c','TargetWindowName__c','SectionNumberOfCols__c', 'SectionFontSize__c' };

        Schema.DescribeSObjectResult descResult = MenuInfo__c.SObjectType.getDescribe();
        Map<String,Schema.SObjectField> fieldMap = descResult.fields.getMap();
        Set<String> checkTargetKeys = new Set<String>();
        for(String fieldName : fields) {
            for(String key : fieldMap.keySet()) {
                if(fieldName.equalsIgnoreCase(key)) {
                    checkTargetKeys.add(key);
                }
            }
        }

        for(String key : checkTargetKeys) {
            Schema.SObjectField field = fieldMap.get(key);
            Schema.DescribeFieldResult descFieldResult = field.getDescribe();
            if(!descFieldResult.isAccessible()) {
                return false;
            }
        }
        
        return true;
    }
    
    @isTest(SeeAllData=true)
    static void testClsMenuControl() {
        clsMenuControl ctrl = new clsMenuControl();        

        ctrl.setMenuList();

        MenuInfo__c testMenu1 = new MenuInfo__c(RecordTypeId=ctrl.itemRecordTypeId);
        insert testMenu1;

        ctrl.setMenuList();

        MenuInfo__c testMenu2 = new MenuInfo__c(RecordTypeId=ctrl.itemRecordTypeId);
        insert testMenu2;

        ctrl.setMenuList();
    }
}