objects/NotifierObject__c.object
<CustomObject>
    <description>LEX(Lightning)移行時 削除予定</description>
    <fields>
        <fullName>contentFontColor__c</fullName>
        <defaultValue>&quot;black&quot;</defaultValue>
        <label>お知らせ事項の色</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contentFontSize__c</fullName>
        <defaultValue>2</defaultValue>
        <label>お知らせ事項の文字サイズ</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>contents__c</fullName>
        <label>お知らせ事項</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>detailUrl__c</fullName>
        <label>お知らせ詳細 URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>endDate__c</fullName>
        <label>掲載終了日</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>headerFontColor__c</fullName>
        <defaultValue>&quot;blue&quot;</defaultValue>
        <label>見出しの色</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>headerFontSize__c</fullName>
        <defaultValue>2</defaultValue>
        <label>見出しの文字サイズ</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>orderNumber__c</fullName>
        <label>表示順</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>startDate__c</fullName>
        <label>掲載開始日</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>お知らせ事項</label>
    <nameField>
        <label>見出し名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NotiferController.cls
public class NotiferController {

    private List<NotifierObject__c> ns;
    private Integer l = 10;
    
    public List<NotifierObject__c> getNotifiers() {
        Date today = Date.today();
        ns = [SELECT Id, Name, orderNumber__c, detailUrl__c, startDate__c, endDate__c, contents__c, headerfontcolor__c, headerfontsize__c, contentfontcolor__c, contentfontsize__c
                FROM NotifierObject__c
                WHERE startDate__c <=:today AND endDate__c >=:today
                ORDER BY orderNumber__c ASC 
                LIMIT :l];

        return ns;
    }
    
    static testMethod void doTest() {
        NotiferController nc = new NotiferController();
        List<NotifierObject__c> ns = nc.getNotifiers();
    }
}