objects/OperationHistory__c.object
<CustomObject>
    <fields>
        <fullName>CallCenterReceptionNo__c</fullName>
        <label>コールセンター受付番号</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CorrespondenceNumber__c</fullName>
        <label>対応番号</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>コメント</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDatetime__c</fullName>
        <label>対応完了日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>対応内容</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Responce__c</fullName>
        <formula>CASE(Interaction__c , 1, &quot;一次&quot;, 2, &quot;二次&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>対応</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDatetime__c</fullName>
        <label>対応開始日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>顧客対応票</label>
        <referenceTo>Support__c</referenceTo>
        <relationshipLabel>対応履歴</relationshipLabel>
        <relationshipName>OperationHistries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>対応履歴</label>
    <nameField>
        <label>件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (販売先取引先)</relationshipLabel>
        <relationshipName>SalesAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (出荷先取引先)</relationshipLabel>
        <relationshipName>ShipmentAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>seikyusakiAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>請求先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>販売オーダ (請求先)</relationshipLabel>
        <relationshipName>SalesOrders_SeikyusakiAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesResult__c.object
<CustomObject>
    <description>削除対象Object
※別売上Objectに変更</description>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>売上</relationshipLabel>
        <relationshipName>SalesResults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>hanbaisaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (販売先)</relationshipLabel>
        <relationshipName>aaaS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>seikyusaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>請求先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (請求先)</relationshipLabel>
        <relationshipName>cccS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>shukkasaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>売上 (出荷先)</relationshipLabel>
        <relationshipName>bbbS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>売上</label>
    <nameField>
        <label>売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ServiceOrder__c.object
<CustomObject>
    <fields>
        <fullName>CallCenterReceptionNo__c</fullName>
        <formula>Customer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>コールセンター受付番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RetrieveDate__c</fullName>
        <label>回収日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ReturnDate__c</fullName>
        <label>返却日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ReturnDueDate__c</fullName>
        <label>返却予定日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SalesAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>サービスオ販売先取引先ーダ ()</relationshipLabel>
        <relationshipName>ServiceOrders_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipmentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷先取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>サービスオーダ</relationshipLabel>
        <relationshipName>ServiceOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>サービスオーダ</label>
    <nameField>
        <label>サービスオーダ</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ServiceOrderControl__c.object
<CustomObject>
    <fields>
        <fullName>RetrieveDate__c</fullName>
        <label>回収日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ReturnDate__c</fullName>
        <label>返却日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ReturnDueDate__c</fullName>
        <label>返却予定日（旧）</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ServiceOrder__c</fullName>
        <label>サービスオーダ</label>
        <referenceTo>ServiceOrder__c</referenceTo>
        <relationshipLabel>サービスオーダ材料費</relationshipLabel>
        <relationshipName>ServiceOrderControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SetNo__c</fullName>
        <label>セット番号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>サービスオーダ材料費</label>
    <nameField>
        <label>サービスオーダ材料費名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support__c.object
<CustomObject>
    <fields>
        <fullName>CallCenterUketsukeNo_Sync__c</fullName>
        <externalId>true</externalId>
        <label>コールセンター受付No_連携用</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Responce__c</fullName>
        <label>対応内容</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ServiceEndDate__c</fullName>
        <label>顧客対応終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ServiceStartDate__c</fullName>
        <label>顧客対応開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>コール応答中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>コール保留</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>対応依頼</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応終了</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>一次対応にて完了</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>二次対応中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>二次対応完了</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>顧客対応票</label>
    <nameField>
        <label>コールセンター受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_ObjectTriggerHadler.cls
public with sharing class JEOL_ObjectTriggerHadler {

    /**
     *  コメントを内容に格納する。超過分は切り捨てる。
     */
	public static void operationHistory_descriptionToMemo(List<OperationHistory__c> recs) {
        for (OperationHistory__c rec: recs) {
            String memoText = rec.Description__c;
            if (memoText != null && memoText.length() > 255) {
                memoText = memoText.substring(0, 254);
                memoText += '…';
            }
            rec.Memo__c = memoText;
        }
	}
	
    /**
     *  Todoの参照先を設定する。対象は顧客対応表。
     */
    public static void operationHistory_relationshipToSupport(List<OperationHistory__c> recs) {
        Set<String> ccNos = new Set<String>();
        for(OperationHistory__c rec : recs) {
            String ccNo = rec.CallCenterReceptionNo__c;
            if (ccNo != null) {
                ccNos.add(ccNo);
            }
        }

        Map<String, String> supportIdMap = new Map<String, String>();
        for(Support__c rec: [SELECT Id, Name FROM Support__c WHERE Name IN: ccNos]) {
            supportIdMap.put(rec.Name, rec.Id);
        }
        for(OperationHistory__c rec: recs) {
            if(String.isNotBlank(rec.CallCenterReceptionNo__c)) {
                rec.Support__c = supportIdMap.get(rec.CallCenterReceptionNo__c);
            }
        }
    }

    /**
     *  登録された対応履歴をもとに顧客対応表の開始日、終了日を設定する。
     */
    public static void operationHistory_putServiceDateToSupport(List<OperationHistory__c> recs) {
        List<String> ccNos = new List<String>();
        for(OperationHistory__c rec : recs) {
        	String ccNo = rec.CallCenterReceptionNo__c;
        	if (String.isNotBlank(ccNo)) {
	            ccNos.add(ccNo);
        	}
        }

        List<Support__c> supports = [
                SELECT
                     Id, CallCenterUketsukeNo_Sync__c, ServiceStartDate__c, ServiceEndDate__c,
                    (SELECT Id, CorrespondenceNumber__c, Name, StartDatetime__c, EndDatetime__c, Description__c, Status__c From OperationHistries__r)
                FROM
                    Support__c
                    
                WHERE
                    Name IN: ccNos
        ];
        
        List<Support__c> updateTargets = new List<Support__c>();
        for(Support__c supportRec: supports) {
	        Decimal firstCorrespondenceNumber = 1000000000;
	        Decimal secondCorrespondenceNumber = 0;
            for(OperationHistory__c targetRec: supportRec.OperationHistries__r) {
                DateTime startDateTime = targetRec.StartDatetime__c;
                DateTime endDateTime = targetRec.EndDatetime__c;

                if(startDateTime != NULL && endDateTime != NULL) {
                    String subjectText = targetRec.Name;
                    Decimal correspondenceNumber = targetRec.CorrespondenceNumber__c;

                    if(subjectText == '一次' && correspondenceNumber < firstCorrespondenceNumber) {
                        supportRec.ServiceStartDate__c = startDateTime.date();
                        firstCorrespondenceNumber = correspondenceNumber;
                    }

                    if (subjectText == '二次' && correspondenceNumber > secondCorrespondenceNumber) {
                        supportRec.Responce__c = targetRec.Description__c;
                        if(targetRec.Status__c == 'Completed') {
                            supportRec.ServiceEndDate__c = endDateTime.date();
                            secondCorrespondenceNumber = correspondenceNumber;
                        }
                    }
                }
            }
            updateTargets.add(supportRec);
        }
        update updateTargets;
    }
    
    /**
     *  販売オーダが更新されたとき、販売オーダラインを辿った先にある売上げに対して取引先の更新を行う
     */
    public static void salesOrder_AccountReferenceToSalesResult(List<SalesOrder__c> salesOrders) {
        Map<String, SalesOrder__c> idSalesOrderMap = new Map<String, SalesOrder__c>();
        for (SalesOrder__c rec: salesOrders) {
            idSalesOrderMap.put(rec.id, rec);
        }
        
        List<SalesResult__c> salesResults = [SELECT id, shukkasaki__c, seikyusaki__c, hanbaisaki__c, SalesOrder__c FROM SalesResult__c WHERE SalesOrder__c IN: idSalesOrderMap.keySet()];
        if (!salesResults.isEmpty()) {
            for (SalesResult__c rec: salesResults) {
                if (idSalesOrderMap.containsKey(rec.SalesOrder__c)) {
                    SalesOrder__c targetOrder = idSalesOrderMap.get(rec.SalesOrder__c);
                    rec.shukkasaki__c = targetOrder.ShipmentAccount__c;
                    rec.seikyusaki__c = targetOrder.seikyusakiAccount__c;
                    rec.hanbaisaki__c = targetOrder.SalesAccount__c;
                }
            }
            update salesResults;
        }
    }
    /**
     *  受け取った販売オーダラインNo_連携用項目から、売上オブジェクトに各種取引先の参照関係を作成する。
     */
    public static void salesResult_relationshipToAccount(List<SalesResult__c> recs) {
        Set<String> targetOrderIds = new Set<String>();
        for(SalesResult__c rec : recs) {
            String salesOrderId = rec.SalesOrder__c;
            if (String.isNotblank(salesOrderId)) {
                targetOrderIds.add(salesOrderId);
            }
        }
        
        if (!targetOrderIds.isEmpty()) {
            List<SalesOrder__c> orders = [SELECT id, SalesAccount__c, ShipmentAccount__c, seikyusakiAccount__c FROM SalesOrder__c WHERE id =: targetOrderIds];
            Map<String, SalesOrder__c> orderMap = new Map<String, SalesOrder__c>();
            for (SalesOrder__c orderRec: orders) {
                orderMap.put(orderRec.id, orderRec);
            }
            for(SalesResult__c rec: recs) {
                String salesOrderId = rec.SalesOrder__c;
                if(orderMap.containsKey(salesOrderId)) {
                    SalesOrder__c tergetOrder = orderMap.get(salesOrderId);
                    rec.hanbaisaki__c = tergetOrder.SalesAccount__c;
                    rec.shukkasaki__c = tergetOrder.ShipmentAccount__c;
                    rec.seikyusaki__c = tergetOrder.seikyusakiAccount__c;
                }
            }
        }
    }
    
    public static Boolean isServiceOrderControlUpdate = true;
    public static void serviceOrderControl_dateSync(List<ServiceOrderControl__c> recs) {
    	Set<String> condisions = new Set<String>();
    	for (ServiceOrderControl__c rec: recs) {
			String parentIdCondition = ' ServiceOrder__c = \'' + JEOLUtil.escapeNull(rec.ServiceOrder__c) + '\' ';
			String setNoCondition = ' SetNo__c = \'' + JEOLUtil.escapeNull(rec.SetNo__c) + '\' ';
			condisions.add(' ( ' + parentIdCondition + ' AND ' + setNoCondition +' )');
		}
		if (condisions.size() > 0) {
			String queryStr = ' SELECT Id, ServiceOrder__c, SetNo__c, ReturnDate__c, ReturnDueDate__c, RetrieveDate__c FROM ServiceOrderControl__c ';
			queryStr += ' WHERE ' + String.join(new List<String>(condisions), ' OR ');
			List<ServiceOrderControl__c> targetControlRecs = Database.query(queryStr);
			Map<String, List<ServiceOrderControl__c>> controlMap = new Map<String, List<ServiceOrderControl__c>>();
			for (ServiceOrderControl__c rec: targetControlRecs) {
				String serviceOrderId = rec.ServiceOrder__c;
				String setNo = rec.SetNo__c;
				String key = serviceOrderId + '_' + setNo;
				if (!controlMap.containsKey(key)) {
					controlMap.put(key, new List<ServiceOrderControl__c>());
				}
				controlMap.get(key).add(rec);
			}
			List<ServiceOrderControl__c> updateRecs = new List<ServiceOrderControl__c>();
			for (ServiceOrderControl__c rec: recs) {
				String serviceOrderId = rec.ServiceOrder__c;
				String setNo = rec.SetNo__c;
				String key = serviceOrderId + '_' + setNo;
				if (controlMap.containsKey(key)) {
					List<ServiceOrderControl__c> updateTargets = controlMap.get(key);
					for (ServiceOrderControl__c target: updateTargets) {
						if (rec.id != target.Id) {
							target.ReturnDate__c = rec.ReturnDate__c;
							target.ReturnDueDate__c = rec.ReturnDueDate__c;
							target.RetrieveDate__c = rec.RetrieveDate__c;
							updateRecs.add(target);
						}
					}
				}
			}
			isServiceOrderControlUpdate = false;
			update updateRecs;
		}
   }
}