objects/OrderPlan__c.object
<CustomObject>
    <description>削除対象Object</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>見積No</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipName>OrderPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipName>OrderPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>×受注予定</label>
    <nameField>
        <label>受注予定No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <description>削除対象OBject</description>
    <fields>
        <fullName>OrderPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注予定</label>
        <referenceTo>OrderPlan__c</referenceTo>
        <relationshipLabel>商談</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>商談</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>見積</label>
    <nameField>
        <label>見積No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>見積</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>系列（装置）</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SalesResult__c.object
<CustomObject>
    <description>削除対象Object
※別売上Objectに変更</description>
    <fields>
        <fullName>SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売オーダ</label>
        <referenceTo>SalesOrder__c</referenceTo>
        <relationshipLabel>売上</relationshipLabel>
        <relationshipName>SalesResults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>keiretsu__c</fullName>
        <label>系列</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>売上</label>
    <nameField>
        <label>売上名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ServiceOrder__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>顧客対応票</label>
        <referenceTo>Support__c</referenceTo>
        <relationshipLabel>サービスオーダ</relationshipLabel>
        <relationshipName>ServiceOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>サービスオーダ</label>
    <nameField>
        <label>サービスオーダ</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Support__c.object
<CustomObject>
    <fields>
        <fullName>SeriesPI__c</fullName>
        <formula>UnitBodyLink__r.Series__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>系列</label>
        <type>Text</type>
    </fields>
    <label>顧客対応票</label>
    <nameField>
        <label>コールセンター受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_AccessTriggerHandler.cls
public with sharing class JEOL_AccessTriggerHandler {
    
    public static void createServiceOrderShares(List<ServiceOrder__c> recs) {
        Map<String, String> idAndSeriesMap = new Map<String, String>();
        List<ServiceOrder__c> shareUseRecs = [SELECT id, Customer__r.SeriesPI__c FROM ServiceOrder__c WHERE id IN: recs];
        for (ServiceOrder__c rec: shareUseRecs) {
            idAndSeriesMap.put(rec.id, rec.Customer__r.SeriesPI__c);
        }
        JEOLUtil.setSameRoleSharing(ServiceOrder__c.SObjectType.getDescribe().getName(), idAndSeriesMap);
    }
    
    public static void createOrderPlanShares(List<OrderPlan__c> recs) {
        Map<String, String> idAndSeriesMap = new Map<String, String>();
        List<OrderPlan__c> shareUseRecs = [SELECT id, Series__c FROM OrderPlan__c WHERE id IN: recs];
        for (OrderPlan__c rec: shareUseRecs) {
            idAndSeriesMap.put(rec.id, rec.Series__c);
        }
        JEOLUtil.setSameRoleSharing(OrderPlan__c.SObjectType.getDescribe().getName(), idAndSeriesMap);
    }
    
    public static void createSalesResultShares(List<SalesResult__c> recs) {
        Map<String, String> idAndSeriesMap = new Map<String, String>();
        for (SalesResult__c rec: recs) {
            idAndSeriesMap.put(rec.id, rec.keiretsu__c);
        }
        JEOLUtil.setSameRoleSharing(SalesResult__c.SObjectType.getDescribe().getName(), idAndSeriesMap);
    }
    
    public static void createQuoteShares(List<Quote__c> recs) {
        Map<String, String> idAndSeriesMap = new Map<String, String>();
        for (Quote__c rec: recs) {
            idAndSeriesMap.put(rec.id, rec.Series__c);
        }
        JEOLUtil.setSameRoleSharing(Quote__c.SObjectType.getDescribe().getName(), idAndSeriesMap);
    }
    
    public static void createSalesOrderShares(List<SalesOrder__c> recs) {
        Map<String, String> idAndSeriesMap = new Map<String, String>();
        for (SalesOrder__c rec: recs) {
            idAndSeriesMap.put(rec.id, rec.Series__c);
        }
        JEOLUtil.setSameRoleSharing(SalesOrder__c.SObjectType.getDescribe().getName(), idAndSeriesMap);
    }
    
    public static void createSupportShares(List<Support__c> recs) {
        Map<String, String> idAndSeriesMap = new Map<String, String>();
        for (Support__c rec: recs) {
            idAndSeriesMap.put(rec.id, rec.SeriesPI__c);
        }
        JEOLUtil.setSameRoleSharing(Support__c.SObjectType.getDescribe().getName(), idAndSeriesMap);
    }
}