objects/QuotationDetailInformation__c.object
<CustomObject>
    <fields>
        <fullName>CertificationExpress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>直販/定価証明書出力</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Depth__c</fullName>
        <label>Depth</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DiscountAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>値引き金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DiscountRate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>値引き率</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IsDiscountTarget__c</fullName>
        <defaultValue>false</defaultValue>
        <label>値引設定対象</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>見積書情報</label>
        <referenceTo>QuotationInformation__c</referenceTo>
        <relationshipLabel>見積書詳細情報</relationshipLabel>
        <relationshipName>QuotationDetailInformations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>数量</label>
        <precision>8</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>ソート番号</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>見積書詳細情報</label>
    <nameField>
        <displayFormat>QT{00000000}</displayFormat>
        <label>見積書詳細</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuotationInformation__c.object
<CustomObject>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>住所（1）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine2__c</fullName>
        <label>住所（2）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine3__c</fullName>
        <label>住所（3）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CalendarExpress__c</fullName>
        <description>和暦、西暦の表示選択</description>
        <label>暦表示</label>
        <picklist>
            <picklistValues>
                <fullName>和暦</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>西暦</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DirectSalesExpress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>直販証明書　出力</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DirectSalesSheetIssueDate__c</fullName>
        <label>直販証明書　発行日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegulerPriceExpress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>定価証明書　出力</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RegulerPriceSheetIssueDate__c</fullName>
        <label>定価証明書　発行日</label>
        <type>Date</type>
    </fields>
    <label>見積書情報</label>
    <nameField>
        <label>見積名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_QuotationListPageCtrlTest.cls
@IsTest
private class JEOL_QuotationListPageCtrlTest {

    private static testMethod void test01() {
        
        QuotationInformation__c quot = new QuotationInformation__c();
        quot.AddressLine1__c = 'dummy';
        quot.AddressLine2__c = 'dummy';
        quot.AddressLine3__c = 'dummy';
        quot.DirectSalesExpress__c = true;
        quot.DirectSalesSheetIssueDate__c = Date.Today();
        quot.RegulerPriceExpress__c = true;
        quot.RegulerPriceSheetIssueDate__c = Date.Today();
        quot.CalendarExpress__c = '和暦';
        insert quot;
       
        List<QuotationDetailInformation__c> lsquotdet = new List<QuotationDetailInformation__c>();
        for (integer i = 0 ; i < 100 ; i++) {
            QuotationDetailInformation__c quotdet = new QuotationDetailInformation__c();
            quotdet.Parent__r = quot;
            quotdet.Parent__c = quot.id;
            quotdet.Depth__c = 1;
            quotdet.SortNo__c = 0;
            quotdet.IsDiscountTarget__c = true;
            quotdet.DiscountRate__c = 10;
            quotdet.DiscountAmount__c = 10;
            quotdet.CertificationExpress__c = true;
            quotdet.Quantity__c = 1;
            lsquotdet.add(quotdet);
        }
        insert lsquotdet;

        Pagereference ref = Page.JEOL_QuotationListPage;
        Map<String, String> params = new Map<String, String>();
        ref.getParameters().putAll(params);
                               
        Test.setCurrentPage(ref);
               
        JEOL_QuotationListPageCtrl ctrl = new JEOL_QuotationListPageCtrl();
        
        List<SelectOption> ret1 = ctrl.getSalesAreaOptions();
        List<SelectOption> ret2 = ctrl.getQuoteTypeOptions();
        List<SelectOption> ret3 = ctrl.getRecordTypeOptions();
        List<SelectOption> ret4 = ctrl.getSeriesOptions();
        ctrl.searchItemClear();
        ctrl.recordSearch();
        ctrl.targetRecords = '1';
        ctrl.getUrlParamFromEditorCopy();
        ctrl.getUrlParamFromEditorBranch();
        
        ctrl.targetQuoteNo = 'dummy';
        ctrl.targetName = 'dummy';
        ctrl.targetCustomerQuotationRequestedNo = 'dummy';
        ctrl.targetSalesPersonCode = 'dummy';
        ctrl.targetSalesPerson = 'dummy';
        ctrl.targetContractCode = 'dummy';
        ctrl.targetContractName = 'dummy';
        ctrl.targetShipmentCode = 'dummy';
        ctrl.targetShipmentName = 'dummy';
        ctrl.targetSeries = 'dummy';
        ctrl.targetCustomerQuotationRequestedNo = 'dummy';
        ctrl.targetQuotationType = 'dummy';
        ctrl.targetRecordType = 'dummy';
        ctrl.targetSalesArea = 'dummy';
        ctrl.RegisteredDateFrom = '2015-08-16';
        ctrl.RegisteredDateTo = '2015-08-16';
        
        ctrl.recordSearch();
        
        ctrl.switchingOrder();
        List<QuotationInformation__c> ret5 = ctrl.getRecords();
        
        QuotationInformation__c ret6 = ctrl.rec;
    }
    
}