objects/QuotationInformation__c.object
<CustomObject>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>住所（1）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine2__c</fullName>
        <label>住所（2）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine3__c</fullName>
        <label>住所（3）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CalendarExpress__c</fullName>
        <description>和暦、西暦の表示選択</description>
        <label>暦表示</label>
        <picklist>
            <picklistValues>
                <fullName>和暦</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>西暦</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DestinationAddress__c</fullName>
        <label>送付案内 住所</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DestinationGuideDate__c</fullName>
        <label>送付案内日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DirectSalesExpress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>直販証明書　出力</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DirectSalesSheetIssueDate__c</fullName>
        <label>直販証明書　発行日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegulerPriceExpress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>定価証明書　出力</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RegulerPriceSheetIssueDate__c</fullName>
        <label>定価証明書　発行日</label>
        <type>Date</type>
    </fields>
    <label>見積書情報</label>
    <nameField>
        <label>見積名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_QuotationDestinationPrintPageTest.cls
@IsTest
private class JEOL_QuotationDestinationPrintPageTest {

    private static testMethod void test01() {
        
        QuotationInformation__c quot = new QuotationInformation__c();
        quot.AddressLine1__c = 'dummy';
        quot.AddressLine2__c = 'dummy';
        quot.AddressLine3__c = 'dummy';
        quot.DirectSalesExpress__c = true;
        quot.DirectSalesSheetIssueDate__c = Date.Today();
        quot.RegulerPriceExpress__c = true;
        quot.RegulerPriceSheetIssueDate__c = Date.Today();
        quot.CalendarExpress__c = '和暦';
        quot.DestinationAddress__c = 'dummy';
        quot.DestinationGuideDate__c = Date.Today();
        
        insert quot;

        Pagereference ref = Page.JEOL_QuotationDestinationPrintPage;
        Map<String, String> params = new Map<String, String>();
        params.put('id', quot.id);
        params.put('preview', '1');
        params.put('print', '1');
        ref.getParameters().putAll(params);
                               
        Test.setCurrentPage(ref);
               
        JEOL_QuotationDestinationPrintPageCtrl ctrl = new JEOL_QuotationDestinationPrintPageCtrl();
        
        List<String> ret1 = ctrl.pdfData.getBodyLines();
        String ret2 = ctrl.pdfData.getDestinationGuideDate();
        
    }
    
}