objects/QuotationDetailInformation__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <label>見積書情報</label>
        <referenceTo>QuotationInformation__c</referenceTo>
        <relationshipLabel>見積書詳細情報</relationshipLabel>
        <relationshipName>QuotationDetailInformations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>見積書詳細情報</label>
    <nameField>
        <displayFormat>QT{00000000}</displayFormat>
        <label>見積書詳細</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuotationInformation__c.object
<CustomObject>
    <label>見積書情報</label>
    <nameField>
        <label>見積名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_QuotationDetailRedirect_ctrl.cls
public with sharing class JEOL_QuotationDetailRedirect_ctrl {

    String sParentID = null;
    
    public JEOL_QuotationDetailRedirect_ctrl(ApexPages.StandardController stdController) {
    
        if(!Test.isRunningTest()) {
            stdController.addFields(new List<String>{'Parent__r'});
        }
        QuotationDetailInformation__c quotDet = (QuotationDetailInformation__c) stdController.getRecord();
        If (quotDet != null && quotDet.id != null && quotDet.Parent__r != null) {
            sParentID = '' + quotDet.Parent__r.id;
        }
    
    }
    
    public PageReference redirect(){
        if(sParentID != null){
            PageReference pageRef = new PageReference('/apex/JEOL_QuotationEditorPage');
            pageRef.getParameters().put('id', sParentID);
            return pageRef;
        } else {
            return null;
        }
    }
    
}