objects/QuotationDetailInformation__c.object
<CustomObject>
    <fields>
        <fullName>Depth__c</fullName>
        <label>Depth</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>見積書情報</label>
        <referenceTo>QuotationInformation__c</referenceTo>
        <relationshipLabel>見積書詳細情報</relationshipLabel>
        <relationshipName>QuotationDetailInformations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SortNo__c</fullName>
        <label>ソート番号</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>見積書詳細情報</label>
    <nameField>
        <displayFormat>QT{00000000}</displayFormat>
        <label>見積書詳細</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuotationInformation__c.object
<CustomObject>
    <label>見積書情報</label>
    <nameField>
        <label>見積名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_QuotationDetailRedirect_ctrlTest.cls
@IsTest
private class JEOL_QuotationDetailRedirect_ctrlTest {

    private static testMethod void test01() {
        
        QuotationInformation__c quot = new QuotationInformation__c();
        insert quot;
        
        QuotationDetailInformation__c quotdet = new QuotationDetailInformation__c();
        quotdet.Parent__r = quot;
        quotdet.Parent__c = quot.id;
        quotdet.Depth__c = 1;
        quotdet.SortNo__c = 0;
        insert quotdet;

        Pagereference ref = Page.JEOL_QuotationEditorPage;
        Map<String, String> params = new Map<String, String>();
        params.put('id', quot.id);
        ref.getParameters().putAll(params);
                               
        Test.setCurrentPage(ref);
               
        JEOL_QuotationDetailRedirect_ctrl ctrl = new JEOL_QuotationDetailRedirect_ctrl(new ApexPages.StandardController(quotdet));
        
        PageReference ret = ctrl.redirect();
    }

    private static testMethod void test02() {
        
        QuotationInformation__c quot = new QuotationInformation__c();
        insert quot;
        
        QuotationDetailInformation__c quotdet = new QuotationDetailInformation__c();
        quotdet.Parent__c = quot.id;
        quotdet.Depth__c = 1;
        quotdet.SortNo__c = 0;
        insert quotdet;

        Pagereference ref = Page.JEOL_QuotationEditorPage;
        Map<String, String> params = new Map<String, String>();
        params.put('id', quot.id);
        ref.getParameters().putAll(params);
                               
        Test.setCurrentPage(ref);
               
        JEOL_QuotationDetailRedirect_ctrl ctrl = new JEOL_QuotationDetailRedirect_ctrl(new ApexPages.StandardController(quotdet));
        
        PageReference ret = ctrl.redirect();
    }
}