objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>MaintenanceEndDateFormula__c</fullName>
        <formula>Datevalue(MaintenanceEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約終了日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaintenanceStartDateFormula__c</fullName>
        <formula>Datevalue(MaintenanceStartDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>保守契約開始日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <label>製番</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBodyLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>販売オーダ</relationshipLabel>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>販売オーダ</label>
    <nameField>
        <label>販売オーダNo</label>
        <type>Text</type>
    </nameField>
    <recordTypes>
        <fullName>HosyuKeiyaku</fullName>
        <active>true</active>
        <label>保守契約詳細</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Support__c.object
<CustomObject>
    <fields>
        <fullName>MaintenanceSituation__c</fullName>
        <formula>UnitBodyLink__r.SvcForm__c</formula>
        <label>保守契約状況</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitBodyLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>本体号機</label>
        <referenceTo>UnitBody__c</referenceTo>
        <relationshipLabel>顧客対応票</relationshipLabel>
        <relationshipName>Support</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>顧客対応票</label>
    <nameField>
        <label>コールセンター受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JEOL_AddSupportLayout_ctrl.cls
public with sharing class JEOL_AddSupportLayout_ctrl{

    public Support__c rec {get; set;}

    /**
    * コンストラクタ
    */
    public JEOL_AddSupportLayout_ctrl(ApexPages.StandardController stdController){

        // 顧客対応票の使用項目リストを作成
        List<String> fields = new List<String>();
        fields.add('UnitBodyLink__c');
        fields.add('MaintenanceSituation__c');

        // 使用項目リストをStandardControllerに指定（テストクラスの場合は回避）
        if(!Test.isRunningTest()) {
            stdController.addFields(fields);
        }

        // レコード取得
        this.rec = (Support__c)stdController.getRecord();
    }

    /**
    * 保守契約製番取得
    */
    public String getProductNumber(){
    
        date today = System.Today();
        List<SalesOrder__c> ordList;
        ordList = [select ProductNumber__c
                    from SalesOrder__c 
                    where UnitBodyLink__c =: this.rec.UnitBodyLink__c
                    and MaintenanceStartDateFormula__c <=: today
                    and MaintenanceEndDateFormula__c >=: today
                    and RecordTypeId IN 
                        (select Id from RecordType 
                            where SobjectType = 'SalesOrder__c' 
                            and developerName = 'HosyuKeiyaku')
                    order by MaintenanceEndDateFormula__c desc
                    , Name desc
                    nulls last
                    Limit 1 ];

        String resultStr = '';
        if (ordList != null && ordList.size() != 0) {
            resultStr = ordList[0].ProductNumber__c;
        }
        return resultStr;
    }

}